### ISSUE TITLE
Bots: Export Bot (NFMT L2 -> L1)

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#111]
User calls Export Bot to send Item to a Mainnet wallet, specifying a Mainnet ETH address to send to

Export Bot checks whether this NFT contract has already been exported and deployed at Mainnet (via Export Factory smart contract or a connected Directory service)

If it has already been exported, user only needs to pay for Item transfer operation. Item is transferred inside L2 to a bridge contract, frozen there and then minted at its L1 copy where it is released and transferred to a target wallet. This costs e.g. 50 Coins.

During the above operation any L1/L2 consensus conflicts should be resolved. For example, if L1 item is already "spent" (transferred somewhere) on L1 - L1 remains the ground truth. Within bridging and contracts logic however efforts should be made to avoid such conflicts.

If the Item L2 contract has not been deployed at L1 yet, user has to pay for its deployment as well. In such case the Export Factory contract deploys a new contract at L1 with same properties as the L2 original. User has to pay e.g. 500 Coins for such operation to cover much higher gas fees to deploy a new L1 contract.

**Comment by dzinzyura** [comment]
Done. Thank you, Borys!

![Screenshot_43](https://user-images.githubusercontent.com/99117374/187873843-eb5cd518-3301-4bfa-8b4a-9903641c252f.png)
![Screenshot_44](https://user-images.githubusercontent.com/99117374/187873846-dc568c89-41dc-45ad-8456-0cc057a3e5bb.png)
