### ISSUE TITLE
"Chat" profile screen button

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#112]
Let's add " 💬 Chat " button into user profiles so that users can contact each other directly from the Profile screen and not just from the in-chat message menu.

![IMG_20220718_073935.jpg](https://user-images.githubusercontent.com/328787/179457024-726d4141-da2d-4df8-bb48-0e38d3844f9a.jpg)

Note: some users will have "Personal Assistant" bot that is going to auto-respond and provide options for the incoming messages.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/180729915-94cf5896-ee2d-465f-95a6-a28169b3be52.mov

**Comment by phwizard** [comment]
@4RGUS please merge this.
