### ISSUE TITLE
Bots - auto-responder bot

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#116]
The task is to create a sample demo bot that provides information about the user or a business when they are contacted. 

This should work as following:

Auto-responder bot should know the JID of its owner. 

1. Bot joins any chat room where its owner is added  _(this is handled outside of your logic so just assume this is done)_
2. Bot only proceeds if there are no more than 3 participants in the room (this is to avoid spam in cases where there are group chats - our main goal is to have bot work in 1:1 chat scenarios).
3. Monitor presences in the room. As soon as a presence is detected of another user (not owner and not the bot itself), the bot should proceed with its Informational Sequence.

**Detecting the presence**:

As discussed, standard presence mechanism isn't very reliable for this. Let's do the following:

1. Client app sends “isComposing” for a few milliseconds upon user joining or re-joining a chat.
2. Bot checks the “isComposing” stanzas and if it comes from a user who hasn’t been active (no “isComposing” received over last 10 minutes), treat this as user has just entered and proceed with the scenario.

N.B.
_we could create another technical stanza just for “wave” 👋  function, if that’s better for any reason,
however detecting any fresh “isComposing” activity should work as well.
using “isComposing” is also better because in case client app has not implemented that logic or bot has missed that “automatic” isComposing for a few milliseconds, bot will still react to a user when user starts typing something. Which is better than no reaction at all._

using “isComposing” is also better because in case client app has not implemented that logic or bot has missed that “automatic” isComposing for a few milliseconds, bot will still react to a user when user starts typing something. Which is better than no reaction at all

**Informational sequence example**:

=======

Hi, I'm assisting here. 

--

Did you want to learn more about our products and services or just wanted to chat?

--

[ Learn about products & services ]

[ Chat ]

=======

**Comment by dzinzyura** [comment]
Ready for review. @phwizard everything works fine, we just need some text for "Learn about.." part

https://user-images.githubusercontent.com/99117374/194004306-bfb85437-d075-4cad-9452-47ea61968ea5.MP4
