### ISSUE TITLE
Users & Bots invite & auto-join mechanism

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#119]
Mechanism to automatically / programmatically invite users and bots into new chat rooms. 

**Auto-join mechanism**
And for the bot to auto-join rooms following such invite. 

~~Shall we use XEP-0249?~~
~~https://xmpp.org/extensions/xep-0249.html~~

Agreed that this can be used as it's already implemented server side:
XEP-0045 - https://xmpp.org/extensions/xep-0045.html#invite

**Mechanism to remember rooms joined**
Bot should maintain a list of rooms it is present in (store it in DB). (And its state for each room.)
Or possibly it's already handled by XMPP roster for all users.

**Invite mechanism**
Users should be able to invite other users and bots by using `@<username>` mechanism (just type "at" sign followed by JID or human readable user name)

**Comment by Akick** [comment]
XEP-0249 not implemented in ejabberd
But we can use XEP-0045 - https://xmpp.org/extensions/xep-0045.html#invite

**Comment by phwizard** [comment]
This works.
