### ISSUE TITLE
Video play overlay

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#127]
See screenshot below - above is a static image uploaded, second after that is a video uploaded.

They open correctly (Image opens, Video playes) but the preview style is identical.

Let's overlay a "play" triangle in a circle or some similar semi-transparent icon over video previews, so users understand that's a video. 

Or (better option) would be to show the length of the video in MM:SS in the bottom right of the preview image.

![Screenshot_2022-07-27-11-50-54-449_com.ethora.jpg](https://user-images.githubusercontent.com/328787/181230805-4d89b67c-0c6b-41b7-9d37-10ffc394ef20.jpg)

**Comment by dendidibe** [comment]
<img width="219" alt="Снимок экрана 2022-07-29 в 11 53 52" src="https://user-images.githubusercontent.com/54039544/181722809-407943ed-2d5a-49be-bb82-6a320bb241c2.png">
