### ISSUE TITLE
Blocklist - Users blocking other users

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#128]
A user can block another user, in this case if Alice blocks Bob, then Bob can still send messages in the chat but Alice will not be able to see the messages but Bob can see messages from Alice. Alice can also unblock Bob anytime.
Alice also cannot tag Bob in chat after blocking him. 

Unlike "ban" which is particular to chat room but can be done by Owners / Moderators only, "block" can be done by anyone and it's applied across all chats. 

Chat server:
need a plugin? or existing XEP?

UI:
add "Block this user" button in dark blue / violet background in the bottom of the Chat Message Menu.

**Comment by Akick** [comment]
I will create plugin for that

**Comment by phwizard** [comment]
waiting for backend implementation from @Akick

**Comment by phwizard** [comment]
Please place "Block this user" button above the "Ban this user" button.

**Comment by phwizard** [comment]
Done - thank you!
