### ISSUE TITLE
version (date-derived) at Login screen

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#13]
We still have an issue that often the version in the bottom of the Login screen doesn't get updated so it's not easy to tell which version of the code the app is running, whether it's the latest development build etc.

TO DO: Research the possibility of automatically displaying the date of the build / latest code change there.

FORMAT:
yy.mm.dd for all versions including development, test, hotfixes
yy.mm can also be used for stable monthly versions

alternatively add version number into Config file so it's easy to update it manually. 

We may also add DEV or QA into version number to reflect it runs from DEV or QA backend.

Example:
21.09.16-DEV means it's a version dated 16th September 2021 running from Dev backend.

**Comment by 4RGUS** [comment]
@phwizard , The changes have been made. Closing the issue.
