### ISSUE TITLE
Long tap room menu mockup

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#135]
Should include:

Room image and title

Sharing link and
QR code button

Number of participants

Notifications switch

Favourite status switch

Managent controls for chat owners (Edit name, Edit image, Delete room etc) 

Leave button

**Comment by Egatlov** [comment]
![02 Chat-Main-List – 3](https://user-images.githubusercontent.com/10884207/184314430-ec5c36e6-ca82-4572-87d4-a4ea4812c1e4.png)
![02 Chat-Main-List – 4](https://user-images.githubusercontent.com/10884207/184314439-ffa4ba9e-9acf-4a3e-9d28-e2965c8d34ee.png)
![02 Chat-Main-List – 5](https://user-images.githubusercontent.com/10884207/184314440-5d34dad0-9f4d-4c16-9633-d918f0cc936e.png)
![02 Chat-Main-List – 6](https://user-images.githubusercontent.com/10884207/184314443-b267d14d-1d86-4383-90dc-7d3aabcb6767.png)
![02 Chat-Main-List – 7](https://user-images.githubusercontent.com/10884207/184314452-fd1c84a0-044a-44f4-9e57-0e858d9886b9.png)

Hi @phwizard ,
Please find the attached designs and let me know the area of improvement.

**Comment by phwizard** [comment]
@Egatlov 
can you please work on some changes for the last screen (detailed chat view):

1. Menu will have the following options:

- Add to Favourites
- Delete and leave
- Edit settings

2. Title and description will have "Edit" icon next to each of them (this will be shown to Owners and Admins only)

3. Remove "group chat" and "Participants: 54".  Change "Mute notifications" simply to "Notifications".

4. Write the number after "Members" like this: "Members (54)"

5. Remove "Created on.."

6. Rename "Exit chat" to "Leave room"

7. "Pin" icon in the top nav bar can be toggled, right? Can we show it enabled? So user taps on it and it becomes yellow or somehow else highlighted? 

8. "Members (54") is a tab, selected by default (selection is shown as a line underscoring the tab name).
There will be another tab in case the room contains any Bots or Items.

9. show "Bots (3)" and "Items (10)" tabs next to Members for illustration purposes.

**Comment by Egatlov** [comment]
![02 Chat-Main-List – 6](https://user-images.githubusercontent.com/10884207/185176652-30f90735-281b-4f5d-a7c8-2dd60925d301.png)
![02 Chat-Main-List – 7](https://user-images.githubusercontent.com/10884207/185176661-0e7fa11e-6373-4968-8741-f33886420d67.png)

@phwizard 
Let me know if this looks fine or need any more modifications.

**Comment by phwizard** [comment]
@Egatlov this is great

only couple comments:
1. Pin icon - I didn't mean to make it yellow all the time, just meant to somehow show when it's on and when it's off. Can you have it white, same as other icons, but show a highlighted (on) state as well?
2. Please put "Delete and leave" to be the last menu item, also make it red colour  (and maybe worthwhile to have horizontal divider between each menu item so it's easier for users to tap them).

**Comment by Egatlov** [comment]
![Pinned](https://user-images.githubusercontent.com/10884207/185350836-10fececf-8d18-4655-8b68-ee8854280b49.png)
![Unpinned](https://user-images.githubusercontent.com/10884207/185350853-54c4fd28-b6c2-4e93-b572-b16c633d2f8b.png)

Hi @phwizard 

Please check this way of notifying pinned and unpinned chat and let me know if it works.

**Comment by phwizard** [comment]
Not really, this is close but looks quite custom and not ideal, perhaps we should leave it for @4RGUS to use some system UI control? We just want to show that there are two states, pinned and not pinned, for the chat. Another option is to use a star icon, in one case the star will be filled (pinned), another just outlined (not pinned).

**Comment by Egatlov** [comment]
Attaching two variations, one with star icon and one with pin icon.

![Pinned – star-filled](https://user-images.githubusercontent.com/10884207/185418040-bbf7f43f-b5f9-4abe-968d-2ef46d01fd20.png)
![Pinned](https://user-images.githubusercontent.com/10884207/185418059-3ea23d2a-a3ac-4930-a232-5bb9e45534ea.png)
![Unpinned – star](https://user-images.githubusercontent.com/10884207/185418069-77aa414d-da9c-415d-9837-f7b470275469.png)
![Unpinned](https://user-images.githubusercontent.com/10884207/185418077-4e889eb5-2294-4247-8cc7-9adf69b016c2.png)

**Comment by Egatlov** [comment]
![01-Pinned – star-filled](https://user-images.githubusercontent.com/10884207/185418529-018c1bf4-6f8a-42fc-8f9f-c6adbefc248c.png)
![02-Unpinned – star](https://user-images.githubusercontent.com/10884207/185418538-638a69ab-5c25-47f5-93cd-9ed19b96d82d.png)
![03-Pinned](https://user-images.githubusercontent.com/10884207/185418546-60eb3c33-552b-43c2-bbc0-65199b9f917a.png)
![04-Unpinned](https://user-images.githubusercontent.com/10884207/185418550-61c9824a-806a-42d4-9cb3-a9e4d452fe6c.png)

attaching two variations,
1 with star icon and another with pin icon where color is changed to highlight color to indicate pinned (active)

**Comment by phwizard** [comment]
@Egatlov I prefer the option with the star, looks more like fitting the overall style. 
Thank you, this is no over to @4RGUS to implement.
