### ISSUE TITLE
Attachments/Items view download options

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#138]
Users should be able to download media attachments they are looking at. 

Currently there is no option to download, like in the screenshot below there is no option to go further and download this image full size.

Let's implement it so that long tap on the maximized preview has a Download option.

![Screenshot_2022-08-16-14-26-24-614_com.ethora.jpg](https://user-images.githubusercontent.com/328787/184891484-c30669f2-d8d0-444d-8347-a0d4738f2494.jpg)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/185069451-c86b12d0-212f-4f29-bb28-84487a4b7cfe.mov

added file download button, it looks like that in most messengers, instead of long tap

**Comment by phwizard** [comment]
Done, thank you.
