### ISSUE TITLE
Chat history scroll down UI

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#140]
Currently users can reveal the previous / old chat history by pulling down the last (top) available part of the chat history. 

However it doesn't load immediately and it's not obvious for the user that something is loading.
Also last (the highest in the top) available chat bubble shows too close to the navigational header. 

We should probably show three dots or spinner / cloud icon, some UI element there showing that older chat history is being loaded?

Can you propose a UI / UX solution to notify the user that the history is being loaded?

**Comment by Egatlov** [comment]
Hi @phwizard 
I just noticed that we already have a spinner that animates when the user enters the chat after logging in to the app.
We can use the same spinner to show the chat history is loading when a user is pulling down the last (top) available part.
This animation should also create some space between the top navigational header and chat bubble.

**Comment by Egatlov** [comment]
> Hi @phwizard I just noticed that we already have a spinner that animates when the user enters the chat after logging in to the app. We can use the same spinner to show the chat history is loading when a user is pulling down the last (top) available part. This animation should also create some space between the top navigational header and chat bubble.

I noticed this spinner already implemented in Hablar app.

**Comment by phwizard** [comment]
Done - thank you
