### ISSUE TITLE
'Owned smart contracts' addition for balance route 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#141]
We need to extend the users balance API route so that we can return for each user the L2 smart contracts they are owners for.

This will allow us to display NFT Items in User Profiles (and also allow them to Display Item in chat rooms which is already implemented) in cases where user might not have any actual Items in their wallet, but they are still the owner / admin of the contract.

Proposed approach:
* Maintain a directory/cache of deployed L2 contract owners
* Implement a service/route allowing to return owned contract addresses for each User (each L2 ETH address)
* Extend the Balance route with the required information

**Comment by phwizard** [comment]
"зараз /v1/wallets/balance/:address повертає поля balance, extBalance які є масивами з інформацією про всі токени на L2 та L1, можемо добавити ще одне поле яке буде масивом з інформацією про всі контракти які задеплоїв конкретний :address"

**Comment by dzinzyura** [comment]
Done. Thanks, @transkarpation!
