### ISSUE TITLE
Allow sending X amount of Coin

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#142]
We need to allow users to send custom amounts of Coin to each other (and to bots). 

Current UI only allows to quickly send 1, 3, 5, 7 coins.

Proposed implementation:

1. Replace "7" with "X" meaning it will be an arbitrary number
2. if user taps "🟡 X", the dialog will change to:

======

Reward [User Name] with coins

[  _ _ _  ]  _- input field allowing to enter digits only_

[ Send ]

======

![IMG_20220816_212929.jpg](https://user-images.githubusercontent.com/328787/184979133-bbd557b4-4156-4f94-baf1-23125f829992.jpg)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/185078853-eec82e3b-00aa-43cd-acbc-94d904ae1a34.mov

**Comment by phwizard** [comment]
Great, thank you!
