### ISSUE TITLE
"Create a new room" item

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#146]
Under the list of chats in each tab let's have another cell which prompts users to create a new room.

Cell icon: plus sign "+"

Cell title: Create a new room
Cell description: Your own room, share with anyone you like

Cell colour: light green background

Once user taps on it, it will call the same screen as "New chat" currently in the menu

![IMG_20220817_105919.jpg](https://user-images.githubusercontent.com/328787/185091913-b0dc214c-e6f7-4f15-b255-90b602e46d29.jpg)

**Comment by Egatlov** [comment]
![Chat-list-create-room](https://user-images.githubusercontent.com/10884207/185179899-f929b81e-6524-4294-816b-63750731d1a5.png)
![Chat-list-floating-create-room](https://user-images.githubusercontent.com/10884207/185179906-67ae2063-7cf3-4bac-bc4c-3e50f7016061.png)

Hi @phwizard 
Please let me know your thoughts on both variations. The one you suggested looks more professional. Another way is to keep a floating button.

**Comment by Egatlov** [comment]
![Chat-list-create-room-2](https://user-images.githubusercontent.com/10884207/185180582-fbce07bf-b688-4213-adf0-2a51dcbf66b9.png)

**Comment by phwizard** [comment]
Love the idea with the floating / hovering button in the bottom, let's go ahead with that one!

Thank you.

**Comment by phwizard** [comment]
@4RGUS please implement this with this option:

<img width="329" alt="Screenshot 2022-08-17 at 16 51 18" src="https://user-images.githubusercontent.com/328787/185185210-8ef8935f-bd84-4720-9d5d-4c31bb52d13e.png">

so it floats in the bottom of the chats list screen, as per discussion above.

**Comment by phwizard** [comment]
@4RGUS actually no, let's go ahead with this option and show it right after other chat rooms, this is more intuitive for the users:

<img width="375" alt="Screenshot 2022-08-17 at 16 56 24" src="https://user-images.githubusercontent.com/328787/185186562-0cb04ed3-2ff9-40c0-a9b8-6dc0f877ff60.png">

**Comment by phwizard** [comment]
Final option. 

Also I guess just keep the font size same as for other cells (room titles), no need to make it bigger. 

<img width="382" alt="Screenshot 2022-08-17 at 16 57 24" src="https://user-images.githubusercontent.com/328787/185186796-e26440f5-1994-4fdf-8f17-0b59b6dc3b77.png">

**Comment by phwizard** [comment]
Done - thank you
