### ISSUE TITLE
Requesting users for First name and Last name - universal component

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#147]
Currently there are multiple scenarios where we don't receive user's first and last name via SSO, for example, in case with WalletConnect/MetaMask sign in, also in case with Apple sign in. 

We are handling them by requesting user name explicitly, but this is done in different places.

Let's unite this into one component/module so that some methods of sign in such as:
- WalletConnect
- Apple
- Any custom 3rd party / CRM / ERP integrations which don't supply a name

will all reuse the same component and display a same behaviour: upon / during sign in, user is asked for their First name and Last name, and after that can proceed.

**Comment by phwizard** [comment]
Done, need extra testing.

**Comment by dzinzyura** [comment]
Works great. Thank you, @dendidibe !

**Comment by bikash-code** [comment]
It is working great.
