### ISSUE TITLE
Threads UI

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#152]
Please visualize how threads could look in Ethora.

We are looking to create a UI to help users follow a particular conversation in a busy room.

So, users who are inside the thread view will only see messages related to that thread.

Users outside of the thread view will see the number of messages and maybe some small users (participants) avatars along as part of the thread - first / last message, but it will be a collapsed view, unless user decides to go into the thread. 

Standard back arrow button in the top nav bar will allow users to come back from thread into main chat view.

We also ideally should have an option to star and deep link into threads. For example, if I star a thread it will appear in my Starred tab, allowing to access it faster

**Comment by Egatlov** [comment]
![Thread UI – Expanded](https://user-images.githubusercontent.com/10884207/190131094-ec77aec7-41c6-454f-b13e-0ccdf9b38602.png)
![Thread UI](https://user-images.githubusercontent.com/10884207/190131103-4eae3b0d-7da4-41fc-be89-0e4ad545644d.png)

Design drafts first version.
