### ISSUE TITLE
Provenance - showing "0/x" when created 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#153]
Please fix this issue that is showing in Provenance when somebody has created an NFT collection (for example 5 copies), in the Provenance screen initially it's showing zero in the history. It should start with the creator having it full (for example, 5/5 instead of 0/5).

**Comment by dendidibe** [comment]
<img width="339" alt="Снимок экрана 2022-08-31 в 10 26 19" src="https://user-images.githubusercontent.com/54039544/187618665-cb57e760-f138-4859-a908-1686cca99639.png">

**Comment by dzinzyura** [comment]
Done. Thank you!
