### ISSUE TITLE
Provenance - NFMT details

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#154]
Currently in Provenance screen it doesn't show any record of creation of the collection for NFMTs. 

Normally it should show who has created the collection as the first record.

This is likely because the creator is a chat bot. 

Can we display the owner of the collection there assuming that the Create Bot has transferred ownership to the user who called it?

**Comment by dzinzyura** [comment]
Done

![image](https://user-images.githubusercontent.com/99117374/187949031-9773c003-f622-48cf-89d8-c28306030ee9.png)
