### ISSUE TITLE
Collections UI improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#160]
1. Add “Get” button for those collections that still have some unminted tokens. This will initiate an individual chat with a Merchant bot, sending to it the address of the collection contract so that User doesn’t have to type it.
2. Show tokens availability like this “128/130” so that the first (‘available’) number is shown in bold green. 
3. Add “Coin” icon before the price like this, you can also remove the word “Price”:  “ 🟡0 - 🟡20 “
4. When user taps on the cell (outside of image preview or "Get" button area), open a detailed Collection screen similar to Item screen where the Provenance can be seen (when Collection is created etc). 

<img width="785" alt="Screenshot 2022-09-02 at 12 27 41" src="https://user-images.githubusercontent.com/328787/188129871-7819b8de-dac3-4793-928f-ea5bedd5aafa.png">

**Comment by phwizard** [comment]
Please make sure it is aligned as a column

![IMG_20220902_144725.jpg](https://user-images.githubusercontent.com/328787/188160256-9be894c4-15b7-4d54-abfe-4501ca451ddb.jpg)

**Comment by phwizard** [comment]
And remove "Price"

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/188396268-9198734b-0a17-41ed-b6d3-c8a8d978e185.mov

**Comment by dzinzyura** [comment]
Done. Thanks!
