### ISSUE TITLE
Bug with sending minus Coins

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#161]
As discussed - I can send minus Coins via the "X 🟡“ UI.

This shouldn't be possible as ERC-20 smart contract doesn't allow to "take back" tokens from someone by transferring a negative value to them.

Minus transactions are not shown in transactions history but seem to be reflected in the balance.

Perhaps an API / caching issue?

Please investigate and resolve. 

![Screenshot_2022-09-02-12-30-39-417_com.ethora.jpg](https://user-images.githubusercontent.com/328787/188131113-545db8cb-2ffc-494c-aec4-7f9b676d5836.jpg)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/188382685-5e0d588d-81c3-470d-a862-eed5785b3745.mov

**Comment by dzinzyura** [comment]
Done. Thank you!
