### ISSUE TITLE
Items traits tags display

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#162]
1. Please display traits as tags as shown
2. Align them in the middle vertically, and closer to the right
3. If there are two or more tags, can we put them into two rows, but if one just keep it in the middle?
4. Show “unique!” tag for all 1/1 Items.
5. Show “rare” tag for all items which are /20 or less than 20. 

<img width="764" alt="Screenshot 2022-09-02 at 13 01 53" src="https://user-images.githubusercontent.com/328787/188138879-557c54a8-4289-4dca-b268-0b6d1a7c8ae7.png">

**Comment by phwizard** [comment]
Please make sure it is aligned as a column:

![IMG_20220902_144633.jpg](https://user-images.githubusercontent.com/328787/188160146-fb28d170-e067-4e2b-bafb-afc254189239.jpg)

**Comment by dendidibe** [comment]
<img width="336" alt="Снимок экрана 2022-09-06 в 09 53 30 (1)" src="https://user-images.githubusercontent.com/54039544/188829187-0c71b23c-ebef-4c0b-bdac-c4e7c13b4f11.png">

**Comment by phwizard** [comment]
Please reduce the right padding a little bit (by half)

**Comment by phwizard** [comment]
Done - thank you!
