### ISSUE TITLE
Long tap message menu - send Collections option (tab)

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#163]
Please add a tab here, so that default option will be Items and the 2nd tab is Collections.

If User chooses Collections tab, the interface is similar to what's currently there with Items, but listing the Collections where User is the owner.

Tapping on Collection should cause a pop up:
" Are you sure you want to transfer the whole Collection (smart contract rights) [ collection name ] to [ User Name ]?"

with Proceed and Cancel buttons.

Choosing "Proceed" will proceed with the transfer which will be shown similarly in the chat room, however "(Collection)" should also be added. For example:

Borys Bordunov -> FunkyCats (Collection) -> Misha Mohyliuk

**Comment by dendidibe** [comment]
<img width="336" alt="Снимок экрана 2022-09-07 в 11 26 01" src="https://user-images.githubusercontent.com/54039544/188829309-8bbb6ab6-159b-4632-a389-fc5eaede4ef9.png">

**Comment by phwizard** [comment]
Done.
