### ISSUE TITLE
Message Delete from One tap menu

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#166]
Choosing the Delete from One tap message menu should for a confirmation pop-up first:

Are you sure you want to delete this message?

Cancel Delete

And then, if User chooses Delete, proceed and delete this message for all participants.

Display 
_Message deleted.
_

In place of deleted message.

Delete should only display and work for cases when User has the rights to delete that message, i.e.:
1) It's Users own message
2) User is Owner, Admin or Moderator of the Room

**Comment by phwizard** [comment]
Waiting for RTC server implementation.

**Comment by phwizard** [comment]
@4RGUS over to you

**Comment by Akick** [comment]
<message from="olek@localhost" id="1635229272917013" to="test_olek@conference.localhost" type="groupchat">
    <body>Wow</body>
    <delete id="1635229272917013" />
</message>
And all users in room will receive next:

<message xmlns="jabber:client" xml:lang="en" to="olek@localhost/1216574346180782548712130" from="test_olek@conference.localhost/olek" type="groupchat" id="1635229272917013">
    <archived by="test_olek@conference.localhost" id="1635233863744841" xmlns="urn:xmpp:mam:tmp"/>
    <stanza-id by="test_olek@conference.localhost" id="1635233863744841" xmlns="urn:xmpp:sid:0"/>
    <delete id="1635229272917013"/>
    <body>Wow</body>
</message>

The message will be deleted from the archive and all users will get a "to delete" message.

**Comment by dzinzyura** [comment]
User can delete own messages.
Owner/Admin/Moderator can delete messages - in progress @Akick

**Comment by Akick** [comment]
Moderator also?

**Comment by dzinzyura** [comment]
yes, we planned it like this:

Delete should only display and work for cases when User has the rights to delete that message, i.e.:

It's Users own message
User is Owner, Admin or Moderator of the Room

**Comment by phwizard** [comment]
@4RGUS @dzinzyura does this work?

**Comment by phwizard** [comment]
Remains to update moderator's plugin for this.

**Comment by Akick** [comment]
@phwizard I will do that this week

**Comment by dzinzyura** [comment]
@4RGUS the plugin is ready from Oleksii's side. You can proceed by adding it to the client

**Comment by dzinzyura** [comment]
@4RGUS the updated mod_delete plugin is deployed on dev and prod servers. We can try to implement the feature and if it works

**Comment by dzinzyura** [comment]
Done. Works great. Thanks guys!
