### ISSUE TITLE
Solve room participants retrieval

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#168]
This should be resolved so that app shows correct users here.

![Screenshot_2022-09-05-22-29-13-119_com.ethora.jpg](https://user-images.githubusercontent.com/328787/188513964-af745bbd-1943-46d5-9a5e-e90629b19d8c.jpg)

**Comment by dzinzyura** [comment]
https://user-images.githubusercontent.com/99117374/189848534-3aae24c0-b482-4ec4-b57b-2a266ab2fd99.MOV

Done. Looks great! Thank you, @4RGUS @Akick!
