### ISSUE TITLE
Provenance - creation for Collections

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#169]
Collections should display who has created them and when in the Provenance section

![Screenshot_2022-09-05-23-30-39-870_com.ethora.jpg](https://user-images.githubusercontent.com/328787/188517806-e86237de-18d9-4ec3-b338-561c07dca26b.jpg)

**Comment by dendidibe** [comment]
<img width="336" alt="Снимок экрана 2022-09-06 в 11 52 14" src="https://user-images.githubusercontent.com/54039544/188591738-d5316b2b-1847-4bfd-a7ad-73d527fc9acf.png">

**Comment by phwizard** [comment]
done - thank you
