### ISSUE TITLE
Sending attachments & minting Items (NFTs) - show device gallery by default?

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#17]
Most users are attaching images. 
Also images from the gallery are most commonly used for the NFT Item minting. 

On Android, our file attachments feature first shows different folders/storages.

Can we show Gallery by default in both in-chat and mint cases?

At the same time, we should keep an option for the user to navigate somewhere else if they want to attach something outside of the Gallery, for example a PDF file.

**Comment by phwizard** [comment]
For Product Manager: decide 
A) add content type picker menu. 
B) default to Gallery (show images immediately)

**Comment by dendidibe** [comment]
Update: On Android devices it is working file, on IOS not working

**Comment by phwizard** [comment]
Filtering is implemented. 
Let's close this for now and then re-visit if needed.
