### ISSUE TITLE
Fix ownership transfer display 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#172]
Looks like we don't display it correctly when the ownership of the Collection gets transferred.

<img width="371" alt="Screenshot 2022-09-14 at 09 57 56" src="https://user-images.githubusercontent.com/328787/190109760-6543b67a-dd64-4cb8-b099-97295da4f712.png">

Can you please address this - suggestions:

* Don't display balances for contract ownership transfer
* Show a different arrow (for example, a thicker arrow, or double arrow, or red colour arrow) to make it easier distinguish a contract ownership transfer

**Comment by dendidibe** [comment]
<img width="341" alt="Снимок экрана 2022-09-15 в 20 21 51" src="https://user-images.githubusercontent.com/54039544/190470045-3fc016db-f477-4177-8370-bd702124a7cf.png">

**Comment by dzinzyura** [comment]
Done. Looks great. Thank you, @dendidibe !
