### ISSUE TITLE
Ethora app logo

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#174]
Current logo icon doesn't look great.

![IMG_20220917_224251.jpg](https://user-images.githubusercontent.com/328787/190877296-9e405abc-4ce2-45e4-a882-53dfe2ea20d4.jpg)

Let's have something more simple and stylish.

I suggest look into a stylized leter E

For example something like this where nodes are chat rooms that are connected by tunnels - lines in the letter

![IMG_20220917_224208.jpg](https://user-images.githubusercontent.com/328787/190877301-598caf61-0b29-4cef-b241-4706f4632500.jpg)

alternatively combine "e" with a chat bubble:

![IMG_20220917_225144.jpg](https://user-images.githubusercontent.com/328787/190877544-65b09879-6843-46ce-8bf5-73fd128664ae.jpg)

**Comment by phwizard** [comment]
Something like this would work too

![IMG_20220917_231541.jpg](https://user-images.githubusercontent.com/328787/190878083-9a84291e-67bd-411d-8cc2-31a7743c4f60.jpg)

We could literally take a vector space image of some Greek pillar and cut out a piece with that curly thing

**Comment by Egatlov** [comment]
![spiral-logo](https://user-images.githubusercontent.com/10884207/191006115-f756ed11-5d6f-4e59-ac7b-ad253c0ded98.png)

**Comment by Egatlov** [comment]
![1](https://user-images.githubusercontent.com/10884207/191182453-a443a11b-f8cd-4ce4-a717-5b64e706bd65.png)
![2](https://user-images.githubusercontent.com/10884207/191182460-704d0672-fb8b-4d4c-b209-06f612b7fa33.png)
![3](https://user-images.githubusercontent.com/10884207/191182465-2b00299f-80ca-4107-8a2f-4d95b8844aa1.png)
![4](https://user-images.githubusercontent.com/10884207/191182476-3e89e209-325a-4cd8-99c4-8aeef6699341.png)
![5](https://user-images.githubusercontent.com/10884207/191182479-42805374-9573-47bd-b911-f916d4171fec.png)
![6](https://user-images.githubusercontent.com/10884207/191182482-727580f9-9243-4da9-98e6-b251790a3014.png)
![7](https://user-images.githubusercontent.com/10884207/191182483-d7846a6f-442c-4bf8-8708-f27a6b23a7a3.png)
![8](https://user-images.githubusercontent.com/10884207/191182485-fa9cb4db-f86e-421d-b8c2-350068700edb.png)

Above attached are the icon variations for E resembling chat/messaging.
Each of them costs around 75Rs / ~1USD.

Let me know which one to finalize and I can go ahead with the procurement.

**Comment by phwizard** [comment]
Thank you!

I think the spiral direction has a lot of potential, but we'll need to spend a lot of time making it right. 

This one is great meanwhile - let's go ahead with this one please:

<img width="764" alt="Screenshot 2022-09-20 at 09 31 20" src="https://user-images.githubusercontent.com/328787/191208811-5d4d644a-afd2-47a9-b697-7c82df4b04cb.png">

**Comment by phwizard** [comment]
<img width="354" alt="Screenshot 2022-09-20 at 12 53 57" src="https://user-images.githubusercontent.com/328787/191251022-5539aaba-70de-431a-b8c7-e0b39ff24126.png">

@Egatlov thank you - could you try a transparent option or an option where it is white around inside the chat bubble, but is transparent outside?

**Comment by Egatlov** [comment]
@phwizard @4RGUS 

Attaching the compressed file which contains the new Ethora icon in different dimensions starting from 16x16 till 1024x1024 pixels.
[Ethora New Icon.zip](https://github.com/dappros/ethora/files/9615592/Ethora.New.Icon.zip)

**Comment by Egatlov** [comment]
#UPDATE

Use this zip
[Ethora-Icon-Boxed.zip](https://github.com/dappros/ethora/files/9615927/Ethora-Icon-Boxed.zip)
