### ISSUE TITLE
Data API - simple access management solution

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#175]
Entry creators can specify Owner field when creating a Data entry/object.

All Users have Read access.

Only Owners have Update and Delete access.

-----
(this is a v1 implementation. A preview of V2 implementation to be implemented in future phases): 
* data entries can have Tags assigned to them 
* separate endpoint for advanced ACL management
* access rights can be assigned to groups of entries (Tags)
* (optional) timed access
* can restrict Read access 
* multiple Admins/Managers can be assigned to objects/data entries

**Comment by transkarpation** [comment]
https://app-dev.dappros.com/api-docs/#/Data
