### ISSUE TITLE
New Web client - Framework & Login page

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#176]
**Framework**
Web Users should be able to gain access to the following important features:
- Own Profile (app.ethora.com/profile/<ETHaddress>)
- Own Balance (wallet) including Coins, Items and Collections
- Profiles of other Users
- Explorer (ideally this should be accessible without sign in) (app.ethora.com/explorer/)
- Web push notifications

All screens should be available under their own permanent URLs, for example use "app.ethora.com/item/<itemAddress" for Item details screen. 

QR codes to Users, Rooms and Files should lead to web implementations by default which include correct deep link manifests so that smartphone users have the links opened into correct sections in the app, to ensure correct cross-platform function.

**Login page (also Sign in and Sign up)** 

New Web client should allow Users to sign up or sign in to the platform in a same way that mobile users can:

* Social Sign On (SSO) via FB and Gmail
* Sign in with MetaMask / WalletConnect
* Log in with credentials

We should include an optional GET param ("app" or "appID") allowing to specify an Application ID for the login page. Otherwise, if not specified, all newly joining users should join under Ethora app by default.

**Comment by dzinzyura** [comment]
Everything's done, instead of push-notifications feature. Created separate task - https://github.com/dappros/ethora/issues/200
