### ISSUE TITLE
Documents route and contract type

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#178]
/ creating a task here to reflect the latest work on tokenizing documents / 

Currently we are using our Items (ERC-1155 contract) API for handling tokenized documents which is not ideal. 

Looks like we should create a separate API route for tokenized documents reflecting what's more relevant for business purposes.

**REQUIREMENTS**
API route: suggest to use /docs/ (better: shorter) or /documents/ similarly how we have /items/ API implemented.

Contract type: custom (I haven't found any suitable ERC for business documents) - keep similarity to standard ERC-20 or ERC-1155 best practices where it makes sense.

Mint params:
* Beneficiary: document minter can specify ETH address of the user/entity who will receive the document. 
* admin: ETH address of user/contract who can manage the parameters of this Document contract
* isBurnable - if this is FALSE, don't allow to burn/delete this token
* isTransferrable - if this is TRUE, means document can be transferred to other users. If not, then document can only stay with its beneficiary owner (so it's kind of "soul-bound"). This may be useful for example when it's a health test or an academic certificate which only belongs to a specific person or entity.
* isFilesMutableByAdmin - if this is TRUE, then contract admin can modify files records in the contract (update or delete them)
* isFilesMutableByOwner - if this is TRUE, then contract owner (user who has this document in their wallet) can modify files records in the contract (update or delete them)
* isSignable - if this is TRUE, other addresses can sign this Document via addSigner function
* isSignatureRevokable - if this is TRUE, other addresses can revoke their signature via revokeSigner function

Params / ABI endpoints:

* files[] - I propose to have an array that allows to specify files in the document. You can implement this just as a single param if this is simpler or makes more sense for you. However if we have an array here this will allow us to implement documents with multiple files. For example, a PDF legal contract + some binary data or video attachment to it. Or PNG image for book cover and PDF file for the book content. 
For each file, can we specify:
-> * fileName - filename
-> * fileType - file type (if relevant), for example PNG, JPG, PDF
-> * fileSize - file size
-> * fileHash - hash to verify the contents 
-> * URI (URL link to the specific file storage - such as IPFS, AWS S3 or secure ACL controlling files retrieval gateway)

* createdAt - timestamp when created
* updatedAt - timestamp when updated (if mutable)

* transferOwnership - standard - allows to transfer token ownership

SIGNERS
This will allow 3rd parties to sign this document. For example, a business contract signed, a bill of landing, a health test certificate etc.
* addSigner
* getSigners 
* revokeSigner (if removable)
- there is an array of signers[] with signerAddress, signedAt (timestamp), revokedAt (timestamp) and signedHash (optional, can be used for additional external validation of the signature). 

Business requirements / UI notes:
* Each document should have their unique ID (I assume this will be contract address once deployed). 
* Provenance - In the mobile and web apps UI we will be showing the document name, details, provenance (when created, by whom, when / by whom signed, when / to whom transferred etc). 
* Provenance for printed / physical documents - we should be able to print a QR code that will allow to retrieve the tokenized Document provenance via our Profile/Wallet UI or Explorer interface
* I would prefer to keep documents close to ERC-1155 standard just because there is a great support from ecosystem for NFT standard. This isn't a hard requirement however. 
* In our platform (DP API) Documents can be linked with additional custom business data / params / metadata by creating a record (or records) in our /Data/ objects and specifying Document Address as a way to link them. 
* ACL / Security - by default, Users can specify direct access to documents IPFS or other storage when minting. If, however, they don't want to have documents public, they should specify a link to our hidden Files API gateway (or alternative 3rd party solution). Such solution will be authenticating the user who is trying to retrieve the file and only return the file to those users who are in the ACL list for specific File/obect.

**API usage**

We should probably keep it same as with Items - client handles file upload as a separate step, and then calls Documents API which mints the smart contract. 

Documents API should return the code and the contract address if it's created successfully.

**Comment by transkarpation** [comment]
@phwizard if API accepts array of files[], should we have array of fileNames[], or should we use just one fileName which represent firts file from files[]? The same question for fileType, fileSize, fileHash, URI. Does we upload file directly to POST /docs route, or we firs upload file to POST /files endpoint. If we upload first to /files what should I use for files[] field?

**Comment by transkarpation** [comment]
does Mint params will be applied for all the files[]?
