### ISSUE TITLE
Dashboard / Web client - Users screen - Permissions UI

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#183]
Admin User path:

1. Log in as a User with Admin access to Users within specific Application (you should have 'appUsers "A" / owner permission, or "R" permission simply to see this as 'read-only')	
2. Open Users screen	
3. Click any specific User, e.g. "John Doe"	
4. Choose "Permissions" tab	

<img width="888" alt="Screenshot 2022-10-07 at 10 02 00" src="https://user-images.githubusercontent.com/328787/194516023-ddb94286-c81d-44ea-b79e-5848120aebe1.png">

Notes: 
* this is in relation to Network and Applications
* in relation to individual Users and Files we probably don’t need web UI for that, it all will be handled via API and frontend UI for the end users

Descriptions for hovering info pop-ups for permissions:
<google-sheets-html-origin><style type="text/css"></style>

User (wallet) -level ACL / permission settings for Network |   |   |   |  
-- | -- | -- | -- | --
netStats | 0 | 0 | RA | Network stats & network health screen. Read allows Users to view Network stats. Admin allows to give max privileges for this interface to other Users.
N/A |   | N/A | N/A | Explorer - there is no ACL setting for explorer, as everybody who has access to the network should be able to access its explorer for "Read" and there is no "Update" . In the Explorer UI however there should be a way to filter all transactions by Application (via GET param and/or UI filter), if possible.
  |   |   |   |  
User (wallet) -level ACL / permission settings for Apps |   |   |   |  
appCreate | 0 | 0 | C | All Ethora / directly registered DP Platform Users can create new Applications (currently this is free, in future it will be paid with Coin (DP utility token). Once user has created Application, they obtain full Owner access to their Application (RUDA). So they can Read, Update, Delete and also Admin (manage rights to other Users). For Users created within the context of other Applications, they can restrict their right to "appCreate" which means they won't be able to create Applications. This may be useful for many business use cases where we don't want to confuse the end users with this feature.
appSettings | 0 | 0 | RUA | Application settings. Read allows User to access application settings screen and read it. Update allows to also update the settings. Admin allows to give max privileges for this interface to other Users.
appUsers | 0 | 0 | RUA | Users screen. Read allows User to view all Users of the Application and their details.  Update allows to update Users profile details. Delete allows to delete Users. Note: there might be situations when End User has removed the rights for the Application to update or delete their account. In such case another User will not be able to update or delete their account even if they have such privileges from their Application owner/admin. Admin allows to give max privileges for this interface to other Users.
appTokens | 0 | 0 | RUA | [ Note: we can put this screen on hold for now. ] Tokens screen. Read allows User to view all ERC-20 and NFT tokens created within the Application context. Write allows to create / mint new tokens via web interface. Admin allows to give max privileges for this interface to other Users.
appPush | 0 | 0 |   | Access to Push Notifications interaface used for manual/marketing push. R allows to read what Push Notifications have been sent. U allows to send marketing / manual push notifications.
appStats | 0 | 0 | RA | Stats scren. Read allows Users to view Application specific stats. Admin allows to give max privileges for this interface to other Users.

**Comment by dzinzyura** [comment]
done - thanks, Misha!

**Comment by dzinzyura** [comment]
needs to be tested through Swagger API
@bikash-code

**Comment by dzinzyura** [comment]
Tested. @transkarpation please, have a look into [Bikash's report ](https://dappros.atlassian.net/browse/ETO-113?focusedCommentId=13203&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13203)
