### ISSUE TITLE
Ban & Block minor changes

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#184]
Please make the following changes:

- "Ban this user" = "Ban (this room)"
- "Blocklist this user" = "Block (your contacts)" 
- Make both buttons darker red background (try #460000)
- In the buttons make icons and text vertically aligned along the same line 

<img width="369" alt="Screenshot 2022-10-07 at 10 10 58" src="https://user-images.githubusercontent.com/328787/194517979-410ce3ea-75f9-48fd-8006-d7dc69500703.png">

**Comment by dendidibe** [comment]
<img width="338" alt="Снимок экрана 2022-10-07 в 12 56 36" src="https://user-images.githubusercontent.com/54039544/194527451-c645d0e8-0344-4c5a-8cd5-6d787adc2cb8.png">

**Comment by dzinzyura** [comment]
@dendidibe 

**TO BE DONE** 

1. Change colors of buttons "Ban" & "Block" as on the Taras' mock-up (attached image in the task itself)
2. Add additional explanations for the buttons (attaching mock-up below)

"Ban this user" button is only accessible for chat Admins/Moderators
"Blocklist this user" button is accessible for all users

Text (can be changed if it's doesn't fit)
"The ban feature allows you to kick a user out of the chat without the possibility of returning to it before unbanning."
"The blocklist is a global feature that allows you not to receive any messages from a blocklisted user before unblocking."

![Ban   Blocklist mock-up](https://user-images.githubusercontent.com/99117374/196202289-6aa529c9-3e08-4a0d-850b-db4e41569d0f.png)

**Comment by dendidibe** [comment]
<img width="324" alt="Снимок экрана 2022-10-18 в 11 31 33" src="https://user-images.githubusercontent.com/54039544/196379015-e4227132-177b-40df-9548-df3d03657932.png">

**Comment by dzinzyura** [comment]
@dendidibe thank you, looks great! 
but can you, please, make some minor changes: 
1. To center the text on buttons (as we have on my or Taras' picture above)
2. To edit a text: "The **blocklist** is a global feature"

**Comment by dendidibe** [comment]
<img width="324" alt="Снимок экрана 2022-10-18 в 11 51 04" src="https://user-images.githubusercontent.com/54039544/196383691-64ff6566-27e2-4d09-b9f9-e00f5363da48.png">

**Comment by dzinzyura** [comment]
awesome! thank you!

**Comment by phwizard** [comment]
@dendidibe 
Nearly there! Please change the text for Ban:
Kick user from this room

text for Block: 
Hide content from this user 

Make both texts dark grey. (something like #5A5A5A)

**Comment by dzinzyura** [comment]
Thanks, @dendidibe ! looks great!
![image](https://user-images.githubusercontent.com/99117374/197479126-c1480f13-73eb-487c-84cd-42a43272b5dc.png)

@phwizard is it OK for now? can I close the task?

**Comment by phwizard** [comment]
This is great, thank you!
