### ISSUE TITLE
concept for roomContract, presence and travel functions

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#187]
This implements three important aspects finalizing equipping Ethora with decentralized metaverse building and traveling mechanics:

* Rooms (Spaces) can be created and managed by Users and entities in a decentralized way.
* Users can travel between rooms. Users can be properly “Present” only in on Room at a time.
* Rooms can connect to each other so that Users can easily travel to neighbouring rooms. These connections are managed in a decentralized way.

**Contract attributes**:
* contractOwners - contract owner ETH address
* contractAdmins - contract admins ETH addresses
* roomCreateFee - how many Coins required to create a Room
* linkFee - how many Coins required to update a link in a Room where you’re Owner or Admin

**Room attributes**:
* address - a unique address (such as ETH public key or similar) to uniquely identify the room. Note: it will be beneficial if the room can have its own ETH wallet, or its wallet can be managed by the main roomContract. 
* owners - (at least one) - ETH addresses who can manage all Room attributes including changing the Owners. They can also withdraw funds and assets from their Rooms.
* admins - (optional) - ETH addresses assigned by an Owner who can manage all Room attributes except changing the Owners or Admins and except withdrawing any funds or assets from the Room
* image - (static) - IPFS image for the room 
* background - (static) - IPFS image for room background
* stream - link for audio or video stream for the room background
* links - connections to neighbouring rooms (see below)

**BALANCE (Coins)**
Rooms may be able to receive or earn funds in Ethora Coin and ETH. 
We should implement methods allowing to (1) transfer Ethora Coins and ETH to the room contract specifying a specific Room; (2) for Room Owners to withdraw such funds.

**BALANCE (Items)**
We also want to have methods allowing to store and withdraw other types of tokens / Items inside the Rooms, such as NFT Items. 

Initially it is proposed simply to implement a way for any User who is present in the Room to drop an Item there and for any other User who is present in the room to collect any Item. In future this may be extended with advanced mechanics.

**PRESENCE**
This is a User related attribute, not a Room attribute. 
For each User our contract and our caching layer track where they currently are. 

This is for:
* Remembering where user has left the system in case the client app cache is reset 
* Various metaverse, gamification and business logic mechanics. For example, users located in certain room can enjoy certain benefits, Items drops, access to certain features or information. Bots and room can interact with Users who are present in a specific location.

proposed data structure:
key: roomAddress
value: userAddress

**functions needed** 
(these functions are to be implemented both in the smart contract and in the API layer):

PHASE 1: 
* addRoom(roomAddress, [owner addresses], [admin addresses]) - creates a new "meta" room (or adds an existing XMPP room into "meta" rooms) - I assume that User first creates an XMPP room and gets its address and then sends the roomAddress here, but if easier we can have this function create the XMPP room from the backend, in this case we don't need roomAddress from the User. 
* getRoom(roomAddress) - if the room is registered in roomContract, this returns the room attributes, most importantly during Phase 1 this should return all links to other rooms (direction code + roomToAddress for each direction)
* setLink([roomFromAddress], linkDirection, e.g. "N", roomToAddress]) - sets link direction ("N") from roomFromAddress to lead users to roomToAddress. Important logic: if the opposite direction is free in the roomToAddress, then this function should also automatically set the mutual link in that room. For example, if I call setLink(room1, "E", room2) then function should check if "W" (opposite) direction is free in room2. If "W" is free in room2, our function should automatically set "W" in room2 to link to room1. If, however, "W" is already occupied in room2, then we only set the outgoing link from room1. 
* getPresenceByUser(userAddress) - returns address of the room where the User is currently in

PHASE 2: (to be updated)
* getRoomUsers(roomAddress) - gets a list of users present in the room 

**TRAVEL**
travel(userAddress, destinationRoomAddress)

This function should be called by a User (a client app on behalf of the User) and allows the User to change their Presence to another Room.

**Travel messages**
If successful, the act of travel should also emit a message for the Room that User has left and for the Room that User has joined

These messages are communicated via VM ‘emit’ by the smart contract and/or messaging protocol (XMPP) messages by the client app.

E.g. (as seen by other users):

User leaving room:
< user name > has left -> 
the arrow here symbolizes the direction where User has gone. This allows other users to follow in case our User has travelled into a neighbouring (linked) Room. In case User has left via a portal (QR code) there will be no direction or link in the message to preserve confidentiality of any invite-only Rooms.

User entering room:
< user name > has entered.

Client implementation notes:
* Underscore the user name and allow to tap on it as a link opening the joined / left User’s profile.
* In case many users have left or joined the room simultaneously (within 15 seconds), group them to avoid overloading the chat. For example, "< user name 1>, < user name 2 >, <user name 3> and 45 other users have entered". 

**LINKS (and “compass navigation")**
Links are essential for the crowd-sourced Metaverse building. Rooms are building blocks and Links connect them together. 

Room owners / admins can set a limited number of links to other Rooms. 

In the client application, Users can easily navigate to ‘nearby’ Rooms (for example, go West via swipe right action, go East via swipe left etc).

Links structure for current phase (stored as a mutable attribute for each room):
* linkW
* linkE
* linkN
* linkS

Links data structure:
fromRoomAddress, linkType [‘W’, ‘E’, ’N’, ’S’]), toRoomAddress

E.g. array stored inside smart contract for connecting room1 to other rooms. 

In future phases we may add Up / Down etc links. 

**Updating links** 

Owners / admins can update Links for which they need to pay a Coin fee. 
In case Link is empty, the Client app will lead to a default room in the navigation there. 

Owner/admin of the originRoom should execute the following function along with sending a correct Fee in Coin:
setLink(fromRoomAddress, linkType [‘W’, ‘E’, ’N’, ’S’]), toRoomAddress)

Note: 
* Rooms can link differently. This means if a User travels ‘East’ and then travels ‘West’ immediately, there is no guarantee they end up in the same room. This is fine. We may establish a mutually binding linking mechanism in future updates. Note that initially setLink will set mutual directions, but room owners will have option to change the links in future. 
* Client app should retain the “Back” navigation allowing User to come back to the previous Room visited without using the “compass” navigation
* In case a room doesn’t have some link created yet, the client will still allow them to "travel" into that direction and will show it's an empty space, allowing the User to create a new Room there.

**Comment by phwizard** [comment]
_> Contract attributes:
contractOwners - contract owner ETH address
contractAdmins - contract admins ETH addresses
roomCreateFee - how many Coins required to create a Room
linkFee - how many Coins required to update a link in a Room where you’re Owner or Admin
**Q1 - ці поля відносяться до загального контракту (General Room Contract), який задаватиме правила для створення інтстасів контракту-кімната (Room Contract Instance) ?**_

-

A1: Yes, these are contract level. These aren't likely to change often. You can have them as constants in Phase 1 implementation. 

-

**_Q2 - якщо Q1 = так, то при створенні нового лінку на інcтансі Room Contract Instance ми повинні зробити запит на контакт General Room Contract Instance, щоб отримати ціну для створення linkFee ? (а також для деплою кімнати roomCreateFee ) ?_**

A2: Yes, however we can keep these values as constants and have them stored somewhere at API layer cache or even hard coded at the client side for Phase1. 

**_Q3: PRESENCE
This is a User related attribute, not a Room attribute.
Q3 Пропоную зробити PRESENCE в інстансі кімнати, так буде зручніше отримувати всіх юзерів з кімнати getRoomUsers(roomAddress)._** 

A3: Main purpose we need this for is that we have a source of truth of the "meta presence" of the User. User cannot be "meta present" in multiple rooms at the time, there should always be one room when user is in "Nav" or "meta" mode. 
So this presence (last meta room visited) will be cached on the client side, but also there should be a function to check User's presence from the backend that client will use to verify. 

I propose to implement it via function like this:

getPresenceByUser(userAddress) - returns address of the room where the User is currently in

We could of course implement a function getRoomUsers(roomAddress) or checkPresence(roomAddress, userAddress), however what happens if our User is not there? For example, User has old last location cached on the mobile device. At the same time, User has recently used another mobile device, a web client or even directly a smart contract to travel to a different location. In such case the old client won't be able to verify the last location presence. How do we retrieve the current location of a User from our rooms smart contract?

**Comment by phwizard** [comment]
**_Travel messages
If successful, the act of travel should also emit a message for the Room that User has left and for the Room that User has joined
These messages are communicated via VM ‘emit’ by the smart contract and/or messaging protocol (XMPP) messages by the client app.
Q5 кімната-контракт генерює event на події вхід/вихід. для того щоб xmpp або клієнтський додаток міг отримувати ці івенти йому треба мати доступ до блокчейну. Якщо івенти оброблятиме мобільний додаток потрібно робити блокчейн публічний,  відкривати порти для підключення з любої адреси? якщо івенти оброблятиме xmpp - потрібна реалізаці від Олексія, і доступ до блокчейну для його сервера._**

A5:
Currently we already have implementation where client sends these messages via XMPP. I think we can keep it this way, no need to do ‘emit’ messages on the blockchain side now, but we will come back to this if needed.

**Comment by phwizard** [comment]
**_Q: ok, but how we implement it from ui, now I saw there is a free link on UI, anyone can tap on it, and there is button Create room, if only owner can update room link, there should be step for requesting such operation. User1 whant to update W link on your room. Need to know for backend side too )_**

A: When you create a room in a free space, anybody can create it.
Also if original room had a free link in that direction, anybody can update that link by creating a room in that direction.
However, owner/admin of original room can always change that link in their own room in future, to connect it to a different room if they want.

**Comment by dzinzyura** [comment]
Done. Thank you @transkarpation
