### ISSUE TITLE
UI: Privacy & Data section: Visibility

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#188]
<img width="791" alt="Screenshot 2022-10-12 at 11 12 22" src="https://user-images.githubusercontent.com/328787/195316087-652e376e-46ab-4a84-8b33-dd3b85a45697.png">

**Comment by dendidibe** [comment]
<img width="326" alt="Снимок экрана 2022-10-17 в 09 40 39" src="https://user-images.githubusercontent.com/54039544/196106752-e734a88a-c16a-457b-892d-96cb91f82826.png">
