### ISSUE TITLE
UI: Privacy & Data: Profile Shares: Manage & Add

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#189]
<img width="757" alt="Screenshot 2022-10-12 at 11 14 01" src="https://user-images.githubusercontent.com/328787/195316430-cee50dea-9d12-47e8-b039-4fa5d48fbc41.png">

<img width="779" alt="Screenshot 2022-10-12 at 11 14 45" src="https://user-images.githubusercontent.com/328787/195316583-5c177775-ca19-4eb1-8f87-f8b4735bc58c.png">

**Comment by dendidibe** [comment]
<img width="326" alt="Снимок экрана 2022-10-17 в 09 40 57" src="https://user-images.githubuserc
<img width="326" alt="Снимок экрана 2022-10-17 в 09 41 06" src="https://user-images.githubusercontent.com/54039544/196106630-51b22591-9ee9-4cba-8da6-3a81d082ea04.png">
ontent.com/54039544/196106602-115d8a93-67bd-4e14-9a4f-3b417c5141dc.png">

**Comment by dendidibe** [comment]
<img width="326" alt="Снимок экрана 2022-10-17 в 09 41 06" src="https://user-images.githubusercontent.com/54039544/196106707-15748c10-e881-40b1-9d28-ab61b0bd43f0.png">
<img width="326" alt="Снимок экрана 2022-10-17 в 09 40 57" src="https://user-images.githubusercontent.com/54039544/196106711-d2814f84-4d5d-480b-ad48-6df50c55c62d.png">

**Comment by phwizard** [comment]
@dendidibe please convert timestamp to human readable format

**Comment by dzinzyura** [comment]
Looks great. Thanks, Misha!
