### ISSUE TITLE
RN - Assets display change

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#198]
Currently this is as shown in the screenshots below.

"Coins" tab takes space, but it's not needed really.
Also, in many cases, for many apps, Users only hold 1 type of assets (except Coin) which is either Items or Documents.

Can we make it so:

1. Remove Coins tab from Assets.
2. In case User only has 1 type of Assets, we don't display sub-tabs (such as Coins, Items, Documents) under Assets tab. Display assets straight away. So for example User has 4 Items like in this tab, User has some Coin and doesn't have any Documents. When Assets tab is selected, display the Items table straight way, don't show "Items" or any other sub-tabs.
3. Only show sub-tabs if user has more than one types of Assets (excluding Coins).

![Screenshot_2022-10-18-11-48-38-899_com.ethora.jpg](https://user-images.githubusercontent.com/328787/196411014-c29e79a1-ce69-46a9-be80-70e91dbb2a19.jpg)

![Screenshot_2022-10-18-11-48-53-414_com.ethora.jpg](https://user-images.githubusercontent.com/328787/196411034-e6d6935a-238c-4eb8-b8b0-6cf7652132c3.jpg)

**Comment by dendidibe** [comment]
Note: if user has no items minted, in that case the only thing we can show is coins

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/196420039-506c002c-fe03-40b1-bc4d-eb48756ffe02.mp4

**Comment by dzinzyura** [comment]
great stuff, Misha! thank you!
