### ISSUE TITLE
Experimental build with new rooms navigation

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#199]
(product experiment build)

have 3 chat rooms hard-coded for this experiment (you can choose any rooms - doesn’t matter)

1  -  2  -  3

when user swipes left, you move the user to the previous room (from 3 to 2, from 2 to 1)

when user swipes right, you move the user to the next room (from 1 to 2, from 2 to 3)

when user enters the room, write a technical message into room:

< user name > has joined

< user name > has left ->

When you write ‘has left’ , change the arrow next to it depending on which way user has swiped / moved, so if user moved from 2 to 3 then it will be “->“, but moving from 3 to 2 will be “<-”

you can use any rooms for this experiment, existing or new ones

**Comment by dendidibe** [comment]
@phwizard on ios and maybe some androids, swipe left is a system function which work in any app and is using for going back

**Comment by phwizard** [comment]
thank you!
