### ISSUE TITLE
Assets - Documents - screens (inside Profile and Document details)

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#202]
Documents asset type display - in the Profile (Assets) tab and Document details screens.

Similar to same screens for Items with some differences.

<img width="895" alt="Screenshot 2022-10-24 at 13 13 45" src="https://user-images.githubusercontent.com/328787/197522992-c681cd5f-155c-44e6-8fbe-d96eea1bc7f6.png">

**Comment by dendidibe** [comment]
<img width="328" alt="Снимок экрана 2022-10-25 в 15 16 55" src="https://user-images.githubusercontent.com/54039544/197770679-91d95bac-4a5a-4c10-b213-cce088eb6128.png">
