### ISSUE TITLE
Experimental build - new header UI 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#203]
Main idea here is to get rid of unnecessary UI with tabs, at the same time make Favourite and 1:1 (Private) chats available from anywhere. 

- Menu moved to the left
- Balance box moved to the right
- Star icon introduced - this works same as "Official" tab before
- Dialog icon introduced - this works same as "Private" tab before
- Compass/Navigation icon introduced - this will be described in a separate issue

Note: badge counters for new messages should work for Star and Dialog icons.

<img width="875" alt="Screenshot 2022-10-25 at 01 20 07" src="https://user-images.githubusercontent.com/328787/197654032-75748075-f824-4d0f-8062-fd151cfea088.png">

**Comment by dendidibe** [comment]
![image](https://user-images.githubusercontent.com/54039544/199182930-31defd9d-39d2-476e-8158-8a0d6f91b9ee.png)
