### ISSUE TITLE
Transactions - System sender name

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#205]
I propose that we have a system sender name because we might have multiple system users / wallets / contracts issuing payments to users such as activity bonus and join bonus etc.

So we might have to put their addresses in the config file and just use a hardcoded name for them.

Long story short, let's replace "Ethora Ethora" simply with "Ethora" here

**Comment by dendidibe** [comment]
<img width="334" alt="Снимок экрана 2022-11-01 в 13 32 07" src="https://user-images.githubusercontent.com/54039544/199223665-68df882e-c216-4555-9e99-8c99f2615017.png">
