### ISSUE TITLE
Star / Favourite mechanism

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#209]
Please implement this mechanism as following:

When "Star" is toggled in Chat Details screen, this room/space should be displayed in "Starred" (previously known as "Official") tab.
Similarly, when user "untoggles" the Star icon, then room / space should be removed from that tab, and will be displayed simply in Groups tab.

Note: for Default chats which as specified as default in the Config, Users cannot 'untoggle' them so they will always be Starred in the chat details screen and will always display in the starred tab.

<img width="952" alt="Screenshot 2022-11-03 at 11 33 31" src="https://user-images.githubusercontent.com/328787/199710517-deb66362-49e8-4f62-a761-9e60f71a9018.png">

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/199761124-7e453c4c-300e-4bc8-bbc3-870c5ff9d374.mov

**Comment by phwizard** [comment]
Brilliant, thank you!
