### ISSUE TITLE
Individual Documents sharing - FE implementation 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#212]
Let's finalize this screen as we have backend etc working already.

Individual Documents sharing will be very similar to Profile Shares. 

Only difference:

before Expiration section, add a Document section:

**Document**
Choose the Document you would like to share.

[ Choose Document  V ] _- this is a dropdown that shows all Documents that User has in their profile/wallet and allows to choose one of them._ 

![IMG_20221107_110127.jpg](https://user-images.githubusercontent.com/328787/200294692-dd2e7796-eaf4-4c26-a6fb-cf902c1b321b.jpg)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/201035519-307a6607-1781-43b3-a9d7-19610b8f856e.mov

**Comment by dzinzyura** [comment]
awesome! great job, thank you!
