### ISSUE TITLE
Web - Profile and Documents view improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#213]
Current view below.

Please make the following improvements:

* Hide column names for Items and Documents
* For Documents make its display similar to Mobile view in the example below: (1) Show preview; (2) Show Document Name; (3) Show Date; (4) Show QR code. 
* QR code from documents will be opening the unique sharing link for specific document. If this is difficult to implement now, we can move this to another feature or have this QR button link to Privacy & Data -> Document shares section and User will manage it there. This should be the same for mobile app.
* For Items please also hide header columns and display it similarly as in mobile version: (1) Preview image; (2) Name; (3) Any coloured tags/traits; (4) Rarity in "X/Y" format where X is number of items user owns and Y is total number of such Items.
* Tapping on Document or Item should open Document or Item details screen, similar to mobile app, showing details in the header and Provenance transactions history in the bottom

CURRENT WEB VIEW

<img width="1116" alt="Screenshot 2022-11-09 at 09 32 57" src="https://user-images.githubusercontent.com/328787/200793646-8f508d94-4ee8-4f3a-a748-385ed959b2d1.png">

MOBILE VIEW (EXAMPLE)

<img width="536" alt="Screenshot 2022-11-09 at 09 35 08" src="https://user-images.githubusercontent.com/328787/200794202-0d895910-f3de-4120-ba2b-4ac422101aeb.png">

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2022-11-10 в 10 04 27" src="https://user-images.githubusercontent.com/54039544/201034974-5cc898b5-1e8c-4ca1-9818-dd5c0a2e11ec.png">
<img width="1440" alt="Снимок экрана 2022-11-10 в 10 04 55" src="https://user-images.githubusercontent.com/54039544/201035026-f00335f4-e7c0-4e6d-9ce0-1696738102e3.png">

**Comment by dzinzyura** [comment]
Thank you, @dendidibe ! looks great!
