### ISSUE TITLE
Web - menu change (+ Mobile menu update)

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#215]
Let's change the menu in Web version menu (current screenshot below) so it's similar to latest Mobile version. 

See changes bullet points below.

<img width="965" alt="Screenshot 2022-11-16 at 11 19 06" src="https://user-images.githubusercontent.com/328787/202167021-4cd6073e-74a8-4420-bf54-abaea241e384.png">

CHANGES REQUIRED:
* Move menu to the left, burger icon same as in latest mobile
* Update menu items according to how it's described below

MOBILE MENU UPDATE:

-

**ACCOUNT**
My profile
E-mails (previously "Account")
Transactions
Referrals (previously "Enter code") 

-

**ACTIONS**
New room (previously "New chat")
QR scan (previously "Scan")
Mint NFT (previously "Mint items")
Upload Document

-

**ID** (previously "SYSTEM")
Sign out (previously "Logout") 
(alternatively show "Sign out" option / button without any section header at all, simply under divider line as a single menu item) 

WEB MENU UPDATE:
Same as mobile, however you can also add "Chats" in the top as we don't have tabs UI for chat rooms in web yet. 

Also no need to add those menu items which are not implemented yet - they can be added as required.

ADMIN FEATURES:
In web currently, and later in Mobile, if user gets access to admin features via ACL, please add another section called "**ADMIN**" which should show above "Sign out" section and it should hide if User doesn't have access to any Admin features.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/202674076-d90ccee1-aebd-4f09-a315-e7e9102af8b5.mov

**Comment by dzinzyura** [comment]
Thanks, @dendidibe! Looks great!

To be done in web-client

**Comment by dzinzyura** [comment]
Changes on the web-client. Thanks, @dendidibe! Looks great

![image](https://user-images.githubusercontent.com/99117374/203313347-b1844198-9aea-4deb-b2e8-52bbfef3c9c5.png)
