### ISSUE TITLE
Chat / XMPP glitches from the past

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#217]
When testing today I have noticed some chat issues which resurfaced from the past

1) In a new chat first message didn't come through. I tried to reproduce that for a video recording but couldn't, it only happened once.

2) Double message send

3) No message coming through

Both above issues I captured on video below

https://user-images.githubusercontent.com/328787/202353481-f7b1473a-309f-4b61-9a48-52b5bcd5bd4b.mp4

Let's find and eliminate the root cause

P.S. note that the messages not appearing have actually appeared after I tapped back into list of chats and opened the room again:

![Screenshot_2022-11-17-04-18-41-977_com.ethora.jpg](https://user-images.githubusercontent.com/328787/202354518-7da96780-c7f0-4a66-9143-b4638ec67e70.jpg)

Note the double send also happened there

**Comment by dzinzyura** [comment]
Thanks, @4RGUS! 

[Build with changes](https://dappros.slack.com/archives/C025G04FQV6/p1669270465290169)
