### ISSUE TITLE
Items layout issue

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#218]
Note the issues here, especially last Item almost hidden below screen.

https://user-images.githubusercontent.com/328787/202356323-51e574ff-4f01-4038-9aac-9b53336fdfed.mp4

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/202674327-60171901-3cc6-4753-881a-8027e80b2c1b.mov

added padding, removed blue line

**Comment by phwizard** [comment]
Thank you. Didn't ask for padding but let's see how this works out
