### ISSUE TITLE
Reflect rooms where I'm owner or admin

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#221]
Can we somehow reflect the chats where I'm owner or admin? 
Do we have that information when we receive a list of chats or do we only get when we're in the room?

If we can do that, let's try simply this:

highlight the chats where I'm owner or admin with a light yellow background.

**Comment by dzinzyura** [comment]
@phwizard, Vineeth implemented this in such way, Please, let us know if it works

![image](https://user-images.githubusercontent.com/99117374/203312370-9fd5b880-fbf6-4f9d-ade2-977006f0792c.png)
![image](https://user-images.githubusercontent.com/99117374/203312389-2511fd05-23dc-45cd-a277-42a184737a29.png)
![image](https://user-images.githubusercontent.com/99117374/203312403-ff1eea28-de60-47ad-9368-1f43dca588b7.png)

**Comment by phwizard** [comment]
@4RGUS sorry no I wasn't clear probably. 
I meant to highlight such Rooms (chats) in the list of chats. Either with some icon or different background of the cell. So that users know which rooms they are responsible for managing.

cc: @dzinzyura
