### ISSUE TITLE
Room name limit increase 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#224]
Room name seems to be 20 symbols. 

Let's increase to 50.

![Screenshot_2022-11-21-22-20-49-854_com.ethora.jpg](https://user-images.githubusercontent.com/328787/203170104-188056fc-73be-4704-bccf-6d43a5dc4849.jpg)

**Comment by dzinzyura** [comment]
Thanks, @dendidibe !

[New build with changes](https://dappros.slack.com/archives/C025G04FQV6/p1669105522897609 )
