### ISSUE TITLE
Web - login screen improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#227]
Please make the login screen closer to the mobile version.

Facebook first, then Gmail, then Metamask.

Mostly lower case letters and "Sign in.." same as in mobile version.

Please hide extra options such as sign in with email, sign in with username, owner login / registration under some tab or other UI which only opens if user wants to open them. Should only be 3 main SSO choices initially.

![Screenshot_2022-11-22-00-48-20-147_com.android.chrome.jpg](https://user-images.githubusercontent.com/328787/203188217-d222b6d4-1e75-4957-b432-0a0190c543ec.jpg)

![Screenshot_2022-11-22-00-49-56-445_com.ethora.jpg](https://user-images.githubusercontent.com/328787/203188229-50ea8fc8-06a6-4ccb-97bc-ad946cf26256.jpg)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/203268172-98940042-9800-4729-9815-668666be60e1.mov

**Comment by phwizard** [comment]
Perfect! Thank you.
