### ISSUE TITLE
Web - client UI & UX changes

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#228]
Please, let's make some changes in the web-profile according to the list below:

- Replace the "circle" menu to the "hamburger" (as in the mobile app)
- Move the menu button to the top left corner
- Balance box should lead to User profile when clicking
- Add the button, which opens User profile QR-code and link for sharing window

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/203331081-ac0d72ee-b754-48d5-8f81-be3b7c0e8ac5.mov

**Comment by dzinzyura** [comment]
Looks great! Just one suggestion: maybe we can reduce the size of this window with QR-code if it's possible? e.g. to make it's frames between blue header and "Items"?

**Comment by dendidibe** [comment]
<img width="1435" alt="Снимок экрана 2022-11-22 в 16 09 52" src="https://user-images.githubusercontent.com/54039544/203335113-d221a6c7-946b-4fa5-811f-30faeeceb3d5.png">
@dzinzyura

**Comment by dzinzyura** [comment]
awesome! thank you, @dendidibe!
