### ISSUE TITLE
Web-client - Notifications redirecting

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#229]
**Goal:** 
Introduce the possibility of getting to the page from notifications.

**Affected metric:**

- UX enhancement 
- Ease of use
- Ease of getting to the web-profile

**Story:**
As a user I received a notification from Ethora web-client. When I click on this notification it opens the web-client chat tab (or, if possible, the specific chat room, from which the message was sent)

**Description:**
Implement the logic of redirecting to the Chats tab, when the notification is received and clicked

AC:
-  Redirecting to the web-client after clicking on the notification

![image](https://user-images.githubusercontent.com/99117374/203323833-04650b6c-0689-4ced-9f48-473f57d2d2a7.png)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/203334115-4a6788ae-3d6e-4b27-9c53-44dfa96a633a.mp4

**Comment by dzinzyura** [comment]
awesome! great stuff, Misha, thank you!
