### ISSUE TITLE
Web version issues 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#230]
1. Audio messages not visible in web - need to implement same UI with waveform as in mobile client.
2. Profile of other users opens into Transactions screen. We should see the whole profile including assets, DM button etc.

<img width="1124" alt="Screenshot 2022-11-23 at 09 51 05" src="https://user-images.githubusercontent.com/328787/203517202-4c0bc7cb-2892-422b-8983-f74740622868.png">

**Comment by dzinzyura** [comment]
1. Done. Thanks, @ibnsan! @phwizard please, let us know if it's OK for now or should Anton change the UI of the audio message display
![image](https://user-images.githubusercontent.com/99117374/205107586-0e97728a-eb46-439c-936c-a9c330a11872.png)

2. Fixed, thank you, @dendidibe
