### ISSUE TITLE
[mobile, web] Config updates

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#231]
Please do the following updates to the Config file.
This is to finalize version 22.11 for current release purpose + improve future compatibility and support for both Mobile and Web.
We will do another review of Config for 22.12 making it even better readable and logical. 

=

Move section "//images for tutorial screens” to the bottom of the file, create section header there: “// TO BE DEPRECATED // ”.

Same as above for “/* TUTORIAL */“ section. 

Same as above for "/* USERS AND ACCOUNTS */"
// EMAIL MANAGEMENT
and
// PREMIUM MEMBER CHECK
sections - move them to  “// TO BE DEPRECATED // ”.

Master switches - add this section somewhere in the initial parts of the Config file. 

/* 
START SCREEN switch.
This specifies which screen is going to be the default one for Users. See options below. 
(A) Starred rooms. In social-focused applications which is also default for Ethora, this is ’roomsStarred’ which means user will first see the messaging interface with ‘starred’ tab selected. 
(B) Own Profile screen. In business-focused applications you may prefer to have ‘profileOwn’ be the start screen. That’s where User can view their own profile, see their documents / assets and share their information via QR and links.
(C) Chat Bot. In some business and social applications, User needs to be greeted by a chat bot. It may be the case that most of the interaction will happen in one Room via a conversational interface. In such case, specify ‘roomBot’. This means that the app will send a “hi” message to your default chat bot and the User will be redirected to their individual Room with the bot, as their start screen experience. The default chat bot will prompt the User for further actions from there. 
(D) Metaverse mode. If you prefer a gamified / metaverse experience, however, you may want to start from ‘roomsNav’ option which prompts the User to start ‘walking’ around Rooms in a metaverse presence mode. 
*/

configStartScreen = ‘roomsStarred’; // default option (A) - start with the starred or default chat Rooms
// configStartScreen = ‘profileOwn’; // option (B) - users start from own Profile
// configStartScreen = ‘roomBot’; // option (C) - User starts in a room guided by your default Chat Bot
// configStartScreen = ‘roomsNav'; // option (D) - User starts in a ‘metaverse’ mode

/* 
META / NAV master switch.
When enabled, this means that your Users can use the “metaverse” navigation mode to move between Rooms. 
In this mode, Users can also create their own Rooms next to existing ones, collaboratively building a social metaspace. 
If disabled, all rooms will be static and no navigation UI will be shown. 
*/ 
configMetaNav = true; // most business apps would prefer this disabled

/* 
ITEMS / NFT master switch. 
When this setting is enabled, your Users can mint and trade NFTs a.k.a Items.
Business applications may prefer this disabled and use Documents asset type instead. 

Developers notes: 
(1) We hide “Mint NFT” from Actions menu when this is enabled. 
(2) In Profile, we already hide types of assets that User doesn’t have, however we should also check this switch to make sure we don’t display contextual NFT related UI in apps where this is disabled. 
*/ 

configNFT = true;

/* 
DOCUMENTS master switch. 
When this setting is enabled, your Users can create and share Documents asset type. 
Most business applications would prefer this enabled. 
*/

configDocuments = true; 

=

Please update  the login screen section a bit like this (note added comments plus metamask option)

// LOGIN SCREEN 

// Enable or disable options below to control which login options your Users should have. 

const googleSignIn = true; // social sign on with existing Gmail account
const appleSignIn = true; // social sign on with existing Apple account
const facebookSignIn = true; // social sign on with existing Facebook account
const metamaskSignIn = true; // sign in with Metamask or Wallet Connect crypto ID
const regularLogin = true; // custom login+password - users have to register first 
const regularLoginEmail = false; // custom login using e-mail address for login - users have to register first 
const regularLoginUsername = false;

**Comment by dendidibe** [comment]
added file to src/config/connfig.ts for web, updated for mobile

**Comment by dzinzyura** [comment]
thank you, Misha! great stuff!

**Comment by phwizard** [comment]
@dendidibe 
also would be good to manage owner sign in options as well in the login Config options

You can add:

===
const ownerRegistration = true; // if you want to display a button for Owner registration in your login screen
const ownerSignIn = true; // if you want to display a button for Owner sign in in your login screen
===
