### ISSUE TITLE
Web Explorer issue

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#232]
There is some issue with web Explorer showing zeroes here:

<img width="765" alt="Screenshot 2022-11-24 at 16 13 23" src="https://user-images.githubusercontent.com/328787/203828539-91f69200-c4ea-424f-acc7-80ab1e9e04df.png">

**Comment by dzinzyura** [comment]
@dendidibe let's remove this "Miner" section, leave just "Blocks" with already displayed information and enlarge or expand the graph

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-01-25 в 10 02 36" src="https://user-images.githubusercontent.com/54039544/214510171-f2dd5c0d-b7a9-48e9-9dae-966f2422f536.png">

**Comment by dzinzyura** [comment]
Done. Thank you
