### ISSUE TITLE
DP Stats review, repair and update

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#233]
Please review and repair the stats mechanism for Dappros Platform metrics. 

This can be placed into Owner or Super Owner account - basically just need to have access to main stats of the system.

Most important metrics:
* API calls
* Blockchain transactions

Also useful to collect secondary importance stats
* Users sign in sessions
* IPFS files stored
* Tokens / assets created 

etc

**Comment by phwizard** [comment]
Discussed - will keep current setting where app Owners can see network stats.

**Comment by dzinzyura** [comment]
@transkarpation can you restore this [interface]( http://app-dev0-old.dappros.com/userAnalysis ), please

_some notes:_
1. “Traffic Analysis” is not needed, you can remove or keep whatever is easier. It was done earlier to track people coming from promotions.
2. User Analytics - not sure if we need this - seems like simply a list of users - however it would be good to have a diagram with a number of end users registered. Maybe “Users” can be added as a tab into “Statistics” screen? After “Blockchain transactions”? Here we’ll be just tracking a number of end users registered.

**Comment by transkarpation** [comment]
![image](https://user-images.githubusercontent.com/57521389/210957637-9c43462b-47f5-4571-9a96-4b9e4afd46b9.png)
![image](https://user-images.githubusercontent.com/57521389/210957719-9128a32e-420b-4a00-afba-7cb10033a336.png)
If user has masterAccess he can view statistics
