### ISSUE TITLE
Web - chats list - recent timestamps more tidy

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#234]
Let's make the recent timestamps more tidy. 

For example, "about 2 hours ago" and "37 minutes ago" here can be "2h" and "37 min" instead, then we can fit them under same column on the right where other timestamps are and this will all look better. 

<img width="1499" alt="Screenshot 2022-11-25 at 15 50 47" src="https://user-images.githubusercontent.com/328787/204019824-26fd9c1f-a048-4f63-9ab7-2856c494dcfa.png">

**Comment by dzinzyura** [comment]
@phwizard Anton made such changes as in Telegram, so could you, please, have a look once you have a chance. I think we can remove seconds in chatroom timestamps

![image](https://user-images.githubusercontent.com/99117374/204840250-50912a71-6b28-45c4-96f1-cea2dc50d821.png)

![image](https://user-images.githubusercontent.com/99117374/204840486-4b692382-565d-40a0-bc06-c4e7fe171757.png)
