### ISSUE TITLE
Web - chat avatars

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#235]
Can you please make the initials in the non-image avatars to be more centered? Right now this looks too close to the top of the circle.  

<img width="382" alt="Screenshot 2022-11-25 at 15 57 54" src="https://user-images.githubusercontent.com/328787/204020867-686e13fe-5544-48a7-af8c-44ace26591ec.png">

**Comment by dzinzyura** [comment]
Fixed. Thank you, Anton!
