### ISSUE TITLE
Nav mode finalize and connect to backend

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#236]
Tasks to finalize Nav mode and connect it to backend for Alpha version.

1. Nav mode and start Room. Nav mode should be off by default unless it is specified in Config file to start in Nav mode. If User has switched on the Nav mode, it should be switched on unless User switches it off. This on/off setting should persist across login sessions. If User has enabled Nav mode first time and User is already in a Room, client should check with backend if the Room is registered with roomContract (getRoom(roomAddress)). If it is, simply show navigation showing links obtained from the backend. If not, then move the User to the default room (Agora English). 

2. If User has enabled Nav mode not a first time (including situation where User logs in and the Nav mode was already on) - client should be checking Nav location of the User from roomContract every time User taps on Nav - so whenever this data is not empty, the last location Room should be opened, without moving the User, and navigation displayed.

3. Every time the User moves we change their "meta" location informing backend of that via function.

4. If User opens a Room on the client that is not registered with roomContract (getRoom API returns nothing for our room address) so a simple chat room without meta mode, then we display it as normally without moving the User in roomContract and we don't display Navigation in such room. Tapping the Nav icon should return the User to the latest Nav/meta supporting room according to Users location as registered in roomContract.

**Comment by dzinzyura** [comment]
Build for a review https://dappros.slack.com/archives/C025G04FQV6/p1669909997810999?thread_ts=1669895264.757059&cid=C025G04FQV6

**Comment by phwizard** [comment]
Thank you.
