### ISSUE TITLE
Profile view for Guests

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#238]
For guests, can you please remove app logo (same as for authenticated users, we remove logo to have more free space and make it easier to re-brand). 

And also please hide "Direct Message" button for guests (non-authenticated users). 

See current authenticated (left) and guest view (right) below:

<img width="2446" alt="Screenshot 2022-11-28 at 11 56 38" src="https://user-images.githubusercontent.com/328787/204272263-b8aee491-2084-46b2-a8c8-56d0e0d480de.png">

**Comment by dendidibe** [comment]
<img width="1435" alt="Снимок экрана 2022-11-28 в 14 58 24" src="https://user-images.githubusercontent.com/54039544/204283631-d61f892f-ce78-4344-9a1e-c35fad4da271.png">
