### ISSUE TITLE
Mobile: error prefix for XMPP

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#248]
Please add so it says

XMPP: too much traffic

For all XMPP server errors.
So add "XMPP: " for all errors that come from XMPP server.

![Screenshot_2022-12-06-14-49-07-897_com.ethora.jpg](https://user-images.githubusercontent.com/328787/205944000-a16b36bb-696c-44db-9655-3f7132f8f029.jpg)

**Comment by dzinzyura** [comment]
Done. Thank you. Misha!

[Link to the build for review](https://dappros.slack.com/archives/C025G04FQV6/p1670403297841529)
