### ISSUE TITLE
Remove buttons from submenu

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#249]
Please remove the button from this submenu

![Screenshot_2022-12-06-14-51-51-478_com.ethora.jpg](https://user-images.githubusercontent.com/328787/205944832-05f65545-82c7-4c13-ad67-fd5ed6589a1a.jpg)

**Comment by dzinzyura** [comment]
Done. Thanks, @dendidibe!

![image](https://user-images.githubusercontent.com/99117374/206134205-d7c4d43f-6234-4513-8757-82252a964a06.png)
