### ISSUE TITLE
Coin name in chat fix

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#250]
Please make sure same consistent Coin name is taken from Config and used everywhere.

![Screenshot_2022-12-06-14-53-21-547-edit_com.ethora.jpg](https://user-images.githubusercontent.com/328787/205945691-0874de3d-4240-458d-b5a9-a135638d0a35.jpg)

**Comment by dzinzyura** [comment]
@phwizard the "Dappros Platform Token" displayed in the app because of the web-client chat. 
@dendidibe will change the name to "Ethora Coin" in the web-client

**Comment by phwizard** [comment]
@dzinzyura @dendidibe OK, please close this once done

**Comment by phwizard** [comment]
I thought however that the default token name will be auto-replace anyway for better UX, using what the default token/coin name is in mobile app Config

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/206198339-281d3f58-666d-4f77-888b-aeb51f84d6fc.mov
