### ISSUE TITLE
Creating a new room - image issues

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#253]
When creating a new room from scratch, the room image doesn't add correctly and app sometimes crashes.

Creating room without image is fine.

Also adding image later from the chat details screen is also fine.

Can you fix it so users can add image when creating, without issues?

https://user-images.githubusercontent.com/328787/205975616-81bdc336-4e45-464c-a7c2-c7a7a0ddc027.mp4

**Comment by dzinzyura** [comment]
Done. Thanks, @4RGUS!

[Video](https://dappros.slack.com/archives/C025G04FQV6/p1670488734364179?thread_ts=1670487505.915669&cid=C025G04FQV6)
