### ISSUE TITLE
App re-open problems

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#255]
Let's fix this. See video. Issues when restarting the app when it was used before.

May be related to JWT.

https://user-images.githubusercontent.com/328787/206001687-a76cf0a0-5e87-4177-beb3-90f035b212be.mp4

**Comment by dzinzyura** [comment]
Fixed. Thanks @4RGUS !

[The build with fixes](https://dappros.slack.com/archives/C025G04FQV6/p1671116386719789)
