### ISSUE TITLE
Web - enable icon tabs

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#257]
Please implement rooms tabs in the Web client similarly to how it's done in Mobile client.

You can skip the Compass (meta mode) tab for now and keep it inactive.

Please enable "Starred" and "Dialogs" tabs so they work same as in mobile:
1. 'Starred' only displays 'pinned' rooms as specified in local Config file + also those rooms that user has starred. 
2. 'Dialogs' displays the rest of rooms, sorted by most recent messages. Most recent chats go first, then less recent. Timestamp shows time for chats within last 24h and shows date for chats which are older. 

After this is done, you can remove "Messaging" section from the menu as chats will be accessed via these icon tabs now. 

<img width="940" alt="Screenshot 2022-12-09 at 09 27 37" src="https://user-images.githubusercontent.com/328787/206669669-ff177f80-c7ea-49a9-aef1-fb2248f75897.png">

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/207148767-31ad94ed-2287-40a1-ad50-556ec0484ec5.mov

implemented icon tabs navigation

**Comment by dzinzyura** [comment]
great stuff! thank you Misha
