### ISSUE TITLE
Web - implement Compass / "meta" navigation

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#258]
Please implement meta navigation - accessible via "Compass" icon tab similarly as in Mobile version.

You can leave out the rooms creation for now, only do "read only" navigation where User walks between 'meta' rooms and updates his/her location to the server. 

@dendidibe @dzinzyura 
Once this task is done, please create a subtask or simply proceed with Room creation as well for Web version.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/207142113-7756904e-d06f-465b-b623-fb36aaea69c6.mov

added meta navigation to web

**Comment by dzinzyura** [comment]
Thank you, @dendidibe! great stuff. you can start with the room creation and I'll create a sub task in the morning for it, cause i don't have electricity at the moment :(
