### ISSUE TITLE
App submission improvements

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#261]
**Goal:**
Introduce the changes according to latest Apple guidelines

**Affected metric:**
- UI&UX enhancement
- Privacy and data sharing enhancement

**Description:**
Implement the changes according to the latest update of Apple guidelines:

- Remove the "voip" setting from the UIBackgroundModes key.

- Fix “Sign in with Apple logic“ - [Apple Guidelines](https://developer.apple.com/documentation/authenticationservices) 
If we don't get any name you can implement like this: 
Show "anonymous" for the first name
And random animal name for last name like in Google Doc (panda, bandicoot, horse, racoon whatever).
Then user can change their name in profile if they want.

- Make sure that our app is optimized to support the device screen size or resolution _(will be updated which screens need fixing)_

- [App Tracking Transparency implementation](https://developer.apple.com/documentation/apptrackingtransparency)

**Comment by dendidibe** [comment]
<img width="317" alt="Снимок экрана 2022-12-19 в 15 47 57" src="https://user-images.githubusercontent.com/54039544/208440156-18410293-e4a3-413b-beb9-853732150954.png">

**Comment by dzinzyura** [comment]
Everything's done. Thank you, @dendidibe!

@bikash-code could you, please, check the app resolution/sizes on different devices once you have a chance
