### ISSUE TITLE
Web - room creation

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#262]
Implement the Room creation logic for the web-client

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/208390760-04717a8b-81df-416e-8e0d-66f5e5b56f85.mov

**Comment by dzinzyura** [comment]
Let's add "New room" to the ACTIONS subcategory in the menu for this feature @dendidibe

**Comment by dzinzyura** [comment]
Done. Thanks @dendidibe!
