### ISSUE TITLE
User accounts export/download

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#265]
Please implement a download/export route for User accounts. 

I assume this will be exported as a JSON file (or zipped JSON) with data that we hold in database regarding the specific User:
* User account (profile data)
* Data table entries

This will be available via existing UI in the Privacy & Data section. 

This will be useful for GDPR compliance so that users can see what data we hold on them (and decide whether they want to delete it which we have already implemented), and generally to allow users to download/export their data.

**Comment by transkarpation** [comment]
https://app-dev.dappros.com/api-docs/#/Users/get_v1_users_exportData

**Comment by transkarpation** [comment]
https://app-dev.dappros.com/api-docs/#/Users/get_v1_users_exportData
