### ISSUE TITLE
Mobile: finalizing threads

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#267]
Currently there are following issues with thread:

1. Simply a number under first message doesn't make it clear for users what that is about.
2. No (easy) way to review thread messages unless you send a message into thread

Please adjust as follows:
* If message has a thread, add "View thread" into quick message menu. Under "Reply" and "Copy" options. That should open the thread UI same as if someone tapped "Reply". 
* Replace number e.g. "2" with a better description: "2 replies (tap to review)". Make this active - if someone taps on that text the thread UI opens.

**Comment by dzinzyura** [comment]
Done. Thanks @4RGUS 

- "View thread" option inside quick message menu when there are replies to message.
- Reply counter will now show as "2 replies (tap to review)"
- On click of reply counter will open corresponding thread.

[Video](https://dappros.slack.com/files/UN520JLQY/F04FJ276CPM/simulator_screen_recording_-_iphone_13_-_2022-12-16_at_11.24.50.mp4)
