### ISSUE TITLE
Bot & Contract - NFT "Create Bot" changes

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#268]
1. The bot should respond to any of these keywords (not case sensitive):

any of: create, mint, NFT
+ bot 

2. If user says “exit”, “stop” or “leave” as a single word any time, bot should ask:
Would you like to stop the process? 
with 
“Yes, stop 🚫”
and
“No, keep going ▶️” 

If User chooses “Yes, stop” then the Bot stops the process and deletes the latest state of the dialog with this User. 
Next dialog will start from the beginning.
“No, resume” simply continues with the same state.

3.
Please skip the contract type question where it says “Please choose contract type:". Instead, write this:

"Just so that you know, I will use “NFmT Standard” template for your collection set up."

"This means in your collection you will have:"

"1) 25 x Paper NFTs: free,
2) 50 x Copper: 100 Coin ($0.1) each,
3) 100 x Steel: 1,000 ($1) each,
4) 10 x Silver: 50,000 ($50) each,
5) 3 x Gold: 150,000 ($150) each,
6) 1 x Diamond: 1,000,000 ($1,000) each, 
with a total minted value of 189 NFTs and $2,055."

"Any User will be able to purchase NFTs directly from this Collection.”

“Tip: you can type ‘exit’ or ’stop’ any time before we finish the mint in case if you change your mind.”

“To proceed, please send your art. JPG and PNG images are supported. (Hint: use paperclip icon bottom left.)”

4. Skip “please set the minimum paid tier price in Coins…”. Instead, we will use the standard pricing from this default template (free for Paper and 50 for Copper type).

5. Change “Now, …, how many Beneficiaries” messages to the following:

“Sales proceeds will go to you by default. In case you wanted to add another beneficiary, please specify how much of the proceeds they should receive:”
[ Share 100% ]
[ Share 90% ]
[ Share 50% ]
[ Share 10% ]
[ Not at the moment - skip this step ]

If User chooses “Not at the moment..” then simply assign proceeds to go to their L2 wallet. 

If any other option is selected, display this step:

“Please enter an address for your beneficiary that will receive X% of sales proceeds from this collection.”

User enters an address - please use Ethereum address verification such as a regular expression to carry out a simple verification such as length check.

6. Let’s skip the “drop into the room” step as well. Instead of this:
“would you like to go ahead? The operation will cost 3 Coins. After I mint I can send NFMT to your wallet or drop it in the room.” 

please write the following:

“Now, simply send me 3 Coins (hint: long tap on my message) to mint your NFT collection.”

UPD: Note: after the mint, please still have the Bot to drop the link into the room. 
Ideally the link should look like this:

🔗🖼️ **NFT Item or Collection title**
(tap to view NFT)

plus optional preview under it.

7. Change the wording here “start to process your request, please wait” to “Righty-ho, I’m minting 🛠️ your collection smart contract 📜 on chain 🔗 as we speak, you can leave this with me now..”

8. Once minted, write this message:
"Awesome and congrats 😎🍸! Your NFT collection has been minted.” 

"It should be accessible in your profile under “Collections” tab now. Anybody can purchase NFTs first come - first served, starting now!”

“Good bye 👋 and looking forward to be working with you again!” 

8. Add “waving hand” emoji into first message like “Hi 👋 Taras Filatov, I’m Create Bot..”

9. Replace “NFMT” with “NFT” everywhere in messages except this one:
"Just so that you know, I will use “NFmT Standard” template for your collection set up.”

**Comment by dzinzyura** [comment]
All mentioned changes are done. Need to be tested

thank you, @transkarpation!
