### ISSUE TITLE
Coins purchase screen

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#269]
Please implement a simple Coins Purchase screen under "Account".

Menu name:  "Buy Coins" 
Show this under "Referrals".
Also remove "E-mails".

---

The screen will have the intro text and purchase options.
Just use system UI where possible.

Intro text:

---

Here you can purchase Coins. 
Use Coins to unlock features such as create your own "meta rooms" or purchase NFTs. 
You may also use Coins to reward other users (use them as "likes" in respond to useful chat messages etc).

Please choose how many coins you would like to purchase now:

849 Coins - $0.99
8,491 Coins - $9.99
21,250 Coins - $24.99
42,500 Coins - $49.99
85,000 Coins - $99.99

---

Once User has done the payment, we send them the relevant amount of Coin:

"Thank you, your payment has gone through and your balance will be topped up now!"

**Comment by dzinzyura** [comment]
Done. Thank you guys

![image](https://user-images.githubusercontent.com/99117374/209643917-b9b8dd7e-4632-4400-8872-2a8bc89b9757.png)
