### ISSUE TITLE
Thread reply fix

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#270]
Please:

1) Change wording "Also send in Chat room?" to "Also send to room".

2) Move this checkbox section above the message entry box so it's clearer for the user this is related to the message they are typing.

![Screenshot_2022-12-20-02-52-37-945_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208570735-41f9f894-963e-4cd1-8560-63a17c7a50d1.jpg)

**Comment by dzinzyura** [comment]
![image](https://user-images.githubusercontent.com/99117374/208617159-0be3b57b-65b6-4a9d-8080-4040c0415776.png)

**Comment by dzinzyura** [comment]
Looks awesome! thank you @4RGUS !
