### ISSUE TITLE
Emojis for links inside chats

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#273]
Let's bring the links to the unified standard and also improve / add those which aren't handled yet.

Please implement as following for links to Rooms, User profiles, Documents and NFTs or Collections inside chats.

🔗💬 **Room title**
(tap to open room) 

🔗👤 **User name**
(tap to view profile) 

🔗📄 **Document title**
(tap to view document)

🔗🖼️ **NFT Item or Collection title**
(tap to view NFT)

This should be done in both Mobile and Web versions.

**Comment by dzinzyura** [comment]
Done. Thank you, Vineeth!

![image](https://user-images.githubusercontent.com/99117374/208898385-49ea3427-6c7c-427d-8539-8c4454742d1c.png)

**Comment by phwizard** [comment]
Done - thank you!
