### ISSUE TITLE
Remove "media" from quoted messages

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#275]
Please also remove "media" from here

![Screenshot_2022-12-20-22-45-28-183-edit_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208781110-f98438d2-3b2b-4437-b83c-a683ddbe3523.jpg)

**Comment by dzinzyura** [comment]
Done. thanks! 

![image](https://user-images.githubusercontent.com/99117374/208899134-8f918225-202b-4c9c-89ea-ffe2dbf177b5.png)
