### ISSUE TITLE
Coin prices / values display standard 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#276]
Let's simplify these big numbers for users.

Please apply the following rules to showing large prices and balances in Coin:

1) For all values which end with 000 replace that with K.

Example:
Was 20,000
Now 20K

2) Apply coma formatting to make numbers easier to comprehend

Example
Was 1245000000000
Now 1,245,000,000K

![Screenshot_2022-12-20-22-47-58-100_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208782005-de94db2c-f9c5-49ab-88bd-41efd21a7b69.jpg)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/208861155-f9e138fa-4079-4a22-a8f1-4933c805c470.mov

**Comment by dzinzyura** [comment]
Thank you!

[Build for review](https://dappros.slack.com/archives/C025G04FQV6/p1671618382276689)
