### ISSUE TITLE
Remove "E-mails" for now

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#277]
Please remove "E-mails" screen from the menu.

We will replace it with advanced screen in future versions allowing user to manage identities, wallets and sign ins.

![Screenshot_2022-12-20-23-28-46-341_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208785879-09933698-1a73-46bf-aa6e-12f6589d24be.jpg)

**Comment by dzinzyura** [comment]
Done. Thanks, Vineeth!

![image](https://user-images.githubusercontent.com/99117374/208899360-a0b1c89e-086f-4580-9a76-8d58e695f2d2.png)
