### ISSUE TITLE
Items, Collections - Delete and Copy buttons etc

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#278]
Please add Delete and Copy icons in the Items and Collections similarly as in Documents.

Copy icon should copy a link so it can be sent to chat room. 

Delete should call a dialog:

Do you really want to delete (burn) this NFT?

Do you really want to delete (burn) this NFT collection?

Buttons:
No, cancel ✖️
Yes, burn 🔥

If User says Yes, then request the server to delete 

Server will not delete and return an error if a user is trying to delete a collection somebody has already purchased from.

In this case display an error:

🛑 Can't burn this collection as someone already owns NFTs in it. 

Also, when viewing Collection or Document details, please display "Collection" or "Document" accordingly instead of "Item" in the nav bar.

![Screenshot_2022-12-21-06-31-36-194-edit_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208837605-2fbfe27d-8877-416b-b14f-04eceb8ba273.jpg)

![Screenshot_2022-12-21-06-31-50-254-edit_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208837673-c7c68c0c-cfdc-4bce-bd30-1a60d89125e1.jpg)

![Screenshot_2022-12-21-06-32-05-257_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208837693-8dce7993-64e6-4ba2-878f-9f3a9e5e7bfb.jpg)

**Comment by dendidibe** [comment]
@phwizard i think we cant add copy button, because we cannot create link directly on this screen. @transkarpation can correct me if i am wrong

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/208878129-39fb68e7-2d27-4e8f-9248-3d4f4440fbd4.mov

**Comment by dzinzyura** [comment]
Thanks, Misha!
Great stuff!

[Build for review](https://dappros.slack.com/archives/C025G04FQV6/p1671618382276689)
