### ISSUE TITLE
Transactional mails via Postmark and ethoramail

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#279]
Please migrate system emails such as transactional mails to Postmark, to be sent from ethoramail domain

**Comment by transkarpation** [comment]
@phwizard what the local part of email address should I use? Could it be noreply@ethoramail.com?

**Comment by dzinzyura** [comment]
let's try to use hello@ethoramail.com just to check If the name depends on the emails going to spam, as we discussed this morning @transkarpation

**Comment by phwizard** [comment]
let's use noreply@ethoramail.com

**Comment by transkarpation** [comment]
done
