### ISSUE TITLE
Document delete error message update

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#280]
Do you really want to delete this document?

Note: this action is irreversible.

![Screenshot_2022-12-21-14-37-39-203_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208930627-783b8713-9f0a-40a3-9542-7ebdbeb24d1c.jpg)

**Comment by dendidibe** [comment]
<img width="347" alt="Снимок экрана 2022-12-27 в 13 52 43" src="https://user-images.githubusercontent.com/54039544/209662854-f5a7254a-c2c9-44aa-a548-57bcd9975119.png">
