### ISSUE TITLE
Items provenance slight mod

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#281]
Please make the part after picture emoji "(of 5 total)" non-bold. 

Please also add type/trait tag here as soon as it's supported in transactions / server side. 

We can either replace picture emoji with appropriate trait tag, or add trait tag after 'total'.

So it can look like this:
a) **1** [paper] (of 5 total)
or 
b) **1** 🖼️ (of 5 total [paper])

Replace 'NFTs minted by' with 'purchased for 🪙 **X** by '. 

(use our coin icon instead of coin emoji above)

![Screenshot_2022-12-21-14-41-46-822_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208931447-9e7af982-f494-4011-81e8-656871f70c1d.jpg)

**Comment by dendidibe** [comment]
<img width="323" alt="Снимок экрана 2022-12-23 в 13 25 1@phwizard " src="https://user-images.githubusercontent.com/54039544/209328085-a9aeabf0-0af9-4915-8aa3-3fd18b4c9a39.png">
@phwizard
