### ISSUE TITLE
Edit message feature

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#282]
Please add "Edit" option into quick response menu when user does one tap on _own_ message and implement this function in the mobile client app.

I guess you can just post the old message content into message entry box and let the user edit it there, then when user hits the standard "Send" button, the old message will be replaced with the new one.

Implementation notes:

`For the plugin to work properly, you need to send the following stanza:
<message from="olek@localhost" id="1635229272917013" to="test_olek@conference.localhost" type="groupchat">
    <body>Wow</body>
    <replace id="1635229272917013" xmlns="urn:xmpp:message-correct:0"/>
</message>
And all users in room will receive next:
<message xmlns="jabber:client" xml:lang="en" to="olek@localhost/1216574346180782548712130" from="test_olek@conference.localhost/olek" type="groupchat" id="1635229272917013">
    <archived by="test_olek@conference.localhost" id="1635233863744841" xmlns="urn:xmpp:mam:tmp"/>
    <stanza-id by="test_olek@conference.localhost" id="1635233863744841" xmlns="urn:xmpp:sid:0"/>
    <replace xmlns="urn:xmpp:message-correct:0" id="1635229272917013"/>
    <body>Wow</body>
</message>`

**Comment by phwizard** [comment]
Done for mobile.

@4RGUS please implement for web.

**Comment by dzinzyura** [comment]
Done for both Mobile and Web-client. Thanks @4RGUS 

![image](https://user-images.githubusercontent.com/99117374/213444690-5aebd763-eca1-4b55-8235-aebe1d7f581e.png)
![image](https://user-images.githubusercontent.com/99117374/213444715-b198595d-fbb6-455a-881f-bce81f275c9d.png)
