### ISSUE TITLE
Refer and Earn touch up

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#283]
Please replace ETO here with our coin symbol.

![Screenshot_2022-12-22-10-43-01-027_com.ethora.jpg](https://user-images.githubusercontent.com/328787/209117361-466f6dfa-6998-4235-bb05-99eaed8fc224.jpg)

**Comment by dendidibe** [comment]
<img width="347" alt="Снимок экрана 2022-12-27 в 13 51 09" src="https://user-images.githubusercontent.com/54039544/209662666-2f5377e4-4865-4d60-b815-d3a47abdabff.png">
