### ISSUE TITLE
Authentication screen: Metamask

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#285]
**Goal:**
Introduce the wallet address display via Metamask

**Affected metric:**
- UI & UX enhancement
- Data accessing ease
- Ease of use
- Ease of control & operation

**Story:**
As a user I open "Authentication" in the menu, I can see "Confirm with Metamask" button. When I click on it takes me to the Metamask app, from which the app extracting my wallet address.

**Description:**
Add a possibility to confirm the user's wallet address using simple Metamask action.

In case Metamask wasn't successful: "Your Metamask connection wasn't successful." Come back to the previous screen.
In case it was successful, show a pop-up: "Your Metamask connection was successful."

[Linked issue](https://github.com/dappros/ethora/issues/284#issuecomment-1363741014) 

![image](https://user-images.githubusercontent.com/99117374/209311780-efb2f29e-2c93-4671-be7f-46eaabc65261.png)

**Comment by dzinzyura** [comment]
**EXCEPTION**

If sign in method is Metamask (or other WalletConnect type of L1 wallet authentication), then:

1. We show the top section as already linked state (screen in the right). This is because with this sign in option we already know the L1 wallet and we don't have to ask for it again.

2. We do not display this part "Use button below.." and "Remove" button. Alternatively, you can show the button as "disabled" (greyed out) state and don't action anything when user taps there. This is because by removing this link, we will block the user from logging in.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/209662352-d749d604-0a84-4166-be0d-8802cdbb3ede.mov
