### ISSUE TITLE
Authentication screen: QR scan

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#286]
**Goal:**
Introduce the Ethereum wallet address display via QR-code scanning

**Affected metric:**
- UI & UX enhancement
- Data accessing ease
- Ease of use
- Ease of control & operation

**Story:**
As a user I open "Authentication" in the menu, I can see "QR scan" button. When I click on it takes me to the "scanning" screen, I point the device at my QR code and it scanning. After this window is closed I can see my Mainnet address.

**Description:**
Add a possibility to confirm the user's wallet address using simple QR code scanning action.
Scan QR should open the QR scan functionality that allows to obtain the Ethereum address. 
Also, please, validate that the data obtained is the Ethereum address.

In case of QR scan data not validating: "This doesn't look like a valid Ethereum address". Come back to the previous screen.
In case of successful scanning: "Your address was successfully validated."

[Linked issue](https://github.com/dappros/ethora/issues/284) 

![image](https://user-images.githubusercontent.com/99117374/209313751-03920f2b-7735-4cbc-a939-646743620639.png)

**Comment by dendidibe** [comment]
i cant record this example because emulator doesnt support it
