### ISSUE TITLE
Authentication screen: Sign On method

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#288]
**Goal:**
Introduce the user's sign on method display

**Affected metric:**
- UI & UX enhancement
- Ease of use
- Ease of control & operation

**Story:**
As a user I open "Authentication" in the menu and can see my sign on method. 

**Description:**
Add a display of user's sign on method, using:
[Email service] (email address) 

e.g. 
GMail (taras@dappros.com)
or
iCloud (v.dzinzyura@icloud.com)

[Linked issue](https://github.com/dappros/ethora/issues/284) 

![image](https://user-images.githubusercontent.com/99117374/209313751-03920f2b-7735-4cbc-a939-646743620639.png)

**Comment by dendidibe** [comment]
<img width="364" alt="Снимок экрана 2022-12-23 в 12 27 21" src="https://user-images.githubusercontent.com/54039544/209319835-a4c1eb36-e44d-4cb0-9814-161376dd2cf5.png">

**Comment by dzinzyura** [comment]
looks good, thank Misha
