### ISSUE TITLE
Authentication screen: Connected address operations

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#289]
**Goal:**
Introduce the next operations with already connected Mainnet address:
- Address copying
- "View on Etherscan"

**Affected metric:**
- UI & UX enhancement
- Ease of data use
- Ease of control & operation

**Story:**
As a user, when I connected my Mainnet address, I copy it by clicking on it on the screen. 
Also, I click on "(view on Etherscan)" button and it redirects me to the Etherscan search using my address and showing all the information for my wallet address. 

**Description:**
Add a possibility of copying user's address when the Mainnet address is already connected.
Add a redirecting to the Etherscan when the corresponding button is clicked.

[Linked issue](https://github.com/dappros/ethora/issues/284) 

![image](https://user-images.githubusercontent.com/99117374/209313751-03920f2b-7735-4cbc-a939-646743620639.png)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/209662288-11ea8285-2e34-436c-bd63-4a7adc12e614.mov
