### ISSUE TITLE
Authentication screen: Remove Mainnet address

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#290]
**Goal:**
Introduce the possibility of removing connected address.

**Affected metric:**
- UI & UX enhancement
- Ease of data use
- Ease of control & operation

**Story:**
As a user, when I connected my Mainnet address and want to remove it, I click on "Remove" button and it shows me a dialog screen with the alert:

Would you like to remove your Mainnet address association?
Note: you can always add an association again using Authentication screen later.

[No, cancel] [Yes, remove]

When I click on "Yes, remove" it takes me back to the Authentication screen (1st screen on the screenshot) and shows a pop-up:

"Your Mainnet address was successfully removed."

**Description:**
Add a possibility of deleting user's Mainnet address. Show an alert-window to confirm this action.

[Linked issue](https://github.com/dappros/ethora/issues/284) 

![image](https://user-images.githubusercontent.com/99117374/209313751-03920f2b-7735-4cbc-a939-646743620639.png)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/209317707-ff0c7944-90fe-48dc-8272-b8f9bd4b5ff1.mov

**Comment by phwizard** [comment]
Please change button from "Confirm with Metamask" to "Read from Metamask".

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/209662207-adb2a20d-b538-4d17-8091-c6af6aebbb20.mov
