### ISSUE TITLE
Kick User feature

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#291]
We had this via different UI before, but this doesn't work in the latest build, so let's implement this.

If our User is owner / admin then:

Next to each user in the list display a " Kick " button.

Once tapped, show a message:

Kick [User Name] from this room?
No, cancel (usual background) Yes, kick (pink / light red background)

If Yes is selected, then proceed and kick the user.

![Screenshot_2022-12-23-10-22-04-024_com.ethora.jpg](https://user-images.githubusercontent.com/328787/209318945-19c3a767-a0a4-4a4b-b9a5-9eb6e207a3cf.jpg)

**Comment by dzinzyura** [comment]
Done. Thanks, Vineeth!

![image](https://user-images.githubusercontent.com/99117374/210535053-f9eecdff-22bf-46ee-abc9-5f4bed07c718.png)
