### ISSUE TITLE
Kick feature fixes

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#292]
Some fixes here:

1) In the menu, please change button caption from "Ban this user" to "Kick this user"
Text under instead of "Kick user.." write "Remove user.."

2) When tapped, ask in a modal:

Kick [User Name] from this room?
No, cancel    Yes, remove

"Yes, remove" is light red background.

After user is kicked, please write a technical / status message into chat room:

[ User Name kicked ] removed by [ User Name admin ]

https://user-images.githubusercontent.com/328787/209355456-1cb270be-102e-4d42-9ee2-c5eb929a4240.mp4

**Comment by dzinzyura** [comment]
@4RGUS please, add a chat message after user is kicked: 
[ User Name kicked ] removed by [ User Name admin ]

Also, is it possible to add user's name when the modal is displayed?

![image](https://user-images.githubusercontent.com/99117374/210537105-859e8fa3-520b-4fa5-b6af-b153007ea1b5.png)

**Comment by dzinzyura** [comment]
Done. great stuff, thank you @4RGUS!

![image](https://user-images.githubusercontent.com/99117374/210755965-bc8d9f09-a82c-4c9d-9fb4-6fdb982a055f.png)
![image](https://user-images.githubusercontent.com/99117374/210755996-16f0bf1d-64aa-4968-8cdc-dc89799aa46b.png)
