### ISSUE TITLE
Camera permission alert - description changes

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#293]
**Goal:**
Introduce the "Camera" permission request alert with a specific purpose string

**Affected metric:**
- UI & UX enhancement

**Story:**
As a user, when I downloaded and opened the app, I got a popup asking for permission to use the camera.

**Description:**
Change the purpose string of the Camera usage description: 
"Allowing access to the camera lets you take and send photos and videos and use other special features."

**AC:**
- Changed description of the Camera permission alert

![image](https://user-images.githubusercontent.com/99117374/209648096-cd28a583-ce6c-479b-9fe1-cb53c927d41a.png)

**Comment by dendidibe** [comment]
<img width="347" alt="Снимок экрана 2022-12-27 в 12 35 28" src="https://user-images.githubusercontent.com/54039544/209654025-80742690-ca79-4365-bf6a-5e9022f4c151.png">
