### ISSUE TITLE
Export bot mods

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#297]
Please make the following modifications:

"Now, send me your Item.."
=
"Now, send me your NFT Item.."

"The token has been exported to Goerly"
=
"✅ The token has been exported to Goerly chain!"

also, instead of "contract address is .." please write these 2 messages:

"Etherscan address:" 

"[ insert Etherscan URL here ]"

"OpenSea address:" 

"[ insert OpenSea URL here ]"

Also change the last message from "Thank you for your business!" to:

"You may now sell or transfer your NFT on mainnet." 

"Thank you for you business & good bye! 👋"

![Screenshot_2022-12-29-13-48-04-423_com.ethora.jpg](https://user-images.githubusercontent.com/328787/209962705-b51564a5-183b-4068-b28c-5ae2adff05a8.jpg)

**Comment by transkarpation** [comment]
![image](https://user-images.githubusercontent.com/57521389/209968295-1ace9a9c-4e99-471a-a005-ff01e1d1fd74.png)

**Comment by phwizard** [comment]
thank you
