### ISSUE TITLE
'main' branch update

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#298]
Please, update the 'main' branch with the 'newArchitecture' one.

**Comment by dendidibe** [comment]
<img width="1086" alt="Снимок экрана 2023-01-04 в 10 28 59" src="https://user-images.githubusercontent.com/54039544/210514198-5fc22326-6cbe-4ef0-a620-0ae133e833c1.png">

**Comment by dzinzyura** [comment]
awesome! thank you, @dendidibe!
