### ISSUE TITLE
Web & Mobile - Export Data feature

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#299]
**Goal:**
Introduce the possibility of data exporting on both web-client and app

**Affected metric:**
- UI & UX enhancement
- Ease of data use
- Ease of control & operation

**Description:**
Connect the already existing [Export data route](https://app-dev.dappros.com/api-docs/#/Users/get_v1_users_exportData) to the web-client and app

**AC:**
1. Data download via Privacy&Data tab in the web-client
2. Data download via Privacy&Data tab in the app

[User accounts export/download issue](https://github.com/dappros/ethora/issues/265)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/210401340-85136649-016f-4223-a61b-fdd0edf18501.mp4

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/210405230-f03d7ad7-71f9-4aef-83d7-20b9de0beda6.mov

**Comment by dzinzyura** [comment]
works great! thanks, Misha!
