### ISSUE TITLE
Coins export bot scenario 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#302]
This will allow users from our Ethora L2 chain to exchange their Coin (Ethora Coin normally held in their L2 balances) into ETH. 

First we should implement the coins export contract(s) and then a chat bot that allows to use this contract bridge.

Ethora Coin is a utility token at this stage so we will establish a fixed price conversion rate.

Note: you can implement this as part of the Export bot, or as a separate Exchange bot.

---

[ Conversation starts ]

OK, let me help with exporting your Coin to mainnet. 

First, do you know which mainnet address we will be sending to? 
Please paste the address below.

[ My L1 address: ]

OK, noted.

Checking the L1 contract, a minute please.. 

[ Check the balance at the mainnet exchange contract ]

[ (A) If cannot read the mainnet contract balance ]

Apologies, I have a trouble reading the mainnet exchange contract.

This means I cannot assist you with this exchange at the moment. 

Perhaps at a later time?

[ show menu / choices again ]

[ (B) If balance in USDC is read correctly ]

All good, we can proceed.

Mainnet contract has X USDC available.

You will obtain USDC at the following rate:
1,000 Coin = 1 USDC

This will be send to your L1 address as specified before:

[ show the address here ]

To proceed, simply send me the amount of Coin you’d like to export. 

Alternatively, say “Stop” if you’d like to think more about this.

[ 🚫 Stop ] 

[ If user chooses “Stop”:]

OK, hope to see you soon again! Bye! 👋

If user has sent Coin:

👌Thank you, I’m now proceeding with your transaction. 

X USDC are being sent to the address you have specified..

[ After transaction has been completed ]

✅ All done - funds have been sent. 

Transaction can be verified here: 
[ Etherscan link ]

Thank you for your business and hope to see you soon again! Bye! 👋

**Comment by phwizard** [comment]
Alpha version implemented. @phwizard to test.

**Comment by dzinzyura** [comment]
To discuss in more detail the handling of failed requests to the Blockchain or API.
