### ISSUE TITLE
Web-client - Refer & Earn 

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#303]
**Goal:**
Introduce the logic for Referrals for the web-client

**Affected metric:**
- UI & UX enhancement
- Ease of control & operation

**Story:**
As a user, I open the web-client, click on menu and see "Referrals" option in the ACCOUNT subcategory. When I click on it, it opens the screen with explanation and my invitation code. When I click on "Enter code" I can enter an invitation code of my friend and receive coins.

**Description:**
Implement the "Referrals" screens as we have in the mobile app. 

**AC:**
1. Possibility to copy my invitation code
2. Possibility to enter someone's code
3. Successful receiving of coins after entering someone's code

![photo_2023-01-04_11-42-24](https://user-images.githubusercontent.com/99117374/210527205-76a4fcb0-1420-487f-be91-7a75654ff01e.jpg)
![photo_2023-01-04_11-42-23 (2)](https://user-images.githubusercontent.com/99117374/210527209-dc29b6b8-b213-4da8-a88a-ac2682424442.jpg)
![photo_2023-01-04_11-42-23](https://user-images.githubusercontent.com/99117374/210527214-67cc5588-1320-4eb4-8214-0c08b15ca5ed.jpg)

**Comment by dendidibe** [comment]
<img width="1438" alt="Снимок экрана 2023-01-04 в 13 43 58" src="https://user-images.githubusercontent.com/54039544/210548040-79156812-2026-4498-9f11-8fd0867fc773.png">

**Comment by dzinzyura** [comment]
looks great! can you, please, replace ETO here with our coin symbol? @dendidibe

**Comment by dendidibe** [comment]
<img width="1438" alt="Снимок экрана 2023-01-04 в 13 48 31" src="https://user-images.githubusercontent.com/54039544/210548745-eba477a7-819c-4921-825b-328116041508.png">

**Comment by dzinzyura** [comment]
awesome! thank you, Misha!
