### ISSUE TITLE
Chats backgrounds changing

### ISSUE THREAD

**Issue by dendidibe** [dappros/ethora#304]
Goal:
Introduce the logic for background changing for the web-client

Affected metric:

UI & UX enhancement
Ease of control & operation
Story:
As a user, I want to have the abillity to change the chats background.

Description:
Implement the "change background" screens as we have in the mobile app.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/210609752-0f7e51e5-8a8c-475a-bb61-dfebad8014bc.mov

**Comment by dzinzyura** [comment]
Great stuff! Thanks, Misha!

As you said, it's better to use only colors in the web-client, because images have low quality if we use them, so let's just add two more colors for chats and I think that will be enough.

Also, @ibnsan will check the issues with long "chat loading"
