### ISSUE TITLE
Web - client - Chat QR-codes

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#307]
**Goal:**
Introduce the possibility of sharing the chat room using QR-code or a specific link

**Affected metric:**
- UI & UX enhancement
- Ease of control & operation
- Ease of data handling

**Story:**
As a user, when I open a chat room, at the top right I can see a QR-code icon. When I click on it, it show me a window with room QR-code and it's link below.

**Description:**
Add QR-code and links logic for sharing the room as we already have in the app.

**AC:**
1. QR-code icon
2. Window with the QR-code and a link

![image](https://user-images.githubusercontent.com/99117374/210730357-82095af5-c406-4e2d-aea5-ccc530c1e8d2.png)
![image](https://user-images.githubusercontent.com/99117374/210761951-1e019e76-5aea-436d-af2c-1e6169564d24.png)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/210782637-2f746687-efff-4d31-8170-313d59f1787f.mov

**Comment by dzinzyura** [comment]
great stuff! thank you Misha!
