### ISSUE TITLE
Ethora Production update

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#314]
**Goal:**
Introduce the up-to-date production environment of the Ethora. 

**Description:**
Update Ethora Prod to the latest DP version.

**Comment by phwizard** [comment]
Only remain: web build items to do

**Comment by dzinzyura** [comment]
@dendidibe will prepare builds, but we need to create default rooms. the problems is: default chats there have empty names, this is because they were created manually by Taras.

@phwizard can you, please, create these rooms (Technical support, Random talks, NFT Factory) for prod version as you did for dev previously
