### ISSUE TITLE
Bots - BabelFish / Translate bot

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#316]
Experimental implementation to validate this feature via selected customer trials. 

Problem: different language users need to communicate in our chats (most often 1:1 communication, such as client and consultant)

Proposed solution: BabelFish bot that will translate the messages between 2 languages.

Proposed implementation:

1. Use Google Translate API or similar API for a demo translation service integration.
2. Set default languages as English and Spanish.
3. When added to chat, BabelFish bot listens to messages.  
4. When seeing a message in English, bot follows with a same message in Spanish
5. When seeing a message in Spanish, bot follows with a same message in English
6. When any user writes a message that includes "stop" + "translat" or "stop" + "babelfish" the bot should write "OK, I will stop translating now. Please write "start translate" or "start babelfish" for me to resume". 
Then it should stop writing translation messages until a user writes "start" + "translat" or "start" + "babelfish".7.

**Comment by dzinzyura** [comment]
Done. Thanks Anton!

*To discuss paid plans

https://user-images.githubusercontent.com/99117374/213680733-e44a9186-e3f2-45cd-a1d1-8f81de93446f.MOV
