### ISSUE TITLE
refactoring - screens into folders

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#372]
Please organize screens into folders as following:

<google-sheets-html-origin>

Origin | Folder
-- | --
AccountScreen | Account
Authentication | Account
ChangeBackgroundScreen | Chat
ChatDetailsScreen | Chat
ChatExperimental | Chat
ChatScreen | Chat
CoinPurchaseScreen | Account
DebugScreen | System
DocumentHistoryScreen | Profile
EnterInviteCodeScreen | Account
InviteFriendsScreen | Account
LoginScreen | Login
MintScreen | Actions
NewChatScreen | Chat
NftItemHistoryScreen | Profile
OtherUserProfileScreen | Profile
PrivacyAndDataScreen | Privacy
ProfileScreen | Profile
RegisterScreen | Login
RegularLoginScreen | Login
ResetPasswordScreen | Login
RoomListScreen | Chat
ScanScreen | Actions
ShareInviteLinkScreen | Account
SwiperChatScreen | Chat
ThreadScreen | Chat
TransactionsScreen | Profile
UploadDocumentsScreen | Actions

**Comment by phwizard** [comment]
UPD: I have changed for "PrivacyAndDataScreen" the destination to "Privacy" as you already have that folder, so it makes sense to go there, rather than Account.

**Comment by dzinzyura** [comment]
Done. Thank you, @dendidibe !

![image](https://user-images.githubusercontent.com/99117374/216267817-d69218ee-879f-4f1b-979b-19f92f7d711d.png)

[For review](https://github.com/dappros/ethora/tree/refactoring/client-reactnative/src/Screens)
