### ISSUE TITLE
Code refactoring - Mobile app

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#374]
**Goal:**
To review and refactor the Ethora code (mobile app).

**Affected metric:**
- Ease of data handling
- Improving the readability and usability of the code

**Description:**
Refactor the code, improving the usability and readability of the Ethora repository.

**Comment by dendidibe** [comment]
refactored stacks, transaction modal, profile screen, other user profile, all screens inside home stack to work with new types, api

**Comment by 4RGUS** [comment]
refactored the following:
1. ChatScreen, ThreadScreen refactor.
2. Chat store, chatDetailsHeader, refactor with typescript.
2. Chatlist, roomlist.

**Comment by dzinzyura** [comment]
Great stuff done! Thank you guys!
