### ISSUE TITLE
Push notifications redirecting issue

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#377]
**Goal:**
To review and fix the push notification redirecting issue.

**Affected metric:**
- UX enhancement
- Correcting logic operation

Story:
As a user, I receive a push notification (Android device) from a specific room. When I click on this notification, the Ethora app opens and redirects me to the chat room, from which I received a notification.

**Description:**
Fix the issue with redirecting to the specific room from the push notification.

**AC:**
1. Correct redirection to the room from the push

[Video with issue](https://dappros.slack.com/archives/C025G04FQV6/p1675352086904039?thread_ts=1675351584.014899&cid=C025G04FQV6)

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/216542905-3b2775b1-4b10-4458-ada8-0fe722638e14.mov

**Comment by dzinzyura** [comment]
Fixed. Thank you, @dendidibe !
