### ISSUE TITLE
Code refactoring - Web-client

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#378]
**Goal:**
To review and refactor the Ethora code (web-client).

**Affected metric:**
- Ease of data handling
- Improving the readability and usability of the code

**Description:**
Refactor the code, improving the usability and readability of the Ethora repository.

**Comment by dendidibe** [comment]
also refactored  xmpp https://github.com/dappros/ethora/commit/a408d7260ed5e2318da4cd72f5f723185878f134

**Comment by dzinzyura** [comment]
Done. Thank you, @dendidibe
