### ISSUE TITLE
"Create New App" - Web-client (temp. solution)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#381]
**Goal:**
To add "Create New App" feature for the web-client.

**Affected metric:**
- UI & UX enhancement
- Ease of control & operation
- Ease of data handling

**Description:**
Integrate the already existing UI as well as needed backend of the Owners page into the Ethora web-client.

@dendidibe add the "Create New App" button for the owners in the ID section between Privacy and Data and Logout buttons, which will redirect to the corresponding page.

**Comment by dendidibe** [comment]
<img width="1438" alt="Снимок экрана 2023-02-20 в 16 47 56" src="https://user-images.githubusercontent.com/54039544/220137908-790cd850-780d-48fe-b325-ca9769665736.png">

**Comment by dzinzyura** [comment]
@dendidibe discussed with Borys some points. decided to add some temporary changes for future Terms&Conditions etc. adjustments

1. Remove "Owner registration" button
2. Hide "Terms&Conditions" 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/99117374/220350634-8ce6dc57-9b6d-43a6-b939-b555f3a14cc6.png">

<img width="429" alt="image" src="https://user-images.githubusercontent.com/99117374/220350557-d0307b21-30d3-44b0-ac20-dc1779a6d27b.png">

**Comment by dzinzyura** [comment]
thank you, guys!
