### ISSUE TITLE
Smart link previews

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#382]
Currently links don't show any information except general information about our app. 

When you send our link in WhatsApp, Slack, Viber etc, you will see the same preview for each link. 

Ideally, links should indicate the type of content linked (Profile, Room, NFT collection or Document) and its title + preview.

<img width="360" alt="Screenshot 2023-02-24 at 15 36 18" src="https://user-images.githubusercontent.com/328787/221220178-df3d4472-ef37-4c8e-8a72-db61d9a73fae.png">

UPD requirements list:

When posted in another messenger (link preview mode): 
* show title correctly for the Resource (Resource can be a User Profile, Chat Room + can also be NFT item/collection, Document etc if/when supported)
* show Application name correctly depending on Application
* show Application Icon correctly depending on Application

Once opened:
(A) If opened by a web browser on a laptop / desktop computer:
* open the linked resource correctly in the Ethora web app or a 3rd party app based on Ethora engine (depending on security settings)

(B) if opened by a web browser on mobile devices WITHOUT our app installed
* show the preview page for the Resource (displaying Resource title, application name, icon)
* show Appstore download button so that user can download the corresponding app

(C) if opened on mobile devices WITH app installed
* open the relevant Resource within the app

**Comment by dzinzyura** [comment]
**Profile**
Title - ProfileName
Image - User profile Image (if it's set) / User initials (If not)
site_name - Ethora
Description - Tap to open the Ethora profile

**Room**
Title - RoomName
Image - Room Image (if it's set) / Room initials (If not) / or just an Ethora logo
site_name - Ethora
Description - Tap to open the Ethora room

**Comment by transkarpation** [comment]
@dzinzyura @phwizard "Image - User profile Image (if it's set) / User initials (If not)", If the user has no profile image, should we create an image with the user's initials, upload this image somewhere, and then send the image url as the image for the link preview? It will take many actions to display an image with the user's initials; we can be out of response timeout.
Let me know, please, should I implement user' image creation.

**Comment by phwizard** [comment]
@transkarpation - no need to create any images. Let's keep it simple for now, if no image then display no image. 

@dzinzyura what is the current status? shall we close this or still something pending?
can you post some examples of link previews here for Users and Rooms?

**Comment by phwizard** [comment]
Completed on the backend side, need to reflect forming the links correctly from client side.
