### ISSUE TITLE
Remove "Login with credentials" (client-side)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#383]
**Goal:**
Remove a possibility to register via username.

**Affected metric:**
- UI/UX enhancement
- Application security improvement
- Spam attacks prevention

**Description:**
Remove the possibility to login &/ create an account using usernames from the client side.

![C0165A5F-B993-43F4-A285-3A095347F9AF_1_201_a](https://user-images.githubusercontent.com/99117374/222129435-58ccade6-6b44-4f57-b24d-edb4912e5cf9.jpeg)
![89785ECE-7BA3-43AF-96F2-E6D5A90C5064_1_201_a](https://user-images.githubusercontent.com/99117374/222129463-9ffe926a-0c02-4d06-8ad3-b1ac3bf8ea69.jpeg)
![D10DA14B-64A6-4D48-B5C7-5AD393F5EB4D_1_201_a](https://user-images.githubusercontent.com/99117374/222129476-ce4e25a6-4854-4b4e-a7b4-50636edd1d65.jpeg)

**Comment by dzinzyura** [comment]
@dendidibe also, please, remove the button and related screens from the web-client

<img width="268" alt="image" src="https://user-images.githubusercontent.com/99117374/222139836-6a61a108-8f8f-4cb2-bed0-c1d7e81edcf0.png">

**Comment by dendidibe** [comment]
<img width="341" alt="Снимок экрана 2023-03-01 в 14 48 01" src="https://user-images.githubusercontent.com/54039544/222143673-84416c49-c54d-4d1d-ae18-6407db6bf681.png">
<img width="341" alt="Снимок экрана 2023-03-01 в 14 48 10" src="https://user-images.githubusercontent.com/54039544/222143700-5d9d8806-23ac-47c0-9269-99b540a93da2.png">
