### ISSUE TITLE
Remove "Login with credentials" (backend)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#384]
**Goal:**
Remove a possibility to register&login via username.

**Affected metric:**
- UI/UX enhancement
- Application security improvement
- Spam attacks prevention

**Description:**
Remove the possibility to login &/ create an account using usernames from the API.

https://github.com/dappros/ethora/issues/383

**Comment by phwizard** [comment]
@dzinzyura to close?

**Comment by dzinzyura** [comment]
done. thank you
