### ISSUE TITLE
"Login with E-mail" - mobile app

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#385]
**Goal:**
To replace the username sign-in with the e-mail.

**Affected metric:**
- UI/UX enhancement 
- Ease of data handling

**Story:**
As a user, when I open the app I can see different ways to sign-in into the app: SSO and Login with credentials.
When I choose the second way, it opens a specific screen with the registration/login fields. 

**Description:**
To replace username sign-in with e-mail as we already have on the web-client.

![image](https://user-images.githubusercontent.com/99117374/222143000-f83ee61e-64a9-41da-9548-859566c9b260.png)
![image](https://user-images.githubusercontent.com/99117374/222143011-2e82eaf0-0314-4825-a1ec-fc111745d565.png)
![image](https://user-images.githubusercontent.com/99117374/222143036-c432293f-0cfa-4aff-9592-1a654332e588.png)

**Comment by dendidibe** [comment]
<img width="814" alt="Снимок экрана 2023-03-01 в 14 53 24" src="https://user-images.githubusercontent.com/54039544/222144776-724084ac-c4ac-4bdb-b680-e8ccbfd5bb4f.png">
<img width="341" alt="Снимок экрана 2023-03-01 в 14 56 14" src="https://
<img width="341" alt="Снимок экрана 2023-03-01 в 14 56 23" src="https://user-images.githubusercontent.com/54039544/222145425-bf3ac4f6-5ea2-4f63-88fe-8edbccd50da1.png">
user-images.githubusercontent.com/54039544/222145402-3c32e098-c99e-4215-9b1f-bd63e3644383.png">

**Comment by dendidibe** [comment]
<img width="341" alt="Снимок экрана 2023-03-01 в 15 01 28" src="https://user-images.githubusercontent.com/54039544/222146545-3f778612-4297-43f2-9564-54b171339334.png">
