### ISSUE TITLE
"Forgot password" - web-client

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#387]
**Goal:**
To add "Forgot password" button for e-mail login.

**Affected metric:**
- UI/UX enhancement
- Ease of data handling

**Story:**
As a user, when I open the web-client and clicked on "Login with credentials", I can see the "Forgot password" button. When I click on it, it shows me a pop-up with a "The password reset email has been successfully sent. Please, check your email for further actions." message. When I open this e-mail, I can see the "Reset password" button, clicking on which I get redirected to the web-page, where I can change my password.

**Description:**
Add the "Forgot password" both the button and the related logic for the web-client.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/222180796-492febde-8734-452a-93fe-cb75442d4a09.mp4

**Comment by dendidibe** [comment]
need to change link that is sending to mail to this https://app-dev.ethora.com/resetPassword/[tokenForNewPassword]

**Comment by dzinzyura** [comment]
Done. Thanks guys
