### ISSUE TITLE
"Forgot password" - mobile app

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#388]
Goal:
To add "Forgot password" button for e-mail login (Login with credentials).

Affected metric:
- UI/UX enhancement
- Ease of data handling

Story:
As a user, when I open the web-client and clicked on "Login with credentials", I can see the "Forgot password" button. When I click on it, it shows me a pop-up with a "The password reset email has been successfully sent. Please, check your email for further actions." message. When I open this e-mail, I can see the "Reset password" button, clicking on which I get redirected to the web-page, where I can change my password.

Description:
Add the "Forgot password" both the button and the related logic for the web-client.

**Comment by dendidibe** [comment]
<img width="341" alt="Снимок экрана 2023-03-01 в 16 31 04" src="https://user-images.githubusercontent.com/54039544/222169945-5e43e1b8-622d-4ed7-96f4-a4fdc0c1fabe.png">
