### ISSUE TITLE
Link previews - web

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#391]
**Goal:**
Introduce the link previews logic, adding "Helmet" stuff for the web version.

**Affected metric:**
- UI/UX enhancement
- Ease of data representation
- Ease of data handling

**Description:**
Integrate the "React - Helmet" kit for the link previews display into the Ethora web.

_**Once opened:**_
(A) If opened by a web browser on a laptop / desktop computer:
* open the linked resource correctly in the Ethora web app or a 3rd party app based on Ethora engine (depending on security settings)

[Main task description](https://github.com/dappros/ethora/issues/382)

**Comment by dendidibe** [comment]
react-helmet cannot be used for link preview with react, need to consider to use current eto.li domain with prerendering neccessary information

**Comment by phwizard** [comment]
Remains to find solution for differentiating Dev and Prod clients.

**Comment by phwizard** [comment]
@dzinzyura status?

**Comment by phwizard** [comment]
Please update logic on the client-side to update link query. 

Delete "www." etc.

**Comment by phwizard** [comment]
Add "app=[application domain]"

**Comment by phwizard** [comment]
@dendidibe add appDomain into Config or some local storage param
