### ISSUE TITLE
Confirm e-mail - redirecting enhancement

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#392]
**Goal:**
To change the redirection for confirming the e-mail to app-dev.ethora.com.

**Affected metric:**
- UI/UX enhancement
- Ease of data handling

**Story:**
As a user, when I receive the email for confirmation, I click on the button and it opens the app-dev.ethora.com and I can see a pop-up with a successful result. Here, on this page I can login or if I use mobile app, I can close this tab and login via the mobile application.

**Description:**
Implement the following changes for both frontend and backend sides:

_Frontend_ (@dendidibe):
Share the corresponding link with Borys. Also add a following pop-up, when confirmation was successful: "Thank you! Your E-mail is now confirmed. You can proceed with logging in".

_Backend_ (@transkarpation):
Redirect users to the Ethora web-client instead of showing the API server rendered page.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/222779055-39c10968-c803-4117-9f83-79f28461528b.mov


https://user-images.githubusercontent.com/54039544/222779069-04aac1cb-9db6-4960-a22f-4d497afdb3f4.mov

added verify email page, but route /verifyEmail redirects to swagger.
new page path for ethora web app-dev.ethora/verifyEmail/token

**Comment by phwizard** [comment]
Need to update the link here to point to our new frontend @transkarpation

**Comment by dzinzyura** [comment]
works great, thank you guys
