### ISSUE TITLE
Message preview issue

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#394]
**Goal:**
To fix chat message display.

**Affected metric:**
- UI/UX enhancements

**Description:**
Fix the chat message, which is displayed in 2 rows instead of 1 (maybe it's displayed in such way due to "line breaks"). 

![IMG_5928](https://user-images.githubusercontent.com/99117374/230885152-2ad9bc54-bb7c-4c10-890d-f2b9e6cfe3fb.jpg)

**Comment by phwizard** [comment]
done, thank you
