### ISSUE TITLE
Profile - Transactions list issue

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#395]
**Goal:**
To fix the display of a Transactions list

**Affected metric:**
- UI/UX enhancements

**Description:**
Fix the Transactions list display in the Profile tab to the fullscreen instead of "cropped" version.

**Comment by dendidibe** [comment]
<img width="351" alt="Снимок экрана 2023-04-10 в 20 27 46" src="https://user-images.githubusercontent.com/54039544/230956865-c7e4fd11-2ad9-40e4-8e33-99f4cc4d49e5.png">

**Comment by phwizard** [comment]
please add padding to the right

**Comment by dendidibe** [comment]
<img width="348" alt="Снимок экрана 2023-04-26 в 09 14 30" src="https://user-images.githubusercontent.com/54039544/234485540-05b29b45-c6bf-42b1-a105-cdac09509255.png">

**Comment by phwizard** [comment]
thank you, closing
