### ISSUE TITLE
Admin - Users - actions

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#397]
Please implement the actions as before + add the following "reset password". 

This will call a modal confirmation:

"Are you sure you want to force a password reset for these **X** users? 
This will reset their passwords to a randomly generated ones and will send them an e-mail requiring them to set a new password".

Buttons: "Cancel" and "Reset passwords".

<img width="1123" alt="Screenshot 2023-04-19 at 09 54 35" src="https://user-images.githubusercontent.com/328787/233023003-03b07a3d-de85-4a53-b706-13fbc4c6b901.png">

**Comment by dendidibe** [comment]
@transkarpation need to add and modify existing api routes to work with users array

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/234841309-89893180-7ce5-493f-9e42-1fe26b8f305d.mp4

**Comment by phwizard** [comment]
@dendidibe this is good!

only problem I see here - you were able to add "test" tag twice

tags should be unique in their names, both backend and frontend shouldn't be adding a same tag or displaying same tag twice

cc: @transkarpation @dzinzyura

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/3f340fc0-8a7c-49d7-bfe3-db111d077e15

**Comment by phwizard** [comment]
Thank you - closing.
