### ISSUE TITLE
Web app - Menu Admin section fix 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#403]
Please rearrange this so that:

1) ID section is always in the bottom
2) 'Create new App' sits under "ADMIN" section

<img width="191" alt="Screenshot 2023-04-20 at 09 48 36" src="https://user-images.githubusercontent.com/328787/233312371-b937b838-4c42-47c5-9001-dea21a86689e.png">

**Comment by dendidibe** [comment]
<img width="411" alt="Снимок экрана 2023-04-20 в 11 55 26" src="https://user-images.githubusercontent.com/54039544/233314379-14aa9074-4949-44eb-a73b-ff6a72033d25.png">
