### ISSUE TITLE
Admin - Apps list - quick improvement

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#405]
<img width="1188" alt="Screenshot 2023-04-20 at 16 10 32" src="https://user-images.githubusercontent.com/328787/233409300-bd34170f-2ef5-440d-84ec-9ccd42a86178.png">

Please change column names accordingly:
Profiles Open
Assets Visible
Self-Sovereignty 

Also change true / false to emojis: ✅ and ❌

As discussed, it might be good to make the app name selectable (display it bold or display a "(selected)" text or ➡️ emoji next to it, so that we know which application content we are working with now.

**Comment by dendidibe** [comment]
@phwizard not sure if it will be good to make app selectable in apps table because we make users table depend from Apps table, in this case if in future we want to display users table separate from apps, we will not be able to do this
