### ISSUE TITLE
Users 'homeScreen' param

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#410]
Please add 'homeScreen' param for Users. This param can be set when creating a new User. This can also be changed by the application or User themselves. 

This param will be used by frontend to direct User to the screen which will be the default / home one after log in. 

For example, settings could be:

- 'chats' or empty - standard screen with the list of chats
- 'profile' - own profile screen of the User (this is more relevant for 'wallet' apps where focus is on user's own assets and profile)
- 'appCreate' - the screen under Admin section where a new App can be created - this will be used in case user signs up as a business (app owner) from pricing page, for example.

--

Please also set this to 'appCreate' when signing up users from the Pricing page. 
Same will be done for other 'owner' routes, for example after user has gone through server set up when using their self hosted / AWS marketplace version of Dappros Platform.

**Comment by transkarpation** [comment]
@dendidibe If client app sends signupPlan = free, server will add to newly created user model user.homeScreen = 'appCreate' propery. When user creates first application user.homeScreen will be set to '' (empty string)
https://app-dev0.dappros.com/api-docs/#/Users/post_v1_users_ https://app-dev0.dappros.com/api-docs2/#/Users/post_v1_users_sign_up_with_email

**Comment by phwizard** [comment]
done
