### ISSUE TITLE
Web client - aligning top nav header items

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#412]
See below - on wider screen the alignment breaks a bit.

Left side UI elements should be aligned to left edge, right side to right edge.

<img width="1892" alt="Screenshot 2023-05-08 at 12 04 10" src="https://user-images.githubusercontent.com/328787/236808055-c806282e-0581-4766-bf3b-ebf8215497f0.png">

**Comment by dendidibe** [comment]
<img width="1439" alt="Снимок экрана 2023-05-08 в 15 55 14" src="https://user-images.githubusercontent.com/54039544/236829633-42152002-bbe3-49b2-9f3f-7ce08be778a4.png">

**Comment by phwizard** [comment]
Thanks!
