### ISSUE TITLE
App settings - tabs

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#414]
**Goal:**
Introduce the possibility of making changes for a created app via “Settings” menu. 

**Affected metric:**
- UI/UX enhancements 
- Ease of data handling 

**Story:**
As a user, when the app is created, I can open the “Settings” menu and set up own app using the tabs: Appearance, User defaults, Services, Backend, E-mail templates

**Description:**
Implement the tabs in the “Settings” screen according to the description in the [spreadsheet ](https://docs.google.com/spreadsheets/d/13b5B2ss7021HwUu2oblzVgjcx9ns9r81dq_N76YB6Zw/edit#gid=1653135458)

**Comment by phwizard** [comment]
Done except e-mail templates. @dzinzyura please create ticket for templates.
