### ISSUE TITLE
Application name - make not unique

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#415]
Please make it so Application name doesn't have to be unique across the DP server. 
Applications should be distinguished by the system by their IDs, not by names.

This will allow users to change / modify Application name when they need.

I.e. it is more of a 'display name' and doesn't have any other function than appearance.

**Comment by phwizard** [comment]
@dzinzyura @transkarpation please close this if done

**Comment by dzinzyura** [comment]
done. thanks @transkarpation!
