### ISSUE TITLE
Admin - Apps - Appearance

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#416]
Here 

<img width="2105" alt="Screenshot 2023-05-11 at 15 59 19" src="https://github.com/dappros/ethora/assets/328787/ec84257e-fdb1-4eb5-a2e3-be6d36dfdf6e">

please make it more like in the mockup:

<img width="1187" alt="Screenshot 2023-05-11 at 16 02 52" src="https://github.com/dappros/ethora/assets/328787/f0512211-ad0d-4eb2-b6bd-577fef9b0d52">

* remove App title
* remove e-mail
* move "bundle ID" to "Mobile app" section
* create "Web app" section with subdomain / domain settings there

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-05-11 в 22 05 04" src="https://github.com/dappros/ethora/assets/54039544/5ca6cdf4-53fb-4f5c-b494-37f952a22863">
