### ISSUE TITLE
Admin - Apps - User defaults

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#417]
Here

<img width="1744" alt="Screenshot 2023-05-11 at 16 04 52" src="https://github.com/dappros/ethora/assets/328787/3b96dc2d-6643-4636-9f32-2bef20ea01e9">

Add description for "pinned" checkboxes same as in mockup:

<img width="1187" alt="Screenshot 2023-05-11 at 16 05 53" src="https://github.com/dappros/ethora/assets/328787/bef05a02-6712-4c6d-94bd-d25da9565a43">

```
Specify from 1 to 3 chat rooms your users will be subscribed to by default.

"Pinned" means users won't be able to remove them.

```

Add spacing before "Default profile security settings" header.

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-05-11 в 21 02 53" src="https://github.com/dappros/ethora/assets/54039544/0da2bec4-aa21-4278-a785-fbf82131e23f">
