### ISSUE TITLE
Admin - Apps - Backend

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#418]
Please remove "API" section here - not needed because system already knows this

<img width="1204" alt="Screenshot 2023-05-11 at 16 25 53" src="https://github.com/dappros/ethora/assets/328787/aebf2d82-63b3-4212-b156-a697d70bb50b">

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-05-11 в 20 58 27" src="https://github.com/dappros/ethora/assets/54039544/2cbd3d23-d61b-4746-b1ff-947f7c1f5889">
