### ISSUE TITLE
Admin - Apps - Appearance - Builder button

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#420]
Please implement the functionality accordingly:

<img width="1287" alt="Screenshot 2023-05-11 at 17 08 02" src="https://github.com/dappros/ethora/assets/328787/47402ea0-8824-420b-8916-abcecac6fddc">

<google-sheets-html-origin><style type="text/css"></style>

[ Prepare React Native build ] |   |   |   | state 1 - User clicks and build starts preparing |  
-- | -- | -- | -- | -- | --
[ Preparing React Native build, 02:05.. ] |   |   |   | state 2 - Server prepares the build, counter shows minutes and seconds elapsed |  
[ Download React Native build ] |   | expires in 20h 35min |   | state 3 - Build is ready. Button allows to donwload. Counter shows time remaining until deletion. |

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/97a53ba0-dcb8-49a6-9887-5bbfa419a9f0

added builder button, build preparring happens relatively fast, so maybe no need for counting timer, but i can add if needed

**Comment by phwizard** [comment]
@dendidibe is it possible to have colour picker UI here?

so user can either pick colour from the palette, or paste a hex code?

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/0a6fe1ec-1e70-4a56-bbd1-621f58206a4e

**Comment by phwizard** [comment]
Awesome!
