### ISSUE TITLE
Server Install app

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#421]
As discussed, this should be the web application that opens by default when user gets a new clean Dappros Platform image, for example from AWS Marketplace.

**Step 1** - Install App itself - ask the user for the important parameters to configure nginx etc:

<img width="883" alt="Screenshot 2023-05-15 at 08 31 05" src="https://github.com/dappros/ethora/assets/328787/494e3432-c3e3-4d08-886b-154c9316e94f">

**Step 2** - initialize core app and web app (Ethora web default app) and redirect user to login there

<img width="880" alt="Screenshot 2023-05-15 at 08 31 25" src="https://github.com/dappros/ethora/assets/328787/ee5c82f3-5129-4909-9928-d55e1c7a6bd2">

**Step 3** - implement "Server Config" screen endpoints on the backend + @dendidibe implements the front end. 
<img width="880" alt="Screenshot 2023-05-15 at 08 32 27" src="https://github.com/dappros/ethora/assets/328787/ef63063d-bac8-4806-8d36-27b87cea3ab8">

**ACL implementation**
This requires another ACL entry implemented, for example 'serverConfig'. Users who have Read access will be able to see 'Server Config' screen under "ADMIN" section of the menu. Users who have Write access will be able to modify (save changes) the server config params. Users who have Admin ACL record to serverConfig will be able to assign rights (modify ACL records) for serverConfig property for other users. 

**Users admin ACL implementation** 
The above ("Server Config") entry should also be added to Users ACL management UI. Only users with "A" (Admin) access - the ones we call super users - should be able to modify this property for other Users.

**Comment by phwizard** [comment]
after discussion decided to make Server Config read-only (or optional) 

and also update the 1st screen (Server Install) to include IPFS and Chat:

<img width="896" alt="Screenshot 2023-05-15 at 10 20 56" src="https://github.com/dappros/ethora/assets/328787/f95a757e-2275-41eb-b67d-88e2190e0904">

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/2dea455f-8766-4a2e-8ff0-afeaa29ebf1a

created separate project folder for this page

**Comment by phwizard** [comment]
@dendidibe please change "Api" to "API" otherwise you can close this

thanks!

**Comment by dendidibe** [comment]
<img width="1436" alt="Снимок экрана 2023-05-16 в 15 03 14" src="https://github.com/dappros/ethora/assets/54039544/428867d8-07f4-491c-8f63-36d2d27bb1ad">

**Comment by dzinzyura** [comment]
@transkarpation to connect the backend

**Comment by phwizard** [comment]
V1 is done.
