### ISSUE TITLE
Admin - Apps - settings - subdomain check

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#423]
1. User enters new “App display name”
2. Check if app already has domain name recorded in DB. If yes, then do nothing (exit this algorithm). 
3. If not, convert current “App display name” entry to lowercase + remove other characters that are not acceptable for domain names, and populate “Domain name” entry box with this name.
4. Keep “Domain name” editable by the user. 
5. Check if “Domain name” is in conflict with any existing name in DB for other apps or any service subdomains (for example, api.ethora.com and www.ethora.com are forbidden). If there is a conflict, display “:x: name not available, please fill in something more unique here” next to “Domain name” entry box. Don’t allow to save such entry. If there is no conflict, display “:white_check_mark: available” next to “Domain name” entry box and allow to save it. 

Messsages:
❌ name not available, please fill in something more unique here
✅ available

<img width="643" alt="Screenshot 2023-05-17 at 12 59 30" src="https://github.com/dappros/ethora/assets/328787/3958df4e-7979-4609-88ed-0a2337f5e81c">

**Comment by phwizard** [comment]
Notes:

1. Root domain is the same for everything. We ask admin to specify root domain during initial server install screen.
2. [api.rootdomain.com](http://api.rootdomain.com/) works for Dappros Platform API
3. [app.rootdomain.com](http://app.rootdomain.com/) works for default (Ethora) core web app
4. “www.“, “app.“, “ethora.“, “admin.“, “api.“, “chat.“, “ipfs.“, “rpc.” are reserved names and cannot be registered for app subdomains
5. App subdomains will work under rootdomain like this: “[appname.rootdomain.com](http://appname.rootdomain.com/)”.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/bb8b6783-78ff-4a87-860f-09dd3f30f830

**Comment by phwizard** [comment]
This works great!
