### ISSUE TITLE
Admin - Services tab - additional fields

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#425]
**Goal:**
Introduce additional fields for the Services tab data inputs.

**Affected metric:**
- UX enhancement
- Ease of data handling

**Description:**
For the builder we need two files, to attach google-services.json and GoogleService-Info.plist
For the web-version such fields should be added:

    REACT_APP_FIREBASE_API_KEY: String,
    REACT_APP_FIREBASE_AUTH_DOMAIN: String,
    REACT_APP_FIREBASE_PROJECT_ID: String,
    REACT_APP_FIREBASE_STORAGE_BUCKET: String,
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID: String,
    REACT_APP_FIREBASE_APP_ID: String,
    REACT_APP_FIREBASE_MEASURMENT_ID: String,
    
the fields themselves should be without values

**Comment by phwizard** [comment]
thank you
