### ISSUE TITLE
Admin - Appearance - improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#426]
1. Fix header typo “Appearence” should be “Appearance”
2. For Coin Name, have “Coin” there imputed by default. Add explanation “Name of your internal coin used for gamification and token economy. Leave “Coin” if unsure.”
3. Remove “Coin symbol” input.
4. For Login Screen Background option, add “OR Login Screen Color” with a colour picker. 
5. App logo upload - add helper text “Recommended size: 500px x 500px” under the button in small font. Also reflect the square aspect ratio in the preview on the right, so it’s not squeezed like in the example here.
6. Google Services JSON and Google Services PLIST - move to “Services” tab
7. Allow changing the Mobile App ‘bundle ID’. Add helper text “Bundle ID should be unique to identify your app for Appstore and other purposes”. Idea: use subdomain for the first proposed bundle id unless user changes it. For example, in the example shown it will be “com.myfirstapp001”
8. Move “Save” button to the bottom left so it’s neatly aligned. Also make it bigger or add spaces to show this button is more important than other buttons in this screen.

<img width="1516" alt="Screenshot 2023-05-26 at 12 29 34" src="https://github.com/dappros/ethora/assets/328787/03699b65-13ca-4aa5-b4ff-495230befb18">

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/88a71e1a-a76c-4aee-8c68-7d6803ed22cb

**Comment by dendidibe** [comment]
implemented fixes, except domain idea, because if domain not set it can be something like this 646f1504214d0120432269b8. @transkarpation need to change loginBackground on the backend to accept string colors along with files

**Comment by phwizard** [comment]
proposed:
loginBackground=file
loginBackgroundColor=colour

**Comment by phwizard** [comment]
This seems done.
