### ISSUE TITLE
Web - client - Transactions (Documents and Items display)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#430]
**Goal:**
Introduce a different UI for displaying Documents and Items on a Transactions page.

**Affected metric:**
- UI / UX enhancement

**Story:**
As a user, when I created a document or minted an item, I can see a specific information in Transactions section.

**Description:**
Change the UI for Documents and Mint Items on a Transactions tab:

1. Change coins icon on a documents & items one (e.g. [items](https://www.freepik.com/free-icon/notes_14354423.htm#page=3&query=item%20icon&position=5&from_view=search&track=location_fest_v1) , [docs](https://www.freepik.com/free-icon/google-forms_879618.htm#query=documents%20icon&position=2&from_view=search&track=location_fest_v1))
2. Change arrows to "uploading" icon (e.g. [uploading](https://www.freepik.com/free-icon/upload_15607505.htm#query=uploading%20icon&position=4&from_view=search&track=location_fest_v1))

**Comment by dendidibe** [comment]
<img width="1437" alt="Снимок экрана 2023-05-30 в 14 54 05" src="https://github.com/dappros/ethora/assets/54039544/2cad325a-8e26-4817-a10c-acc1bfbc03dd">
backend sends that the value of creation is 0

**Comment by dzinzyura** [comment]
@transkarpation can we somehow change the value of creation? e.g. I guess it should be 1 for the document

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-05-31 в 10 19 06" src="https://github.com/dappros/ethora/assets/54039544/36023b22-ea59-4515-a0c3-75d4c38ba848">

**Comment by dzinzyura** [comment]
thank you @dendidibe! looks great
