### ISSUE TITLE
Admin - Services tab - UI/UX enhancements 

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#431]
**Goal:**
Introduce an improved interface for the Services tab to enhance the user experience and improve the overall visual appeal.

**Affected metric:**
- UI / UX enhancement
- Ease of data handling

**Description:**
The current Services tab on Ethora website requires a UI/UX enhancement to provide a more engaging and user-friendly experience. The following improvements should be implemented according to [the mockup ](https://docs.google.com/presentation/d/1jEzGvEXc5IcYdUtBNUwXzK39yyzJqfNJuefbH3WFocU/edit#slide=id.g24a93bd0c98_0_12)

There should be 2 two "big" headers (h1/h2) - Google Sign-in & Push notifications. It should be represented as 1 screen: 
1) at first users see Google Sign-in settings
2) when users scroll down, they could see Push notifications part with specific fields/settings

Also it's important to explain either with images or paths somewhere in the modal popups _(if users click on (?))_ or in the fields on the right where they have to look for these settings in Firebase.

<img width="718" alt="image" src="https://github.com/dappros/ethora/assets/99117374/74892560-f87b-409f-aff9-e269050043c1">

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/c21bc452-47e4-42a5-8661-c3e2eb610eb3

**Comment by dzinzyura** [comment]
@phwizard Misha finished with tab improvements. Please, let us know if any changes are required.

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-06-09 в 10 12 21" src="https://github.com/dappros/ethora/assets/54039544/f260f463-2406-4824-8a27-d885e9ab51fc">

**Comment by dzinzyura** [comment]
thanks, @dendidibe!
