### ISSUE TITLE
PDFs preview bug

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#433]
**Goal:**
To fix PDFs previews representation and the possibility to send files to the chat.

**Description:**
Files cannot be sent due to the backend error 

`{
    "success": false,
    "error": "{\"stack\":\"Error: Could not execute GraphicsMagick/ImageMagick: gm \\\"convert\\\" \\\"-density\\\" \\\"100x100\\\" \\\"-quality\\\" \\\"75\\\" \\\"-[0]\\\" \\\"-resize\\\" \\\"956x1238!\\\" \\\"-compress\\\" \\\"jpeg\\\" \\\"/home/ubuntu/dapprosplatform/backend/dist/uploads/cfb07593cce65b6234a3e6559fe189fa_preview.1.png\\\" this most likely means the gm/convert binaries can't be found\\n    at ChildProcess.<anonymous> (/home/ubuntu/dapprosplatform/backend/node_modules/gm/lib/command.js:249:12)\\n    at ChildProcess.emit (node:events:513:28)\\n    at ChildProcess.emit (node:domain:489:12)\\n    at ChildProcess._handle.onexit (node:internal/child_process:289:12)\\n    at onErrorNT (node:internal/child_process:476:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\",\"message\":\"Could not execute GraphicsMagick/ImageMagick: gm \\\"convert\\\" \\\"-density\\\" \\\"100x100\\\" \\\"-quality\\\" \\\"75\\\" \\\"-[0]\\\" \\\"-resize\\\" \\\"956x1238!\\\" \\\"-compress\\\" \\\"jpeg\\\" \\\"/home/ubuntu/dapprosplatform/backend/dist/uploads/cfb07593cce65b6234a3e6559fe189fa_preview.1.png\\\" this most likely means the gm/convert binaries can't be found\"}"
}`

The problem may be related to the library that shows previews.

**Comment by transkarpation** [comment]
done
