### ISSUE TITLE
Web - client - Files preview

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#436]
**Goal:**
Introduce file previews for chats.

**Affected metric:**
- UI/UX enhancements

**Description:**
Add client-side files previews for messages. Use default icons/images for representation. 

**Here're the most used files:**

Video: AVI, MOV, MP4, WMV
Audio: MP3, WAV
Documents: DOC, DOCX, XLS,XLSX, PDF
Other: CSV, HTML, ZIP, XML

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/4d16c9cb-405d-423d-96b3-3f90f5c6c3ef

**Comment by dzinzyura** [comment]
great! thank you
