### ISSUE TITLE
Web - client - Direct messages bugs

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#437]
**Goal:**
Introduce a correct representation scenario for Direct messages.

**Affected metric:**
- UI/UX enhancement
- Ease of usage

**Description:**
Fix the following issues:
- Profile -> Direct message -> No chat title. The chat title is displayed once the message is sent there.
- If the Direct message is opened, display all 1 to 1 chats on the left-side menu

![image](https://github.com/dappros/ethora/assets/99117374/395953c0-f9a3-4a15-be2c-d936f2549378)
![image](https://github.com/dappros/ethora/assets/99117374/9669bd6b-8b56-463f-83bb-808e0ef62d17)

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/82577f11-abf4-484c-9d0e-05576eda5fce

**Comment by dzinzyura** [comment]
awesome! thank you @dendidibe
