### ISSUE TITLE
Web - client - Coins logic review

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#439]
**Goal:**
Introduce improved / fixed logic for coins transfer logic.

**Affected metric:**
- Ease of data handling
- Correctness of data operation

**Description:**
Evaluate the sending coin logic for potential issues, as there have been instances where it functions incorrectly: coins not being sent, absence of sent coin information in the chat, etc.

**Comment by phwizard** [comment]
Fixed

**Comment by phwizard** [comment]
This was in relation to attachments
