### ISSUE TITLE
Web - client - Last messages

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#440]
**Goal:**
Introduce a correct representation of last message on the left-side menu.

**Affected metric:**
- Data representation correctness

**Description:** 
Resolve the issue with the last message display and badge counter. Currently, when the page is reloaded, there is no indication of unread messages, and the last messages fail to appear sometimes.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/e6fa3cce-af1a-48fa-91e9-a2c3876cef37

**Comment by dzinzyura** [comment]
@dendidibe if the user refreshes the page, will the badge counter be displayed?

**Comment by dendidibe** [comment]
the counter stored only on the front end, we do not store this info on the xmpp. Also if we will open chat in the new tab from same account it will not make sense

**Comment by dzinzyura** [comment]
got it. thanks @dendidibe
