### ISSUE TITLE
Admin panel - Data sorting mechanism

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#441]
**Goal:**
Introduce the possibility to sort data on the Admin panel tab.

**Affected metric:**
- Ease of data handling
- UX enhancements

**Description:**
Implement the necessary logic to enable data sorting functionality on the Admin panel.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/13f985af-33ef-47a7-9e33-324b136b9d55
