### ISSUE TITLE
Login page - tooltip for account owners sign up

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#443]
Tooltip text:
"ℹ️ **Account Owners** 

In order to create and manage your App(s), you need to create your own account first. You can use one of your social accounts or create a new custom account using e-mail and password. 
"

This tooltip should be displayed when users are signing up as "Owners" 

for example
?signUpPlan=free

or other non-zero signUpPlan value

<img width="687" alt="Screenshot 2023-06-28 at 17 23 25" src="https://github.com/dappros/ethora/assets/328787/14f5206d-6443-4430-a3f2-e087f8c0a388">

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-06-28 в 22 15 44" src="https://github.com/dappros/ethora/assets/54039544/e41a612f-671a-409e-9cb6-811d4d8b825f">
