### ISSUE TITLE
Apps - Tooltip (permanent)

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#444]
This is a permanent (seen by everybody all the time) tooltip for Apps page. 

Text:
"
ℹ️ **Apps**
Here you can Create, Manage and View applications depending on your permissions. 
Create: use the green “+” icon.
Manage / View: click one of the available apps in the list. 

"

Better option would make it dismissable (so that user can click on "x" button in top right corner, for example, and it disappears)

![Uploading Screenshot 2023-06-28 at 17.27.46.png…]()

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/92c2d2c7-d47a-405e-ba8b-8140fd0fe846
