### ISSUE TITLE
Update Step By Step Guide

### ISSUE THREAD

**Issue by tab00** [dappros/ethora#446]
**Describe the bug**
When building for android, either on local computer or on Expo's infrastructure, error message appears:

> 1: Task failed with an exception.
> -----------
> * Where:
> Build file '/home/expo/workingdir/build/node_modules/react-native-audio-recorder-player/android/build.gradle' line: 23
> * What went wrong:
> A problem occurred evaluating project ':react-native-audio-recorder-player'.
> > Plugin with id 'kotlin-android' not found.
> 

**To Reproduce**
Locally in android directory: `yarn android`
Or using Expo Build: `eas build --platform android`

**Desktop:**
 - OS: CentOS8

**Smartphone:**
 - OS: Android

**Comment by dendidibe** [comment]
@tab00 can you please describe more detailed steps? are you running the latest code from main branch?
did you try to remove node_modules and gradle cache?

typical sequence for running the app, we are not using expo in this project
1. cd ethora
2. yarn install
3. npm run android

**Comment by tab00** [comment]
I just followed the steps in https://ethora.com/wiki/Step_By_Step_Guide

Here is a summary of my steps:

npx react-native init EthoraTest
cd EthoraTest
yarn
Copied "src" and "docs" folders in client-reactnative folder of Ethora project into EthoraTest
Replaced dependencies, devDependencies and jest from package.json of Ethora project to EthoraTest\package.json
In EthoraTest\index.js: replaced `import App from './App';` with `import App from './src/App';`
yarn
cd android
yarn android

**Comment by tab00** [comment]
Actually just after doing the steps I got the error

```
Package name not found in AndroidManifest.xml
```
but I was able to fix that by adding a package name.

**Comment by dendidibe** [comment]
because of you created entirely new project and moved src folder, there are no config for libraries that installed from node_modules in build.gradle and same for ios, if you go this path, then make sure that your configs are the same as in the original project

**Comment by tab00** [comment]
OK. The steps in https://ethora.com/wiki/Step_By_Step_Guide need to be fixed such that when they are followed exactly it works.

**Comment by dzinzyura** [comment]
thank you @tab00 for letting us know! We will make changes to the wiki page to avoid confusing users.

**Comment by tab00** [comment]
> We will make changes to the wiki page to avoid confusing users

Thank you. I've still been trying to get it working but have failed. So I'm looking forward to see new steps that work, as I'm very eager to try ethora.

**Comment by dendidibe** [comment]
You can try to m make ethora from our repo directly.

**Comment by tab00** [comment]
OK thanks, I've managed to run it straight from your repo.

I encountered other issues but will report them in separate new GitHub issues to leave this one about updating the guide.

**Comment by phwizard** [comment]
@tab00 thank you - please do ask questions / create issues as needed

@Egatlov let's update our wiki guide accordingly

**Comment by phwizard** [comment]
Note from NIkhil: app builder still refers to com.ethora in multiple places - need to update that with new bundle ID taken from UI
