### ISSUE TITLE
aws marketplace link?

### ISSUE THREAD

**Issue by seshubonam** [dappros/ethora#447]
**Is your feature request related to a problem? Please describe.**
checking out backend server options and couldnt find aws backend server in the marketplace for aws, which was mentioned in readme file.

**Describe the solution you'd like**
a link to access aws marketplace for ethora backend

thanks

**Comment by phwizard** [comment]
hi - thank you for raising this issue @seshubonam 

we are currently improving the self-install application to make it easier to use so we don't have it live in AWS to avoid confusing users with a 'development' version

if you're interested to try the current "development" version we can share it with you via Docker or AMI (Amazon Machine Image) 

if that's the case, please feel free to drop me an e-mail at taras AT dappros.com or book a call here https://calendly.com/taras-f and we will arrange the 'development' version for you 

alternatively if you prefer to wait for a stable version, ETA on that is 2 weeks, I will update the ticket here with a link alternatively leave some contact and we will let you know

thanks!
Taras

**Comment by seshubonam** [comment]
awesome thanks, will reach out in a few days after going through the react native version. already started development on that.. soon will understand in and out and can discuss scope in detail.. thanks for your swift response 🤗

**Comment by phwizard** [comment]
@seshubonam you're welcome 👍

are you building manually or using a web builder? 

with web builder you can change colours, logo, app name etc via this web interface (see below) and then download the RN build already with those changes 

also you get the web app (built in React.js) already working with those changes too (you can choose a subdomain there and we're working to add option so you can have your own custom 1st level domain, alternatively you can achieve that with self hosting)

<img width="1106" alt="Screenshot 2023-06-29 at 12 27 01" src="https://github.com/dappros/ethora/assets/328787/345dcdb9-8f9b-42c3-a588-14d6c2582c5e">

this interface is available when you log into web app -> ADMIN -> Apps

<img width="364" alt="Screenshot 2023-06-29 at 12 27 21" src="https://github.com/dappros/ethora/assets/328787/51512675-6515-41d7-a617-9f5ceb424394">

**Comment by phwizard** [comment]
for the web app:

https://ethora.ethoradev.com/signIn?signUpPlan=free

**Comment by seshubonam** [comment]
building with the react native version for android and ios

**Comment by seshubonam** [comment]
will be using mostly the same chat window but room list and insta stories like view will be added too in the mobile apps.

**Comment by seshubonam** [comment]
also not very sure of the ios app store prospects because of the coin system, damus was recently given a notice of removal for enabling tipping on ios app store. 
what are your thoughts on this. A solution would be to enable purchase of coins only through apple payment system may be.

**Comment by seshubonam** [comment]
> will be using mostly the same chat window but ui changes will be made in room list and insta stories like view will be added too in the mobile apps.

I'm hopeful this app we are building will be a nice showcase of whats possible with ethora as a platform for building web3/chat apps. will keep you posted on our progress and share the repo soon, for what we are building. right now, working on ui changes

**Comment by seshubonam** [comment]
for the react native version, how do we select the ethora hosted server

**Comment by phwizard** [comment]
regarding the Appstore, we've had our main demo app + some of the customers apps accepted into Apple Appstore without problems

we didn't focus on Coins as token economy however and we didn't offer any other ways to purchase the Coins, however I believe they don't do elaborate checks on that

also our Appstore app has in-app purchase

Apple has a policy that allows to sell NFTs when using In-app purchase, and they allowed our standard vanilla Ethora app into appstore where it allows to purchase Coins via in-app purchase

this is an interesting topic 

I'm not sure what happens when somebody has a popular app on Apple Appstore and they have Coins available for purchase both in-app and externally on the blockchain, I guess we will find out in the short term and hopefully Apple will embrace what can be achieved with web3 economy, otherwise alternative options will emerge such as going for web/Android and using decentralized app stores, Metamask marketplace etc

**Comment by phwizard** [comment]
> for the react native version, how do we select the ethora hosted server
> sign up for the web version and connect to server and use those credentials in the native app code?

yes you either sign up and create a build via the Builder UI, then credentials will be populated automatically

otherwise you sign up and take credentials from your App Settings screen

we have released the App builder and App Settings UI just recently so please report any issues / difficulties you experience and we'll be happy to help

**Comment by seshubonam** [comment]
> regarding the Appstore, we've had our main demo app + some of the customers apps accepted into Apple Appstore without problems
> 
> we didn't focus on Coins as token economy however (as we're not in a business to make a B2C project, for us it's just a demo app so that developers like you can test it) and we didn't offer any other ways to purchase the Coins, however I believe they don't do elaborate checks on that
> 
> also our Appstore app has in-app purchase
> 
> Apple has a policy that allows to sell NFTs when using In-app purchase, and they allowed our standard vanilla Ethora app into appstore where it allows to purchase Coins via in-app purchase
> 
> this is an interesting topic
> 
> I'm not sure what happens when somebody has a popular app on Apple Appstore and they have Coins available for purchase both in-app and externally on the blockchain, I guess we will find out in the short term and hopefully Apple will embrace what can be achieved with web3 economy, otherwise alternative options will emerge such as going for web/Android and using decentralized app stores, Metamask marketplace etc

thanks for the elaborate answer, saved some DYOR on this part.

**Comment by seshubonam** [comment]
> > for the react native version, how do we select the ethora hosted server
> > sign up for the web version and connect to server and use those credentials in the native app code?
> 
> yes you either sign up and create a build via the Builder UI, then credentials will be populated automatically
> 
> otherwise you sign up and take credentials from your App Settings screen
> 
> we have released the App builder and App Settings UI just recently so please report any issues / difficulties you experience and we'll be happy to help

perfect, thanks. looking forward for a call to discuss and show some progress on the app build.

**Comment by phwizard** [comment]
> perfect, thanks. looking forward for a call to discuss and show some progress on the app build, around monday mostly.

sounds good re the call, I'm UK based, not sure about yourself, happy to do calls early or late hours if needed

**Comment by seshubonam** [comment]
time zone noted, will book a working hour in UK time. thank you again!

**Comment by seshubonam** [comment]
Hi, we had some delay on the development on ethora so would need more time to arrange a call with you. delay on the developer side, not ethora. Once thats sorted, will have more things to discuss and can have a meaningful conversation. thanks!

**Comment by seshubonam** [comment]
> hi - thank you for raising this issue @seshubonam 
> 
> we are currently improving the self-install application to make it easier to use so we don't have it live in AWS to avoid confusing users with a 'development' version
> 
> if you're interested to try the current "development" version we can share it with you via Docker or AMI (Amazon Machine Image) 
> 
> if that's the case, please feel free to drop me an e-mail at taras AT dappros.com or book a call here https://calendly.com/taras-f and we will arrange the 'development' version for you 
> 
> alternatively if you prefer to wait for a stable version, ETA on that is 2 weeks, I will update the ticket here with a link alternatively leave some contact and we will let you know
> 
> thanks!
> Taras

recently posted a question regarding docker image for backend. was told only api is currently available. is a self host through aws in roadmap? 

we dont have a specific preference. but to know about options for backend.

**Comment by phwizard** [comment]
@seshubonam 

hi yes let me clarify this 

we have created an experimental AWS marketplace and Docker version last month, but there are a number of server-side improvements going on right now so it makes sense to push back the public version a little bit down the line. We also work on improving our API and messaging protocol documentation to make it all easier for 3rd party developers to work with the server on their own.

It is most likely we will release the Docker and/or AWS self-host version during September, and if you need your own self-hosted version before we release the public one, we can do a 'closed beta' with you where we will share it with you manually and you could provide us with feedback.

**Comment by seshubonam** [comment]
thanks for the update. the api is useful for extending the chatroom functionality to outside the chatroom components. working on integrating that this week. 

and posted this video in a recent issue also. sharing it here as an update to you: 
https://github.com/dappros/ethora/assets/1757478/68d16c41-765b-4bde-aa8c-ff3cb3137b60

**Comment by seshubonam** [comment]
about our app:

 a voice chat app that takes user posted voice notes and converts to ai generated videos with avatars/scenes related to the voice note. this app enables a creative way of sharing opinions with friends and followers.


in the attached video, the user flow is as follows:

the home screen shows a list of rooms with tiles. each tile is a voice note or a video note posted to the respective room. 2. upon clicking any tile a story component like instagram stories is played, which houses the voice-note/video(media) posted by a member of the room.

users can click the "mic" button on left side of each room in home screen to post media to the room.

for further text chat, a "message" icon can be clicked which directs user to the regular ethora chat room with a slightly modified ui that shows the story tiles at the top of the screen.
