### ISSUE TITLE
In web builder: CORS error after preparing react native build

### ISSUE THREAD

**Issue by tab00** [dappros/ethora#452]
**Describe the bug**
When editing an App in the web builder and pressing "PREPARE REACT NATIVE BUILD", 
"Something went wrong" popup notification appears.

In the browser console the following appear:
> XHR POST https://api.ethoradev.com/v1/mobile/src-builder/... CORS Missing Allow Origin

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.ethoradev.com/v1/mobile/src-builder/.... (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.

**To Reproduce**
Sign into [ethora.ethoradev.com](https://ethora.ethoradev.com)
View list of Apps
Edit App
Press "PREPARE REACT NATIVE BUILD"
View browser console
Wait for build to finish
See "Something went wrong" popup appear on the UI
See CORS error messages appear in the console

**Expected behavior**
No errors, and react native build available to download.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 114.0.2, Chrome 108.0.5359.125

**Comment by dzinzyura** [comment]
Hi, @tab00!

Thank you for taking the time to report the bug you encountered. Your contribution is invaluable to us, and we greatly appreciate your effort in helping us improve our product!

The development team has already begun investigating the bug based on the information you provided. Rest assured that we are actively working on finding a solution and implementing the necessary fixes.

**Comment by phwizard** [comment]
@tab00 thank you for reporting this issue

we were able to reproduce this and will fix this bug 

our lead server developer is on vacation this week so it could be until the next week when it's fixed 

if you need it earlier than that we can arrange a session with our React Native developer to help you prepare a customized build manually, please let me know if you'd like that

**Comment by phwizard** [comment]
@tab00 this has been fixed - please try again, I have tested and it works for me now:

<img width="891" alt="Screenshot 2023-07-06 at 14 40 17" src="https://github.com/dappros/ethora/assets/328787/b759d6e4-731a-416d-801d-c2c2fd8051d1">

**Comment by tab00** [comment]
It works now. Thank you @phwizard.

**Comment by phwizard** [comment]
great, let us know if you experience any other issues
