### ISSUE TITLE
In mobile app, Create account: "Someone already has that username"

### ISSUE THREAD

**Issue by tab00** [dappros/ethora#454]
**Describe the bug**
When creating an account in ethora mobile app that is run from cloned repo, the error "Someone already has that username" pops up, even if it's an email address that has never been used before to sign up.

Then when using the same email address and password to try to sign in, the error message "Something went wrong" pops up.

**To Reproduce**
Clone [ethora](https://github.com/dappros/ethora) repo
run app in client-reactnative
Wait for app to load on device
Press "Login with credentials"
Press "Create new account"
Enter email address etc.
Press "Create"
See popup error message "Someone already has that username".

**Expected behavior**
Successful sign-up and able to sign in.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Redmi 10
 - OS: Android 12

**Comment by dzinzyura** [comment]
Thanks @tab00 ! We'll try to reproduce the bug and fix it as soon as possible. 

The team is working on it.

**Comment by dzinzyura** [comment]
Hi, @tab00 !

Hope this message finds you well.

Thanks for letting us know about the bug. We've already fixed it and merged a new version to the "main" branch, so you can use the latest one with the issue resolved.

We appreciate your help in making our product better!

**Comment by phwizard** [comment]
@tab00 could you please close this issue if this works fine for you now?

**Comment by tab00** [comment]
I see warning message "Can't perform a React state update on an unmounted component."

But at least it's working now. Thanks guys.
