### ISSUE TITLE
Web - Apps - Select all users

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#455]
<img width="1073" alt="Screenshot 2023-07-06 at 09 09 45" src="https://github.com/dappros/ethora/assets/328787/89ae1631-0bfc-4b6a-89e7-dae4842d6ea6">

Here when we show in the bottom how many users are selected, please add an option to select all users across all pages:

[ Select all **X** users in **Y** pages ]

<img width="938" alt="Screenshot 2023-07-06 at 09 14 49" src="https://github.com/dappros/ethora/assets/328787/3d8c326a-679f-49b2-a016-a74705e65c21">

**Comment by dendidibe** [comment]
@phwizard because of we are using pagination we can only select all users if we fetched them, we fetch only first page initially. We have limitation to fetch only 50 (max) users i this at a time and because because i dont have all users fetched i cant select them all

**Comment by phwizard** [comment]
This isn't compatible with pagination, decided not to implement this for now.
