### ISSUE TITLE
Web - Apps - Add tag - "something went wrong" but it worked

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#456]
**Describe the bug**
"Something went wrong" shown in the bottom left when trying to add tag to multiple users.

**To Reproduce**
1. Go to Apps -> Users
2. Select multiple users
3. Add tag (I added "dappros" to our team users)
5. Users list becomes empty, but some accounts still selected
6. After adding / removing checkbox selection and reloading, the page shows with tags applied correctly.

**Expected behavior**
1. No error
2. Page refreshes with tags applied correctly. 

**Note**
Unfortunately, I wasn't able to reproduce this on 2nd try. Try reproducing it, if you can't then you can close this.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/5eaea6b0-9ca1-4247-a6a2-a3df53c1848d

tried to reproduce, for me it worked, maybe was some backend error

**Comment by dzinzyura** [comment]
We need @transkarpation help to fix this issue.

The backend doesn't return the updated data of users for whom we've made changes.

@phwizard

**Comment by phwizard** [comment]
Fixed now (due to pages issue)
