### ISSUE TITLE
Web - Apps - Users and Tags management improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#457]
These functions around Users management are very important because App Owners will be looking at their Users table and working with it quite a lot, for every app their users are important. 

Issues / notes that I have with it - below:
(also see if you can spot any other issues or suggest other improvements if applicable)

- Selection of users seems fiddly. Try selecting some users, adding some tags, removing selection etc. Sometimes it feels like I do some action like adding tags, but selection gets applied to more users after the action etc. Also I added an issue to add “select all”  option: https://github.com/dappros/ethora/issues/455
- I had a problem with adding a tag to multiple users. But I couldn’t reproduce it easily. https://github.com/dappros/ethora/issues/456 Try playing with adding/removing tags using
- I want to select a bunch of users on my browser screen and copy & paste it into a Google spreadsheet. Sometimes it works and inserts as a table, sometimes it inserts as a list into one cell. Would be good to make it easier to copy & paste. This isn’t a big deal but will improve UX if something can be done here.
- Tags - I think “Add Tag”, “Remove All Tags”, “Remove Tag” is too many buttons in the bottom menu for a selection of users. Instead, I would just have one button “Manage Tags”. Show a modal window and show all tags that apply to selected users. To inform better, you can display a counter next to each tag (how many times this tag repeats across the selected users) or show fully those tags that are present across all selected users, and semi-transparent those tags that are present only across some (not all) of the selected users. When admin user adds tag(s) there, show that tag in the input window and when “Save” is clicked, update (add) it for all selected users. If admin user removes some tag(s) and clicks Save, then remove it for all selected users. This way we’ll have one button and one UI for add, remove all and remove one. You can check how tags management works in other products. It would be nice if once admin user adds a keyword, it appears as a rounded tag and tags get assigned different colours automatically (permanently based on a hash of their name or something like that).
- Rename “User Tags” column to “Tags”
- We will need to add “EXPORT” button for selected users too (same bottom bar where Tags, Reset Passwords and Delete buttons are). We already have CSV export function as far as I know, I guess Misha can add the button and connect it once Borys is back.
- Sorting still doesn’t seem to work 100% correctly. Is this a backend question? I want to see all users in the order how they have registered, for example, but it doesn’t seem to be doing exactly that.

**Comment by dzinzyura** [comment]
Additional tasks:

1. I suggest to change colors for tags menu (where we have "cancel" "submit" buttons) on **red for Cancel** and **blue for Submit**
2. Change text in the Auth method column on icons (email icons, facebook, gmail)
3. Change text in Auth method on icons (E-mail/Facebook/Google) 
4. Text: Edit **ACL**
5. Reset Passwords -> **Reset Password**

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/d8570c14-73f4-43d6-8531-ef4dcb595dfc

for copying just need to select entire table, in that case it will work

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/2da3bb93-e9f6-4dc4-9e1d-641ae4147930
