### ISSUE TITLE
App - DMs not available

### ISSUE THREAD

**Issue by quavo19** [dappros/ethora#458]
**Is your feature request related to a problem? Please describe.**
I'm working with the react native version and I've realised there's no feature to dm someone. just room chats. 

**Describe the solution you'd like**
Maybe you could help me locate the function to make DMs visible to users on the home page. or add it if its not available for app.

**Comment by phwizard** [comment]
@quavo19 hi Donald, DMs are normally available from user's profile and also via long tap menu when you long tap someone's message. Our team will get in touch to clarify details with you.

**Comment by dzinzyura** [comment]
Hello, @quavo19 !

We greatly appreciate your willingness to assist us in improving our product! 

To better understand and address the problem, we kindly request you to provide us with more details regarding the issue you faced.

Please let us know which version of the app you are using: App Store/Play store or GitHub? Also, as mentioned above, DM can be accessed by long tap on users' messages or through the user's profile.

The more details you can provide, the better equipped we will be to investigate and resolve the problem promptly. We genuinely appreciate your cooperation and your commitment to helping us improve our product.

Thank you once again, and we look forward to receiving the requested information.

Best regards,
Ethora team

**Comment by quavo19** [comment]
> @quavo19 hi Donald, DMs are normally available from user's profile and also via long tap menu when you long tap someone's message. Our team will get in touch to clarify details with you.

thank you very much.

**Comment by quavo19** [comment]
> Hello, @quavo19 !
> 
> We greatly appreciate your willingness to assist us in improving our product!
> 
> To better understand and address the problem, we kindly request you to provide us with more details regarding the issue you faced.
> 
> Please let us know which version of the app you are using: App Store/Play store or GitHub? Also, as mentioned above, DM can be accessed by long tap on users' messages or through the user's profile.
> 
> The more details you can provide, the better equipped we will be to investigate and resolve the problem promptly. We genuinely appreciate your cooperation and your commitment to helping us improve our product.
> 
> Thank you once again, and we look forward to receiving the requested information.
> 
> Best regards, Ethora team

im working with is as a developer, so I'm running the react native version of it on my iOS emulator.

**Comment by phwizard** [comment]
@quavo19 good luck with your build efforts and feel free to ask questions here or on Discord

we're happy to take UX feedback too so if you think your users will benefit from some other ways to DM each other we can take that into account
