### ISSUE TITLE
Change Background for chat not working 

### ISSUE THREAD

**Issue by quavo19** [dappros/ethora#459]
**Describe the bug**
the function to change background colour/image of a chat window is not working

**To Reproduce**
1. Click on any room
2. Click on the blue header containing the name of the chat room
3. click on the hamburger Button at the top right and select 'change background'
4. select your desired background
5. Now go back to the chat window and the chat background will still be the same 

**Expected behavior**
For background to change to the selected background

**Screenshots**
Selecting a background
<img width="850" alt="Screenshot 2023-07-06 at 9 02 31 AM" src="https://github.com/dappros/ethora/assets/87555548/b96324a0-a2af-4243-8f92-fafe93fdf71c">
Background remains the same
<img width="320" alt="Screenshot 2023-07-06 at 9 03 04 AM" src="https://github.com/dappros/ethora/assets/87555548/3534549d-23f8-4d93-adc8-a5a6e96e250d">

**Desktop (please complete the following information):**
 - OS: IOS

**Smartphone (please complete the following information):**
 - Device: Emulator(14 Pro Max)
 - OS: iOS 16

**Additional context**
Also I've been getting this same error all the time. thought its related to internet connection but its not.
<img width="519" alt="Screenshot 2023-07-06 at 9 15 36 AM" src="https://github.com/dappros/ethora/assets/87555548/28099944-30b8-4fe1-8b18-f1d08e4184ea">

**Comment by phwizard** [comment]
@quavo19 looks like a problem with Chat server connection. Either it has blocked your user or a server-side issue on our side. We will investigate and get back to you.

**Comment by dzinzyura** [comment]
@quavo19 could you please provide us this information so that we can help you as quickly as possible:

- JID
- IP
- Time

**Comment by phwizard** [comment]
@quavo19 hi Donald, do you have any updates? Does this issue persist? We need to check if it's internet connection related.
