### ISSUE TITLE
Web - Apps - Users list bug

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#460]
**Describe the bug**
The backend gives us only 50 users (maximum). if you go further down the list, for example, to 61-70 and make any changes, the users will disappear (empty list)

**To Reproduce**
1. Go to Apps -> Users
2. Scroll through the list of users until the number exceeds 50
3. Choose random user and add/remove tags
4. Submit changes
5. Users list is empty

**Expected behavior**
Backend gives more than 50 users. When the changes are made, the list is not empty

**Video**

https://dappros.slack.com/archives/C025G04FQV6/p1688638568951529?thread_ts=1688637546.523499&cid=C025G04FQV6

**Comment by phwizard** [comment]
Updates so that selection applies to 1 page only.
