### ISSUE TITLE
change "client-reactnative/src/Screens"  to "client-reactnative/src/screens"

### ISSUE THREAD

**Issue by TrueMatrixPower** [dappros/ethora#461]
**Describe the bug**
change "client-reactnative/src/Screens"  to "client-reactnative/src/screens"

because in AuthStack.tsx:
import {RegisterScreen} from '../screens/Login/RegisterScreen';
import {RegularLoginScreen} from '../screens/Login/RegularLoginScreen';
import {ResetPasswordScreen} from '../screens/Login/ResetPasswordScreen';

**Comment by phwizard** [comment]
thank you - we will look into this shortly

**Comment by dzinzyura** [comment]
Hi, @TrueMatrixPower !

Thank you for bringing this issue to our attention. We have promptly addressed it, and a fixed version is now available for usage. 

We value your contribution in improving our product, so please don't hesitate to inform us of any further issues you may encounter. Your feedback is highly appreciated!

Please, close this ticket if the problem hasn't recurred.

Best regards,
Ethora team
