### ISSUE TITLE
Web - Apps - Users list export

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#462]
**Goal:**
Introduce a possibility to export users from the list by using a specific "Export" button.

**Affected metric:**
- UX enhancements
- Ease of data handling

**Story:**
As an app owner, I go to Apps section - Users and under the list I can see the "Export" data. I click on it and the CSV file with data downloads on my device.

**Description:** 
Implement a possibility to export users list via CSV file using "Export" button in the Apps tab.

**Comment by transkarpation** [comment]
@dendidibe 
https://api.ethoradev.com/api-docs/#/Users/get_v1_users_export__appId_

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/1118bf7c-8a0b-4a64-a611-808e797916b7

**Comment by dzinzyura** [comment]
awesome! thank you guys @transkarpation @dendidibe
