### ISSUE TITLE
Web - Apps - Users selection

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#463]
**Goal:**
Limit the selection to one page only.

**Affected metric:**
- UX enhancements
- Ease and correctness of data handling

**Description:**
Implement the limit for selection to one page in the Apps - Users tab

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/10a27cb3-9aab-4a34-aa65-ae91f4f70f6e

**Comment by dzinzyura** [comment]
great stuff! thanks @dendidibe !
