### ISSUE TITLE
unable to add expo to ethora client-reactnative

### ISSUE THREAD

**Issue by quavo19** [dappros/ethora#464]
**Describe the bug**
unable to add expo to ethora client-reactnative
**To Reproduce**

1. npx install-expo-modules@latest (will automatically pod install)
2. run any build command eg`npx react-native run-ios --simulator="iPhone 14 Pro Max"`
3. APP WILL FAIL TO BUILD

>  SwiftEmitModule normal x86_64 Emitting\ module\ for\ EXAV (in target 'EXAV' from project 'Pods')
(1 failure)

**Expected behavior**
For project to build ios app with expo components working  

**Desktop (please complete the following information):**
 - OS: Im runing the reactnative version of the project in my android emulator

**Comment by dzinzyura** [comment]
Hello, @quavo19 !

Thank you for your bug report. We appreciate your contribution and effort in helping us improve our product! 

Our team has reviewed your request and we would like to inform you that we do not support Expo in our product. Expo is a separate ecosystem and although there may be some guides available on the internet, implementing them may not guarantee a fully functional solution. 

To make it work, you'll need to initially write the app with Expo. However, please note that this may result in the loss of React Native modules.

Please, let us know if there is anything else we can assist you with.

Best wishes,
Ethora team

**Comment by quavo19** [comment]
@dzinzyura Please is it just ethora alone or all react native projects. im asking because there are [documentations](https://docs.expo.dev/bare/installing-expo-modules/) to add expo to a react-native project and some seem to work fine.

**Comment by quavo19** [comment]
@dzinzyura well understood, thank you.

**Comment by dzinzyura** [comment]
@quavo19 as I mentioned previously, we cannot guarantee specific results as we haven't tested this particular scenario. However, you can find guides or documentation to perform the necessary actions and accomplish your goal. 

If you have any additional questions or require further assistance, please don't hesitate to contact us. We are here to help!

**Comment by quavo19** [comment]
@dzinzyura sure, well understood. thank you
