### ISSUE TITLE
Metamask login update

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#465]
**Goal:**
Introduce the updated logic for Metamask login.

**Affected metric:**
- UX enhancements
- Ease of data handling

**Description:**
Update the Metamask login according to the revamped SDK for React Native.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/2488c48b-7a93-4eb3-8098-b5ba3396566e

updated metamask login, will fix minor issues like name "test"

**Comment by dzinzyura** [comment]
great stuff! thanks @dendidibe !
