### ISSUE TITLE
Web - Apps - app selected

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#466]
Clicking on the app name in the table should automatically select it in the bottom drop-down after "Users"

<img width="1244" alt="Screenshot 2023-07-18 at 09 10 29" src="https://github.com/dappros/ethora/assets/328787/86f52579-0962-4ee3-b0fb-fd6ffde487f7">

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/54d0a385-83b8-4ab6-b63c-cd2ea5316fa9

**Comment by phwizard** [comment]
Purrfect
