### ISSUE TITLE
Stats engine update - tracking vital stats in by-app context

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#469]
As discussed earlier, please update / implement the stats logic so that we can track the following statistics:

Users registrations

- Users sign ons (login sessions)
- API calls
- Blockchain (Web3) transactions
 
with App attribution and timestamps.

From the architecture and high-load point of view, it is likely going to be better if Stats for the core/API app is implemented as a separate service. I.e. it writes into its own separate DB (could be MongoDB but a column-based NoSQL DB such as Cassandra may be a faster working choice here) and its API also works as a separate application so it:
1) Doesn't affect the performance of the main core API/app
2) Can be moved to a separate server instance when needed. 
3) In future can have its own performance optimizations such for example as pre-calculation and caching of popular requests at DB level such as daily stats, monthly stats etc. 

The above (implementing it as a separate service with its own DB) is a recommendation but is not critical at this stage. 

Also note that we will likely need future developments around this service that are important for the platform. I.e.
1) Daily stats e-mail feature - our Customers (app owners) will receive an e-mail every 24h showing them how many Users, API calls, Chats, Push notifications etc have been generated by their apps over last 24h, and similarly we can do a monthly summary e-mail. 
2) Billing and Throttling - Stats service may be used by the core application to check whether the Customer (app owner) has a right to consume this much resources during this month, according to the Plan they are on (or alternatively to bill them Platform Tokens on a pay-as-you-go basis). 

Currently we need an implementation that allows in our Apps UI to display the vital stats like this over the last 24h:

<img width="1245" alt="Screenshot 2023-07-20 at 07 40 32" src="https://github.com/dappros/ethora/assets/328787/40db28d4-64ea-44a5-a4df-64597684bec6">

and also detailed stats with graphs / diagrams of usage over Hour, Day, Month for any specific Application and any specific Metric.

**Comment by phwizard** [comment]
After this is updated on the server-side, we will implement this Apps list view update, and after this we will implement the detailed stats interface.

Detailed Stats interface will be opened via Stats icon on the right.

It will be similar to how it was before (below) in the previous version, but the stats will be:

- Users
- Sessions 
- API 
- Chats (when available)
- Push Notifications (when available)
- Web3 (former Blockchain Transactions)

<img width="819" alt="Screenshot 2023-07-20 at 10 55 38" src="https://github.com/dappros/ethora/assets/328787/638ce316-7bc5-449f-97e8-b22575ff47b7">

**Comment by phwizard** [comment]
Головні нюанси
* Статистика потрібна в контексті аплікейшенів, щоб ми могли показувать реєстрації юзерів, активність (sessions) та інше для кожного App/проекту окремо.
* Зараз все одно, але в майбутньому нам може допомогти якщо Stats буде окремим сервісом зі своєю базою данних. Щоб воно не вантажило головний API/core app. Потрібно подумати як зробити щоб запис статистики (це головне) не дуже навантажував систему або був окремим серісом. Тобто на запис потрібно щось швидке, що не чекає там довго відповіді типу записалося чи не записалося. Це може бути окремий node.js app, що має свою базу даних. Це може бути запис до бази даних що дуже швидка на запис (така як Cassandra) або це може бути запис до Redis / Kafka / RabbitMQ / Memcached. Знов таки, краще зробити як простіше ніж ніяк, але якщо можна зробити так щоб було потім легше з high load, то задача с зірочкою.

**Comment by phwizard** [comment]
Transactions doesn't work in MongoDB on single (same instance) set up.
Will likely have to move to a cluster MongoDB with a replica set.

**Comment by phwizard** [comment]
Updated - added "Files"

<img width="1595" alt="Screenshot 2023-07-27 at 14 54 34" src="https://github.com/dappros/ethora/assets/328787/11df27fc-9389-44f0-b056-64e55f0e1a7a">

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-08-16 в 09 16 50" src="https://github.com/dappros/ethora/assets/54039544/78b0744a-12c6-4d62-a526-31d4c35ec687">

**Comment by dzinzyura** [comment]
done. thanks @dendidibe
