### ISSUE TITLE
Users API - clientType or clientFirst attribution param

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#470]
**Is your feature request related to a problem? Please describe.**
App owners can't attribute where the end users registrations are coming from (mobile, web app etc).
With attribution it would help them manage better their product and marketing strategy across iOS, Android and Web presence. 

**Describe the solution you'd like**
I propose to add a "clientType" (alternatively: "clientFirst") param for the registration method of Users API. 
This will be provided either
(a) explicitly by the client app
OR
(b) automatically collected from User-Agent 

I guess (b) is better as clients don't need to add changes on their side, but both options are OK. 

Then when retrieving a list of Users, the clientType should be returned as well which will allow us to display the attribution of what kind of app user has used for their first registration with the system. 

**Describe alternatives you've considered**

N/A

**Additional context**

Once this is added, we will add client type attribution in the Apps -> Users section like this:

<img width="1220" alt="Screenshot 2023-07-20 at 12 41 27" src="https://github.com/dappros/ethora/assets/328787/ad719faf-21be-4e44-85e3-6289b434c21b">

**Comment by phwizard** [comment]
from Borys:

> Гадаю що надійніше буде використать той підхід що ти пропонував, тіки записувати тип платформи в заголовки а не в тіло запиту, наприклад заголовок x-device-type=[android, ios]

so yes, let's add the headers into our API requests:
x-device-type=[android, ios, web]

(or maybe use REFERRER header for Web version)

**Comment by dendidibe** [comment]
request headers, added x-device-type 
 LOG  {"Accept-Encoding": "gzip, deflate, br", "Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlzVXNlckRhdGFFbmNyeXB0ZWQiOmZhbHNlLCJwYXJlbnRBcHBJZCI6bnVsbCwiaXNBbGxvd2VkTmV3QXBwQ3JlYXRlIjp0cnVlLCJpc0Jhc2VBcHAiOnRydWUsIl9pZCI6IjY0NmNjOGRjOTZkNGE0ZGM4ZjdiMmYyZCIsImRpc3BsYXlOYW1lIjoiRXRob3JhIiwiZG9tYWluTmFtZSI6ImV0aG9yYSIsImNyZWF0b3JJZCI6IjY0NmNjOGQzOTZkNGE0ZGM4ZjdiMmYyNSIsInVzZXJzQ2FuRnJlZSI6dHJ1ZSwiZGVmYXVsdEFjY2Vzc0Fzc2V0c09wZW4iOnRydWUsImRlZmF1bHRBY2Nlc3NQcm9maWxlT3BlbiI6dHJ1ZSwiYnVuZGxlSWQiOiJjb20uZXRob3JhIiwicHJpbWFyeUNvbG9yIjoiIzAwM0U5QyIsInNlY29uZGFyeUNvbG9yIjoiIzI3NzVFQSIsImNvaW5TeW1ib2wiOiJFVE8iLCJjb2luTmFtZSI6IkV0aG9yYSBDb2luIiwiUkVBQ1RfQVBQX0ZJUkVCQVNFX0FQSV9LRVkiOiJBSXphU3lEUWRrdnZ4S0t4NC1XcmpMUW9ZZjA4R0ZBUmdpX3FPNGciLCJSRUFDVF9BUFBfRklSRUJBU0VfQVVUSF9ET01BSU4iOiJldGhvcmEtNjY4ZTkuZmlyZWJhc2VhcHAuY29tIiwiUkVBQ1RfQVBQX0ZJUkVCQVNFX1BST0pFQ1RfSUQiOiJldGhvcmEtNjY4ZTkiLCJSRUFDVF9BUFBfRklSRUJBU0VfU1RPUkFHRV9CVUNLRVQiOiJldGhvcmEtNjY4ZTkuYXBwc3BvdC5jb20iLCJSRUFDVF9BUFBfRklSRUJBU0VfTUVTU0FHSU5HX1NFTkRFUl9JRCI6Ijk3MjkzMzQ3MDA1NCIsIlJFQUNUX0FQUF9GSVJFQkFTRV9BUFBfSUQiOiIxOjk3MjkzMzQ3MDA1NDp3ZWI6ZDQ2ODJlNzZlZjAyZmQ5YjljZGFhNyIsIlJFQUNUX0FQUF9GSVJFQkFTRV9NRUFTVVJNRU5UX0lEIjoiRy1XSE03WFJaNEM4IiwiUkVBQ1RfQVBQX1NUUklQRV9QVUJMSVNIQUJMRV9LRVkiOiIiLCJSRUFDVF9BUFBfU1RSSVBFX1NFQ1JFVF9LRVkiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTIzVDE0OjA4OjI4LjEzNloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTIzVDE0OjA4OjI4LjEzNloiLCJfX3YiOjB9LCJpYXQiOjE2ODQ4NTA5MjV9.-IqNVMsf8GyS9Z-_yuNW7hpSmejajjAy-W0J8TadRIM", "Content-Type": "application/json", "common": {"Accept": "application/json, text/plain, */*"}, "delete": {}, "get": {}, "head": {}, "patch": {"Content-Type": "application/x-www-form-urlencoded"}, "post": {"Content-Type": "application/x-www-form-urlencoded"}, "put": {"Content-Type": "application/x-www-form-urlencoded"}, "x-device-type": "android"}

**Comment by dzinzyura** [comment]
done. added to the code. need to make an updated build

**Comment by transkarpation** [comment]
![image](https://github.com/dappros/ethora/assets/57521389/405c9cd3-b03f-45fc-a509-3c4213dc46ff)

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-08-16 в 09 22 48" src="https://github.com/dappros/ethora/assets/54039544/9b8a6fbe-5495-4a5e-9595-3da27da219fa">
