### ISSUE TITLE
Swipe between chatrooms

### ISSUE THREAD

**Issue by seshubonam** [dappros/ethora#471]
**On react native mobile version would like to know how to enable a swipe between chat rooms.

**Describe the solution you'd like**
After opening a chat room, would like to have a swipe action enabled to navigate to next chatroom. instead of going back to room list and opening a new room. 

**Describe alternatives you've considered**
navigating back to room list is the only alternative but on mobile for our specific need , where we are implementing voice chat rooms, would like to navigate to next voice chat room by swiping on existing chat room.

**Comment by dzinzyura** [comment]
Hi, @seshubonam !

Thanks for your message! Unfortunately, we currently do not have plans to implement this feature in the near future. Your feedback is valuable to us, and we appreciate your suggestion.

If you have any more questions or need assistance, please don't hesitate to reach out.

Best regards,
Ethora team

**Comment by seshubonam** [comment]
thanks for your response.
