### ISSUE TITLE
Admin - Apps - update the list with Stats

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#472]
Please update the Apps list accordingly.

Blue captions above should be displayed when user hovers (or clicks) the ℹ️  icon next to each metric name.

If there is no Stats information from the backend, simply display "N/A" instead of numbers in that field. 

Stats icon in the right (next to Settings icon) will be inactive for now, until we bring back the detailed stats interface.

<img width="1962" alt="Screenshot 2023-07-27 at 14 56 13" src="https://github.com/dappros/ethora/assets/328787/ac7f4f4f-6fde-4d9b-ac71-7cc4a18f7396">

**Comment by dendidibe** [comment]
<img width="1439" alt="Снимок экрана 2023-07-27 в 18 35 11" src="https://github.com/dappros/ethora/assets/54039544/fc6069f5-b9aa-4487-9559-f77c6f4d24e8">

**Comment by phwizard** [comment]
thank you - looks good!

"Sessions" info message is missing though, please add: "User sessions (total vs 24h)"

also add one for "Created": "App creation date'

@dendidibe

**Comment by dzinzyura** [comment]
done. thanks @dendidibe 
needs to be implement on the backend side. *maybe we need to add appID for headers of all requests from client side @transkarpation

**Comment by phwizard** [comment]
Thank you
