### ISSUE TITLE
Admin - Apps - Backend alignment

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#474]
See alignment in the wider window size. 

Content needs to be aligned to the left.

<img width="1367" alt="Screenshot 2023-07-27 at 15 20 32" src="https://github.com/dappros/ethora/assets/328787/34b8af3a-8493-4e30-846b-1e8914c3c83f">

**Comment by dendidibe** [comment]
<img width="1439" alt="Снимок экрана 2023-07-27 в 17 55 17" src="https://github.com/dappros/ethora/assets/54039544/4c7f094b-217e-4315-94de-34ca275f5f49">
