### ISSUE TITLE
Export CSV - file rename & add date

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#477]
For CSV export of the Users list, please change the file name 

from:
download.csv

to:
users-YYYY-MM-DD.csv

for example, for today it will be:
users-2023-07-27.csv

<img width="445" alt="Screenshot 2023-07-27 at 17 45 49" src="https://github.com/dappros/ethora/assets/328787/f784f584-3ea5-44a3-a48b-cd406608a76a">

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/fc8f9e45-3623-4679-8458-e0c7b14d5786

**Comment by dzinzyura** [comment]
done. thanks Misha
