### ISSUE TITLE
Admin - Apps - Default chats changes (FE)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#479]
**Goal:**
Introduce a possibility to make changes for default chats.

**Affected metric:**
- UI / UX enhancements
- Ease of data handling

**Story:**
As an app owner, when I go to Apps - "App" - User defaults. I want to change 2nd default change. I enter desired name, change the JID of the app and pin this chat. After this, I click on "Save" button and the chat is changed. 

**Description:**
Implement the possibility to edit default chatrooms according to this list:
1. Edit room title - make an input field for renaming chatrooms
2. Edit room JID - make an input filed for changing room JID
3. Verification of the JID - correct or not
4. New data goes to backend

**Comment by phwizard** [comment]
this isn't deployed yet?

**Comment by dzinzyura** [comment]
done. deployed @phwizard

thank you @dendidibe
