### ISSUE TITLE
Web - Chat - Replies and Threads UI improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#482]
<img width="372" alt="Screenshot 2023-08-08 at 13 29 57" src="https://github.com/dappros/ethora/assets/328787/e2bfe4cc-ff0d-46fe-b671-5a75d987a778">

1. Instead of "3 Replies (tap to review)" please write "**3 replies** Last reply today at 1.26 pm".

2. Please align this line left so it starts same as message 'bubble' without extra padding. 

3. If possible, add small profile icons (up to 3) of users who have replied in the thread.

4. Once user hovers over this line, then replace this part "Last reply today at 1.26 pm" with "View thread"

<img width="1152" alt="Screenshot 2023-08-08 at 13 34 11" src="https://github.com/dappros/ethora/assets/328787/790ee99e-b25e-4393-9f19-e20794683972">

5. Please add a vertical line separator between main chat and thread, same as between chats menu and main chat.

6. Inside thread, please instead of just number "3" write "3 replies" to make it more clear.

thanks!

**Comment by dendidibe** [comment]
<img width="379" alt="Снимок экрана 2023-08-14 в 10 02 31" src="https://github.com/dappros/ethora/assets/54039544/3d3a20c4-6467-4f21-9d31-9e067bd83bf1">

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-08-16 в 09 19 11" src="https://github.com/dappros/ethora/assets/54039544/220383c2-1eee-4ead-85c7-b86b71d60d1e">

**Comment by dzinzyura** [comment]
looks great, thanks @dendidibe !
