### ISSUE TITLE
Experimental - user balance / profile icon

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#484]
Looking to make the Balance Box more visually appealing to the user and also emphasise that it leads to User's Profile. 

Can you please create an experimental update where our Balance Box (top right) also shows user's own avatar image?

Image is just a sketch, avatar can be with rounded corners etc.

BEFORE:
<img width="224" alt="Screenshot 2023-08-08 at 15 07 43" src="https://github.com/dappros/ethora/assets/328787/50c05742-a9b4-46d8-a639-2a57f369453c">

AFTER:
<img width="217" alt="Screenshot 2023-08-08 at 15 07 57" src="https://github.com/dappros/ethora/assets/328787/8f986fc6-52ca-4ea7-b8df-cc24987c5b15">

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-08-09 в 10 26 17" src="https://github.com/dappros/ethora/assets/54039544/b4e249d9-87a3-40a3-a411-ce94af1d8089">

**Comment by dzinzyura** [comment]
@dendidibe thanks! looks good. but maybe you can also add the Coin icon next to the number, please. because for now it's a little unclear what number is under the avatar

**Comment by dendidibe** [comment]
<img width="1440" alt="Снимок экрана 2023-08-09 в 10 32 13" src="https://github.com/dappros/ethora/assets/54039544/e3e3212e-a7d8-4a3f-925a-90a29ecc0551">
