### ISSUE TITLE
Web - chat tabs highlight

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#485]
Currently user doesn't know which tab they're in.

Example: below we're in the "Starred" tab but we can't say which tab is active now.

Please add an indication for the currently active tab in either of the options:

- yellow colour of the icon
- bright white colour of the icon
- underline or highlight around the icon

<img width="577" alt="Screenshot 2023-08-09 at 16 45 45" src="https://github.com/dappros/ethora/assets/328787/30560fd5-4608-4c02-8720-3d7a9c62dfa7">

**Comment by dendidibe** [comment]
<img width="510" alt="Снимок экрана 2023-08-10 в 09 12 56" src="https://github.com/dappros/ethora/assets/54039544/4f8a13c9-4f27-415d-bf51-9b597686c5f4">

**Comment by dzinzyura** [comment]
done. thank you!
