### ISSUE TITLE
Web - client - Email already exists

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#487]
**Goal:**
Introduce the notification pop-up for the sign up with already existing email.

**Affected metric:**
- UI/UX enhancement

**Story:**
*Prerequisites*
My email was already used/registered.

As a user, when I sign-up with my email, entering password and click on "Continue". Yet I receive a pop-up with the notification of already existing user with this email.

**Description:**
Implement the notification pop-up with the following text message: "Email already exists" for already existing emails.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/a32af7ff-e6a5-4825-8c98-c85f2ea26d55

**Comment by dzinzyura** [comment]
great stuff! thanks @dendidibe
