### ISSUE TITLE
Web - client - Favicon changes

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#489]
**Goal:**
Introduce the Ethora logo as a favicon of the ethora.ethoradev.com

**Affected metrics:**
- UI / UX enhancements

**Description:**
Change the favicon for the web-client - [.zip with the icon](https://dappros.slack.com/archives/C025G04FQV6/p1691573623412539?thread_ts=1691569597.535639&cid=C025G04FQV6)

**Comment by dendidibe** [comment]
<img width="248" alt="Снимок экрана 2023-08-11 в 10 27 18" src="https://github.com/dappros/ethora/assets/54039544/60aa7c83-c05b-4ec7-a11d-3c753093ec45">

**Comment by dzinzyura** [comment]
thank you!
