### ISSUE TITLE
Web - new chat room - improvements

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#491]
UX/UI improvements required for “Create new chat” interface

<img width="694" alt="Screenshot 2023-08-10 at 10 05 34" src="https://github.com/dappros/ethora/assets/328787/9043ca00-a5c6-420a-adf4-ece8ae7e0053">

Maybe look into how it’s done in other messengers

I think title here should be renamed to

“Create a new room”

+ add description for example:
Your new chat room will only be visible to you initially but you can invite other users via QR code or short link. 

+ improve the UI a bit, for example next to Chat Name it would be good to display a red * to show this field is mandatory

also “profile” icon is a bit confusing, needs to be replaced with another image which better symbolizes that this is a chat room thumbnail and also should have some guidance regarding the recommended image sizes here I guess

buttons (Submit) I would rather align left (or right) rather than center

**Comment by joshuasoftdev** [comment]
May I please be assigned to this?

**Comment by phwizard** [comment]
we have a new design for this screen, closing issue as not relevant anymore
