### ISSUE TITLE
Web - Room created - redirect

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#492]
Currently, when user creates a new chat room, they stay in the Starred tab and don't see their created room. They need to navigate to Groups and then open the newly created room.

This is a bit confusing.

Could you make it so that user is redirected to the newly created room after it's created?

If that is not possible (due to XMPP delay etc) then please redirect to "Groups" tab so at least user sees there new room in the sidebar.

<img width="773" alt="Screenshot 2023-08-10 at 10 22 26" src="https://github.com/dappros/ethora/assets/328787/99af1b89-81f1-4540-a2ac-85838aea723f">

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/d99eabcd-02f6-4148-affa-d315bfa05790

**Comment by dzinzyura** [comment]
great stuff! thank you @dendidibe !

**Comment by phwizard** [comment]
thank you
