### ISSUE TITLE
Web - client - Chats - Leave room

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#495]
**Goal:**
Introduce a possibility to leave the chat room for regular users.

**Affected metric:**
- UI/UX enhancements
- Ease of chatrooms handling

**Story:**
As a regular user, I was invited to the room. After sending some messages I decided to leave. I go to chat details screen and can see the [exit] icon on the Chat Image. When I click on it, I receive a "warning" message. I click on "Leave" and room is deleted for me.

**Description:**
Implement the way for leaving the room for regular users. You can use the same logic as we have for chat owners. 

1. Change the icon to [leave] one

e.g. 
![image](https://github.com/dappros/ethora/assets/99117374/4c69448d-ef4f-44f8-aabb-2be825e8c885)

2. Add a warning message as we have for app owners: 

<img width="313" alt="image" src="https://github.com/dappros/ethora/assets/99117374/042bb2eb-52f8-4b71-8053-6e01ffe3f7c9">

But change the text:

**Leave room**

Do you want to leave this room?

[Cancel]    [Leave]

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/cfc41ece-2851-4657-93cc-e1f7d5e2504c
