### ISSUE TITLE
Voice notes Dont play.

### ISSUE THREAD

**Issue by quavo19** [dappros/ethora#496]
Im an IOS developer woring with the react-native directory of the ethora project.
the project is well setup and all features work as expected, except voice recordings, when a user makes a voice note, it loads up to 100% complete, but the voice notes never get displayed on the chat screen to be played, even though text messages work fine.

the same thing happened when I added a component that uses the same 
``` 
"react-native-audio-recorder-player": "^3.5.1",
``` 
to make a voice recording feature. 
**To Reproduce**
1. clone this repository
2. go to the client-react-native directory
3. run the project with X code
4. Go to a chat room and record a voice note 

**Expected behavior**
Expect the voice note to appear in the chat room and to be played. but nothing would happen

**Comment by dzinzyura** [comment]
Hi @quavo19 !

Thank you for promptly notifying us about the issue!

 Our team is already working diligently to gather the necessary details, and we're committed to resolving the problem as soon as possible. 
 
 We truly value your involvement in our project, as your insights and contributions are integral to our success!

Rest assured, we'll keep you updated on the progress and ensure transparent communication throughout the resolution process. If you have any further questions or concerns, please don't hesitate to reach out. 

Thank you once again for being an essential part of our team.

Best regards, 
Ethora team

**Comment by dzinzyura** [comment]
@dendidibe checked - the problems is related to the backend. @transkarpation can you check please

> data": {"error": "{\"stack\":\"Error: Command failed: ffprobe -i /app/dist/uploads/fa794a6974286dfaf37691cb82567790 -sexagesimal  -show_entries format=duration -v quiet -of csv=\\\"p=0\\\"\\n\\n    at ChildProcess.exithandler (node:child_process:419:12)\\n    at ChildProcess.emit (node:events:513:28)\\n    at ChildProcess.emit (node:domain:489:12)\\n    at maybeClose (node:internal/child_process:1098:16)\\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)\",\"message\":\"Command failed: ffprobe -i /app/dist/uploads/fa794a6974286dfaf37691cb82567790 -sexagesimal  -show_entries format=duration -v quiet -of csv=\\\"p=0\\\"\\n\",\"code\":1,\"killed\":false,\"signal\":null,\"cmd\":\"ffprobe -i /app/dist/uploads/fa794a6974286dfaf37691cb82567790 -sexagesimal  -show_entries format=duration -v quiet -of csv=\\\"p=0\\\"\",\"stdout\":\"\",\"stderr\":\"\"}", "success": false}
