### ISSUE TITLE
How to connect backend to react native app built manually 

### ISSUE THREAD

**Issue by quavo19** [dappros/ethora#497]
I've manually built the app with version 22.09 of the Ethora React Native project. Modifications include an added story component, and UI adjustments to the menu pages. I'm currently testing on iOS, with Android in the build phase.

Platform: React Native (iOS & Android).

Query: How can I establish my own backend for the Docker option?

**Comment by dzinzyura** [comment]
Hello, @quavo19 !

I appreciate your inquiry.

After consulting with the team, I want to inform you that we do not provide Docker images for the backend. However, you can still access the API by utilizing the following link: http://api.ethoradev.com/api-docs.

Please, let us know if you have any questions. We're always happy to help.

Best regards,
Ethora team
