### ISSUE TITLE
"Starred rooms" proposal

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#502]
Propose to use mod_private (XEP-0049) as data storage for the rooms starred by the User. 

Let's decide on this during our call tomorrow.

mod_private should be enabled server-side. 

<img width="971" alt="Screenshot 2023-08-28 at 15 40 31" src="https://github.com/dappros/ethora/assets/328787/792338c1-e1b1-4477-9b4b-d57c3190dba0">

<img width="680" alt="Screenshot 2023-08-28 at 15 40 42" src="https://github.com/dappros/ethora/assets/328787/7663b0c2-acc5-480c-b544-4ba925b88c1a">

https://xmpp.org/extensions/xep-0049.html
https://docs.ejabberd.im/admin/configuration/modules/

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/8b4de2ae-dd57-4f29-8052-0ec839a4aab3

**Comment by dzinzyura** [comment]
looks great! thanks @dendidibe
