### ISSUE TITLE
Web - threads - reset checkbox

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#503]
When User has sent a message into main room via checking "Also send to room" checkbox, please reset (uncheck) this checkbox so that by accident user doesn't spam the room with more messages. User needs to enable this checkbox explicitly every time they want to copy the message into main room.

<img width="925" alt="Screenshot 2023-08-28 at 17 12 30" src="https://github.com/dappros/ethora/assets/328787/f0d12df1-9882-47cd-820d-85c1a2bcd1d8">

**Comment by dzinzyura** [comment]
done. thank you @dendidibe
