### ISSUE TITLE
Ethora app issues (iOS build)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#506]
**Goal:**
Introduce the bug fixed version of the Ethora app for future reviews & testing purposes.

**Affected metric:**
- UI / UX enhancements
- Ease of use of the application

**Description:**
Fix the following issues:

1. The Emoji keyboard is opened in Description tab issue
https://dappros.slack.com/archives/C025G04FQV6/p1694073163459509

2. "Copy link" notification pop-up display
https://dappros.slack.com/archives/C025G04FQV6/p1694073242325789

3. The voice message does not automatically close, when it ends
https://dappros.slack.com/archives/C025G04FQV6/p1694073571003279

4. Referrals feature doesn't work
https://dappros.slack.com/archives/C025G04FQV6/p1694073628771549

5. No sound, when sending coins
https://dappros.slack.com/archives/C025G04FQV6/p1694073779724779

6. Displaying wrong person items in the profile
https://dappros.slack.com/archives/C025G04FQV6/p1694073892872309

7. The input field is jumping when I want to enter the text
https://dappros.slack.com/archives/C025G04FQV6/p1694073994637459

8. The keyboard overlapping the content a bit in the Documents tab, while adding the doc name
https://dappros.slack.com/archives/C025G04FQV6/p1694074089315799

9. "Delete documents" feature doesn't work
https://dappros.slack.com/archives/C025G04FQV6/p1694074373080369

10. When I have something in the clipboard and I open the "Privacy and data" tab it shows me the system pop-up
https://dappros.slack.com/archives/C025G04FQV6/p1694074455256089

11. Room subscription via the QR-code / link
https://dappros.slack.com/archives/C025G04FQV6/p1694074571056029

12. "Create new room" issues:

- The image, which was added while creating the chat, is not displayed. But when you set up the image from the chat details - it works fine
- When the chatroom is created, the chat is lagging, cannot send the message / sometimes cannot write the message in the input field
- Some messages are skipped / not sent
- Chat started glitching when I closed the keyboard after sending a few messages
- When adding the room to favorites it's only work while you're in the app. When you kill it and open again - it's disappeared from favorites tab.

https://dappros.slack.com/archives/C025G04FQV6/p1694075214403479

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/74bad31d

https://github.com/dappros/ethora/assets/54039544/da580ae0-ff0f-4b36-918d-85e09dd2d440

-b4fd-4335-a0e1-fed28f789f53


https://github.com/dappros/ethora/assets/54039544/a30affee-b1ed-43c8-a6e4-065e839749f2


https://github.com/dappros/ethora/assets/54039544/8197e472-5ce8-4e45-876d-d58edad92528

**Comment by dendidibe** [comment]
all issues fixed except: 
2 - because there is system problem with z-index, will research about it
8 - added is scroll when keyboard enabled
11 - this is standard ios behaviour

issues with chat slowness is because after room creation we fetch them from xmpp and after there are a lot of actions related to messages

**Comment by dzinzyura** [comment]
thank you @dendidibe
