### ISSUE TITLE
"Join the room" logic issue

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#511]
**Goal:**
Introduce bug fixed logic for "Join the room".

**Affected metric:**
- UI / UX enhancement
- Ease of data handling
- Сore features performance enhancement

**Description:**
Fix the bug with displaying the "Join the room" button when user already subscribed to the room.

**Comment by dendidibe** [comment]
https://github.com/dappros/ethora/assets/54039544/6d6c436d-2ada-49d8-a08d-d78a65125eb0

**Comment by dzinzyura** [comment]
great! thanks @dendidibe !
