### ISSUE TITLE
Login screen and Icon design update

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#514]
Let's update the default Login screen and App Icon with the new design.

Notes:

The main (title) message should take the App Title from the global settings parameter, i.e.: "Welcome to [ APP_TITLE ]" so it will change according to project settings.

The next (tagline) message can be part of the design template and will be customized. 

Logo and Background image should be taken from respective files as before. 

Sign in with Google, Create an Account, Facebook, Apple and Metamask buttons may be enabled/disabled depending on App settings.

<img width="507" alt="Screenshot 2023-11-01 at 04 40 20" src="https://github.com/dappros/ethora/assets/328787/1c2c1de8-d193-4aba-b87e-e93cbe70e24e">

**Comment by mykolapylypchukk** [comment]
![photo_2023-11-15_22-02-53](https://github.com/dappros/ethora/assets/148977403/a9d81055-3bf9-4362-902d-410ac87f77d5)
![photo_2023-11-15_22-02-58](https://github.com/dappros/ethora/assets/148977403/dbd9d86b-5f1e-4ffa-8958-4d83d7a8f80b)
![photo_2023-11-15_22-03-01](https://github.com/dappros/ethora/assets/148977403/3f699b02-d392-4070-9ddc-1b206c362883)

**Comment by dzinzyura** [comment]
looks great! thank you @mykolapylypchukk !
