### ISSUE TITLE
design update: List of Chats screen 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#516]
List of Chats is to be updated according to the new design.

Notes:
* The default Tabs should be shown as follows: Favorites, Groups, Private
* Tabs should be centered / spaced out horizontally 
* If pulled down, there should be a UI for Search and " + New Chat" button, as shown in 2nd set of screen designs below, the design assets will be updated with this.

<img width="370" alt="Screenshot 2023-11-01 at 05 15 11" src="https://github.com/dappros/ethora/assets/328787/c9c3cf9b-2ae4-425a-84c3-58b560d3364b">

<img width="529" alt="Screenshot 2023-11-01 at 05 26 37" src="https://github.com/dappros/ethora/assets/328787/7d305b16-50a3-4804-bb08-8015256cbc5c">

**Comment by polipivnenko** [comment]
![photo_2023-11-09_17-41-39](https://github.com/dappros/ethora/assets/149969403/823daf20-917f-41ba-a1a4-729bcb6a5fab)

**Comment by phwizard** [comment]
I think this looks good. Thank you @polipivnenko. Let's go ahead with implementation, @dzinzyura
