### ISSUE TITLE
Design - ethora.com homepage update

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#518]
Please propose new design for the home page of ethora.com

You have already proposed the top part (1st screen) which looks good, need to proceed with the rest. 

Note: replace the caption "Packed with web2 and web3 features that will play a pivotal role in growing your community" with "Packed with web2 and web3 features that will play a pivotal role in your digital transformation"

Before:
<img width="1744" alt="Screenshot 2023-11-02 at 12 52 17" src="https://github.com/dappros/ethora/assets/328787/aa341b72-8cf8-41ea-81e7-4e9b9a89340d">

After:
<img width="1315" alt="Screenshot 2023-11-02 at 12 53 12" src="https://github.com/dappros/ethora/assets/328787/69d2e335-0a25-4cef-8a58-0707586ad304">

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/c7290879-238c-4486-9a97-a85f054294d1)
![image](https://github.com/dappros/ethora/assets/149969403/42262c2e-b7e4-4d81-99f5-c094b23c639e)

@phwizard @dzinzyura 
This is the first version, it will be improved
I'm considering applying the parallax effect to the Home page. The multicolored spheres represent foreground objects and "greet" in front of the text blocks.

**Comment by phwizard** [comment]
@polipivnenko personally, I liked your suggestion here much more.

We need a simple and clean 2D style. 

What you had in the 1st screen there I thought you would just implement the rest of it in the similar style. 

<img width="611" alt="Screenshot 2023-11-21 at 11 19 14" src="https://github.com/dappros/ethora/assets/328787/50290311-f628-47e3-9132-9bd5a51ce98f">

**Comment by polipivnenko** [comment]
@phwizard Yes, of course, I can go back to the first style.

**Comment by polipivnenko** [comment]
Intermediate result, highlights will still be added to the text.
@phwizard @dzinzyura 

![image](https://github.com/dappros/ethora/assets/149969403/a822dad5-ee8e-4900-869d-dfc75f1403c2)
![image](https://github.com/dappros/ethora/assets/149969403/5a91f932-c620-4fda-8b35-e47e055dccd4)
![image](https://github.com/dappros/ethora/assets/149969403/27a1aa35-3350-49d8-a6a2-f8b061a8cc95)
![image](https://github.com/dappros/ethora/assets/149969403/0905fe16-11b2-4b98-9098-3f1c785035f7)

**Comment by dzinzyura** [comment]
this one looks cool! thank you @polipivnenko 

@phwizard what do you think?

**Comment by phwizard** [comment]
@polipivnenko thank you for your work here

I like most of it, however I'm not sure about this part:

<img width="707" alt="Screenshot 2023-11-23 at 14 24 13" src="https://github.com/dappros/ethora/assets/328787/645535b6-fd7f-4713-9629-450882125a03">

1) I don't think our design should be 3D (have lots of layers and shadows). There should be reasons for doing that and it should be consistent, I'd prefer to avoid that and keep ours flat and simple
2) it's not clear what the stationary can is representing - is that for designing / editing the app?
3) it may be better to represent this part in flat / 2D also because it will be easier for us to edit. See how it works now below, and the design of this 'App Builder' page is also likely to improve so we will need to update it. 

<img width="1391" alt="Screenshot 2023-11-23 at 14 25 55" src="https://github.com/dappros/ethora/assets/328787/88cbfd3b-0b0d-4f2d-b856-b21e0db48bf9">

I like some of the solutions how things are done in our current design, it's not bad at all: https://www.ethora.com/ but I don't think the layout is complete. For example, the top 1st screen is just too large on desktop screen (on mobile the whole current website actually looks good with a couple minor things to improve). 

<img width="1660" alt="Screenshot 2023-11-23 at 14 30 13" src="https://github.com/dappros/ethora/assets/328787/553ad0dc-d96d-4dbc-8007-a9ef86f98255">

and I like your design and sizing of the 1st screen much more,

and also this part needs improvement

<img width="1182" alt="Screenshot 2023-11-23 at 14 30 49" src="https://github.com/dappros/ethora/assets/328787/80a76786-2f0d-4707-b1b8-f02d13848509">

however overall the existing design is quite good already

I wouldn't even change it but it didn't feel complete

what I wanted to achieve with the redesign is a holistic unified look where everything looks in place, it is professional looking but also isn't boring and delivers the message

so this needs either a holistic approach from you or other option is I may need to get more involved and we jointly create a new wireframe, I just will be busy next 1 week so not sure when I can get more involved here

I know my feedback may be confusing and I won't be able to help with a more detailed wireframe until late next week so I suggest you either produce your own version of final design in Figma (and I will review and provide suggestions again) or work on other screens for now.

Thanks!


any comments from @Egatlov or @dzinzyura feel free to add

**Comment by phwizard** [comment]
I like this version more, thank you @polipivnenko. @Egatlov and @dzinzyura,.  do you have any suggestions?

**Comment by dzinzyura** [comment]
@phwizard maybe @polipivnenko can add icons for the features section? I guess it would give a better and clearer understanding for users

@Egatlov what do you think?

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/eda3374c-7c92-421b-8191-c60cda448947)
@dzinzyura I did this in the last update)

**Comment by dzinzyura** [comment]
oh, sorry @polipivnenko. missed this one

**Comment by Egatlov** [comment]
@polipivnenko @dzinzyura This version of the homepage looks good, the only thing I'd suggest is to make use of solid colours and shadows and less use of gradients.

**Comment by phwizard** [comment]
@polipivnenko many thanks for this. Please see if you can address some final comments / adjustments before we take this into implementation:

BEFORE

<img width="1381" alt="Screenshot 2024-01-08 at 15 08 47" src="https://github.com/dappros/ethora/assets/328787/2bf42496-114d-4c95-9d1f-282994282401">

AFTER

<img width="708" alt="Screenshot 2024-01-08 at 15 09 12" src="https://github.com/dappros/ethora/assets/328787/b718d2a3-0609-4ac1-958f-04a103138b99">

In the "BEFORE" I like the clean style and that we feature iOS, Android icons. Can you add iOS, Android (and maybe Web) icons into the new design as well?


BEFORE

<img width="1227" alt="Screenshot 2024-01-08 at 15 14 02" src="https://github.com/dappros/ethora/assets/328787/6f7f95d2-4c72-421c-8730-ff19d7c5846a">

AFTER

<img width="727" alt="Screenshot 2024-01-08 at 15 14 15" src="https://github.com/dappros/ethora/assets/328787/84d9a46d-ca87-4d3e-946f-cb925ef40eb3">

Again looks clean and more calling to action the "Sign Up & Build!" button in the old design. I don't know if / what can be improved in the new design though.


BEFORE

<img width="1186" alt="Screenshot 2024-01-08 at 15 15 53" src="https://github.com/dappros/ethora/assets/328787/7958af4b-b646-41b3-872c-be0528036356">

AFTER

<img width="701" alt="Screenshot 2024-01-08 at 15 16 05" src="https://github.com/dappros/ethora/assets/328787/9564c1e1-6534-450a-833a-86656df8ac0e">

Is it possible to have a hand holding a chisel, not a hammer? Or a hammer that is hammering a chisel? 


SWAP PLACES

<img width="729" alt="Screenshot 2024-01-08 at 15 16 57" src="https://github.com/dappros/ethora/assets/328787/f9a7ea69-905c-4b22-bc76-9a40d871a983">

Please swap images for "Chat, work, play .. " and "Built using the most popular technical stack". The messaging illustration better goes for the 1st paragraph, wile the 3rd one needs something related to tech stack, React icon or actually the image you used for the 1st paragraph is totally fine, if you just swap them. 


FOCUS ON YOUR GROWTH section

<img width="901" alt="Screenshot 2024-01-08 at 15 19 13" src="https://github.com/dappros/ethora/assets/328787/76587f4e-b622-4986-9c88-c503c81ed1a9">

This I definitely like more than the previous design, however can you make the business longer vertically so that either it's bottom is aligned with the bottom of Free and Enterprise, or its bottom is sticking out same length as the top, so it's more symmetrical and prominent. 

FAQ section

BEFORE

<img width="939" alt="Screenshot 2024-01-08 at 15 21 37" src="https://github.com/dappros/ethora/assets/328787/b85626a9-9fea-470d-92f4-25315791ed94">

AFTER

<img width="1555" alt="Screenshot 2024-01-08 at 15 22 47" src="https://github.com/dappros/ethora/assets/328787/39945ef8-3930-41bc-aa41-fc6c29ea03e2">

It feels like something could be improved here, but I don't know what. OK to keep as is I guess.

CONTACT US section

<img width="672" alt="Screenshot 2024-01-08 at 15 25 19" src="https://github.com/dappros/ethora/assets/328787/172dae40-4d5b-4e81-b6da-6e2c0c8c599d">

This is good but alignment isn't ideal, how about we have 2 tabs here? One default tab will be "Message" and it shows the form and the "Send a message" button. Another tab will be "Call us" and it shows the text "You can also book a call .. " with "Book a call" button.

**Comment by phwizard** [comment]
![CleanShot 2024-01-18 at 09 31 40@2x](https://github.com/dappros/ethora/assets/328787/893f054b-b274-4087-849d-a8d2919cf4ff)

this is great - thank you 

just see if horizontally centered title and price look better for each column?

otherwise keep as is for final version

**Comment by phwizard** [comment]
![CleanShot 2024-01-18 at 09 33 07@2x](https://github.com/dappros/ethora/assets/328787/5bbf7d18-0bf5-4e5b-925d-15d9632d7887)

Love this - good to go

**Comment by phwizard** [comment]
This is good but see if you can still insert a Greek sculptor image or graphical reference. 

![CleanShot 2024-01-18 at 09 34 23@2x
](https://github.com/dappros/ethora/assets/328787/743092e7-1d82-44d3-a4b4-efe6c52dc1ba)

what if you try just adding the image from our current website? it was AI generated by me and custom modified by Nikhil so we have all rights to use it

I guess it could be stylized or something if needed

![CleanShot 2024-01-18 at 09 35 09@2x](https://github.com/dappros/ethora/assets/328787/5b92ecf1-2197-482f-853b-fb41a4152d46)

thanks @polipivnenko

**Comment by phwizard** [comment]
to be clear - image as an illustration to "Do you know whose saying is that" section

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/e4cffa70-39ab-460a-b76c-8984b15fe448)
Here is my variation of the illustration for this section 
@phwizard @dzinzyura

**Comment by phwizard** [comment]
thank you all, closing
