### ISSUE TITLE
Design - Login page additional screens

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#522]
**Goal:**
Introduce additional screen which login screen requires.

**Affected metric:**
- UI / UX enhancements

**Description:**
Create / change additional pages for the updated login screen:

- Login with credentials

![IMG_9825](https://github.com/dappros/ethora/assets/99117374/b8a497f7-5d65-4ebd-bcde-ac012681fcd4)

- Create new account

![IMG_9827](https://github.com/dappros/ethora/assets/99117374/fb314959-48d8-4e27-9d74-00673e2d5676)

- Create new account (when the link from email is clicked / account email is verified)

Thank you for confirming your e-mail!

Just specify a permanent password now and you'll be all set!

Temporary password: [ pre-populated via link from the e-mail button ]

New password: [ ]
Repeat password: [ ]

[ Create account ]

Possible warnings:

Temporary password doesn't match.
Please set a new password in order to proceed.
Your new password and repeat password should match.

- Forgot password 

![IMG_9826](https://github.com/dappros/ethora/assets/99117374/f1a16a79-b995-46f2-b3ee-2accc87afb70)

- Forgot password (new password input screen)

[New password]
[Repeat password]

**Reset password**

Possible warnings:

Temporary password doesn't match.
Please set a new password in order to proceed.
Your new password and repeat password should match.

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/c39251a2-6059-4146-91af-d00eef68e4f9)
![image](https://github.com/dappros/ethora/assets/149969403/dd1f5b08-1892-45e0-a3ea-1423bc79961a)
![image](https://github.com/dappros/ethora/assets/149969403/ca9bed03-9d57-45d4-8738-bd08e222d753)

@phwizard @dzinzyura 
Not final design, will be supplemented

**Comment by phwizard** [comment]
Looks great as for me, good for implementation.

**Comment by dzinzyura** [comment]
@mykolapylypchukk you can proceed with the implementation of these screens.

**Comment by dzinzyura** [comment]
@mykolapylypchukk states of the input fields are also added. fyi

<img width="566" alt="image" src="https://github.com/dappros/ethora/assets/99117374/2597ea1b-384b-4851-9244-1f79b9d9c043">

others are added in Figma as well

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/032abba5-59f3-4219-9c96-e81d402e5591)
![image](https://github.com/dappros/ethora/assets/149969403/9dee814c-53d7-4d73-902f-06bbb0fba5c4)
![image](https://github.com/dappros/ethora/assets/149969403/0a171151-c5ef-4a25-94eb-3c14be503844)
![image](https://github.com/dappros/ethora/assets/149969403/b1a7c8b5-0915-4692-88dc-1c8e8f6d88f8)

@phwizard @dzinzyura 
These screens are ready

**Comment by phwizard** [comment]
Looks good to me, thank you Polina, good for implementation @dzinzyura

**Comment by phwizard** [comment]
One thing I noticed @polipivnenko @dzinzyura - I don't see a Google  / Gmail sign in icon here. That should be the first of SSO options if not disabled for the current app:

Google - FB - Apple - Metamask

**Comment by dzinzyura** [comment]
@phwizard it's present and considered as a main / first suggestion for login 

<img width="254" alt="image" src="https://github.com/dappros/ethora/assets/99117374/86412eb2-a549-45c7-bedd-d8bc938bfe68">

**Comment by phwizard** [comment]
@dzinzyura thanks, I missed that, all good then!
