### ISSUE TITLE
Design - Chat list - Create New Chat

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#523]
**Goal:**
Introduce the update screen for "Create New Chat" logic.

**Affected metric:**
- UI / UX enhancements

**Description:**
Create an updated design for "Create New Chat" screen.
Here's the "Create new chat" screen for now:

![IMG_9831](https://github.com/dappros/ethora/assets/99117374/5d27c42f-668e-4c51-ae9a-7906bf2d19f3)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/ac5e29f8-ac8e-41b1-a035-3bccc8e19c90)

**Comment by phwizard** [comment]
Thank you @polipivnenko

Please change "Short description about the chat" to "Description (optional)"

@dzinzyura otherwise, this is ready for implementation.

**Comment by dzinzyura** [comment]
@mykolapylypchukk please, proceed with the implementation. 

Use "Description (optional)" instead of "Short description about the chat".

**Comment by ashifkhn** [comment]
Can you assign me this task?

**Comment by phwizard** [comment]
@polipivnenko 
@Egatlov 

I feel like a bit of fine tuning for this UI is needed

could you review and finalize? 

the UI parts are all OK, just a bit more attention to the layout

as an alternative, this could be a modal window 

only required parameter here is the 'Chat name' and the 'Create' button, the rest is optional

<img width="531" alt="Screenshot 2023-12-04 at 14 36 51" src="https://github.com/dappros/ethora/assets/328787/7c6847ed-74bd-4812-806b-ba11bfea505f">

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/ecde5972-ff6c-4e39-ab44-85f843a31b89)

I have created a version of the pop-up for this element and added a section on Chat Privacy. This feature can also be added to the chat settings if it hasn't been included earlier.

@phwizard @dzinzyura

**Comment by phwizard** [comment]
To be updated with new design

**Comment by dzinzyura** [comment]
done. thank you @RomanLeshc!

https://github.com/dappros/ethora/assets/99117374/becb4e86-507c-48ce-a266-1a2918117f32
