### ISSUE TITLE
Mobile - Store - Code refactoring

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#531]
**Goal:**
Introduce a refactored "Store" code for react-native app.

**Affected metric:**
- Ease of use
- Ease of data handling
- Code readability improvements

**Description:**
Refactor the react-native code as you suggested: take out types, functions and divide them by logic (for example, chat functions, user functions) and import them from one file - it will take up less space, will be more understandable for external users

**Comment by phwizard** [comment]
outdated issue

code and issues moving to https://github.com/dappros/ethora-app-react-native
