### ISSUE TITLE
Design - branding for Ethora (formerly Dappros) youtube channel 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#532]
We plan to be posting more content on Youtube so need to update our branding there.

<img width="1151" alt="Screenshot 2023-12-03 at 19 34 35" src="https://github.com/dappros/ethora/assets/328787/64485863-8840-41d6-abd2-cc0186bed9cf">

https://www.youtube.com/@ethora_app

Assets needed: 
* picture (use Ethora logo)
* banner image (for this we can use ethora logo and some simple background similar how you have done for the Ethora login screen design
* watermark (use Ethora logo)

<img width="691" alt="Screenshot 2023-12-03 at 19 35 41" src="https://github.com/dappros/ethora/assets/328787/e8c87c0c-7e08-4ff2-b8e2-4138eeab50a2">

If you think that additional content / text would be beneficial for the banner image then you can use this:

Ethora, your 'super app' engine
www.ethora.com
Twitter: @ethora_app
Youtube: @ethora_app
Github: https://github.com/dappros/ethora

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/6af339c1-d6d6-4575-89e1-e5c612667b08)
![image](https://github.com/dappros/ethora/assets/149969403/fb626a09-b076-4439-a363-2544765ec3bf)

The banner is for various screen formats (may be chosen different text for the banner). Also, there is a channel icon and 2 watermark options with and without a caption.

@phwizard

**Comment by dzinzyura** [comment]
looks nice! thank you @polipivnenko

**Comment by dzinzyura** [comment]
done & updated. thank you @polipivnenko @Egatlov
