### ISSUE TITLE
(epic) Design - Profile Screen

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#535]
Please review the instructions and go ahead with implementation of: 

- Profile Screen
- Sharing Profile modal (optional - can keep as is)
- Transactions Screen
- Profile Screen - with Documents tab open

@dzinzyura this may need separate subtasks for each of these created

<img width="1140" alt="Screenshot 2023-12-06 at 13 20 04" src="https://github.com/dappros/ethora/assets/328787/4b741bbf-fe7c-426b-b0f5-0e30c58227d3">

<img width="967" alt="Screenshot 2023-12-06 at 13 20 16" src="https://github.com/dappros/ethora/assets/328787/50c955cb-071a-4eda-a5ac-70c14177dca2">

<img width="1133" alt="Screenshot 2023-12-06 at 13 20 27" src="https://github.com/dappros/ethora/assets/328787/8182e317-15cf-4601-b170-4381525c2f0e">

<img width="1136" alt="Screenshot 2023-12-06 at 13 20 39" src="https://github.com/dappros/ethora/assets/328787/7ab114f7-6a09-42b2-9e2e-6e71749836d3">

<img width="1125" alt="Screenshot 2023-12-06 at 13 20 50" src="https://github.com/dappros/ethora/assets/328787/e2f91102-9ee8-450c-afd5-715fa79215cb">

<img width="1138" alt="Screenshot 2023-12-06 at 13 21 00" src="https://github.com/dappros/ethora/assets/328787/8665f0e7-56f2-4d1d-ba81-5530cc71bb01">

<img width="1135" alt="Screenshot 2023-12-06 at 13 21 10" src="https://github.com/dappros/ethora/assets/328787/805c3564-75d1-4ecd-9ba7-25c9712d1e7f">

<img width="1128" alt="Screenshot 2023-12-06 at 13 21 19" src="https://github.com/dappros/ethora/assets/328787/79b83d36-1068-4a84-ba4d-1d268ea96746">

**Comment by dzinzyura** [comment]
Done. Thank you @polipivnenko! 

Final version:
<img width="1317" alt="image" src="https://github.com/dappros/ethora/assets/99117374/702f33e3-6b5c-4efa-8895-4720a45bb72f">
