### ISSUE TITLE
Design - Profile screen - Items and Collections (Documents)

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#538]
**Goal:**
Introduce an updated vision for assets (Items & Collections section).

**Affected metric:**
- UI/UX enhancement
- Ease of data handling

**Description:**
Create designs for Items & Collections section. At this stage, start with "Documents" part.
Please, use these details and descriptions for future works:

![image](https://github.com/dappros/ethora/assets/99117374/2314d506-fcd9-4e2a-9a7b-966bdcbb7ccf)

**Old view of the "Documents" section:**

![image](https://github.com/dappros/ethora/assets/99117374/9b33a816-d2de-49a6-8b1c-d04f98c0a501)

**Document - details:**

![image](https://github.com/dappros/ethora/assets/99117374/67718430-c761-4cd1-b4d7-40e49e3276cf)

**Delete document:**

![image](https://github.com/dappros/ethora/assets/99117374/fb4f9662-ba74-41ff-ab0d-8147584b6e56)

**Comment by phwizard** [comment]
Please note additional instructions for this section:

<img width="1136" alt="Screenshot 2023-12-06 at 22 43 32" src="https://github.com/dappros/ethora/assets/328787/a81f0e84-1602-4d7e-9126-9cba2948d43a">

We need:
1. The updated Profile screen with the Document tab opened and the table list of Documents there.
2. Documents Details screen as described here


----
Documents

Documents tab:
This part of the Profile UI shows a table with a list of Documents.
For each Documents, the Thumbnail (preview image), Document title and Date are shown. 
Note: we don’t need a QR code here.

See video how this works with the old design here:
Video: https://www.youtube.com/shorts/JrHedC5HW6M 

Detailed article explaining Documents functionality here:
https://www.dappros.com/knowledge-base/documents-storing-and-tracing-provenance-on-blockchain/

Document details:
Once user taps a Document, the screen with document details is opened. It shows:
* Document title, Large preview of the document, QR button (opens sharing modal window), Copy and Delete button. (note: let’s replace Copy with Download here).
* Below the Provenance section is shown. This shows all blockchain transactions related to the Document (e.g. when it was created, by whom, when it was signed or certified, by whom, transferred etc).

**Comment by phwizard** [comment]
Yes something like this could work well:

<img width="232" alt="Screenshot 2023-12-07 at 09 48 49" src="https://github.com/dappros/ethora/assets/328787/856ac5c0-443f-4120-bf5a-d8b26386795e">

However I'm worried there isn't much space for the content of the assets section (bottom 30%) which people may interact with quite a lot if there are assets there.
Thinking about this, however, this could be responsive, so once someone starts to scroll the assets, it rolls up to take like 75% of the screen, but scrolling down or tapping on the top 25% (with the users photo background) will return the screen to the initial state.

**Comment by polipivnenko** [comment]
Yes, I think it will be even more convenient for the user than in other messengers when you have to scroll all the way back to return to the user's profile.

**Comment by phwizard** [comment]
<img width="1035" alt="Screenshot 2023-12-08 at 10 20 10" src="https://github.com/dappros/ethora/assets/328787/d9d9fda7-03ba-4995-9a03-b5ba1e273a26">

This looks good in general  👍

One thing to consider / try - maybe:
(a) try placing the buttons onto the user's photo background (move them higher above About) and have some (subtle?) divider between About and the Assets tabs (wallet content), or
(b) keep placement as is, but have some division between About, Buttons and Assets/wallet tabs, or
(c) have the light background rounded background start only for the Assets tabs (starting with Items, Collection..) while for About and Buttons are simply shown over the User's image, or have some rounded background pads of their own. 

Intuitively and logically, these are different functions. Buttons are for interaction with this user, About/description/bio is the  text that user communicates to the visitors of their profile, while the assets tabs and the scroller below is like a separate thing. 

Wasn't sure about this much padding (spacing) on the left and right, my initial feel was that we need to have less space there and give more horizontal space to the content items in the assets scroller. Second though however this might work well design wise, we shall be able to fit in even if we have more content features for Items and Collections.

Search bar - I don't think we need it at this stage as most users have a small number of assets. We will review this at a later stage based on users feedback.

**Comment by phwizard** [comment]
<img width="1082" alt="Screenshot 2023-12-11 at 11 25 30" src="https://github.com/dappros/ethora/assets/328787/efe38d66-3f39-4c37-9f1f-8d0ab8a13c18">

Looks great so far - let's see this implemented as final designs @polipivnenko

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/b6635f16-c8ad-4674-868b-d1acbb04dca8)

Additional wireframes for collection screens. The second screen of collection details is not yet completely finished, but the overall concept is already established.
@phwizard @dzinzyura

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/bcbfa31e-9d50-4378-8802-b21cfe37ab2a)
Additional wireframes for Documents screens. 
@phwizard @dzinzyura

**Comment by dzinzyura** [comment]
looks good, thank you @polipivnenko 

but the one thing i'm thinking about is this confirmation to delete pop-up screen. as for me, these buttons and message looks a bit random. maybe you can think about something like this one, for example:

![image](https://github.com/dappros/ethora/assets/99117374/eed71edd-1edd-4fa7-92ca-6a11c3f6ca72)

@phwizard @Egatlov

**Comment by phwizard** [comment]
thanks Vlad, that confirmation message is good, in our case it would be "this document" instead of "this profile from the database".

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/1a0ae6cd-adfc-4fe7-b80b-1396d74e26c3)
![image](https://github.com/dappros/ethora/assets/149969403/26d4b038-c644-4cbe-9907-f0f95cac5015)
@dzinzyura @phwizard
