### ISSUE TITLE
Design - User profile - Profile appearance screens

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#541]
**Goal:**
Introduce updated designs for profile appearance settings.

**Affected metric:**
- UI / UX enhancements
- Ease of data handling

**Description:**
Implement designs for profile changes modals: name, description, image.

Attaching the old designs below:

_Description:_
![image](https://github.com/dappros/ethora/assets/99117374/96f82cde-1648-43a7-8a32-8d4dd9af20a8)

_Photo:_ 
![image](https://github.com/dappros/ethora/assets/99117374/d5de9a88-99bd-413e-a393-ba74b32937e6)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/5b9d54c3-4f89-4627-8389-e0a53fbb4857)
![image](https://github.com/dappros/ethora/assets/149969403/de29e40a-f782-4f0a-a991-cb1ffff69003)
First version of profile appearance screens
@dzinzyura @phwizard

**Comment by dzinzyura** [comment]
done. referring Figma: https://www.figma.com/file/tMvNOgHrQpJsDXx3xniQB3?node-id=52:2&locale=en&type=design
