### ISSUE TITLE
Mobile - Chat - Replies and threads 

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#542]
**Goal:**
Introduce updated designs for Replies & Threads screens.

**Affected metric:**
- UI / UX enhancements
- Ease of data handling

**Description:**
Implement new designs for Replies & Thread screens. Attaching the old designs below:

Thread screen with users replies on a specific message:
![image](https://github.com/dappros/ethora/assets/99117374/89fd701b-e87d-4d4d-a34c-e78e11dde57f)

Replies counter under a message:
![image](https://github.com/dappros/ethora/assets/99117374/0ca6fcff-0445-4020-ae5c-14c845b596e1)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/1e167642-9954-41ad-b026-0c0e243430a8)
![image](https://github.com/dappros/ethora/assets/149969403/998ffa4d-4049-45a9-9abf-c48165afec4b)
![image](https://github.com/dappros/ethora/assets/149969403/fe5c9f3b-f7cb-4054-b2b6-cf223d47c2d2)
So far, the first version of Thread screen, number of replies, replying. This is not the final version yet and needs to be improved.
@dzinzyura @phwizard

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/2fe90737-06f4-48af-9fb4-f1ecabfbeb84)
New version of Replies and threads
@dzinzyura @phwizard

**Comment by dzinzyura** [comment]
looks good, thank you @polipivnenko !
