### ISSUE TITLE
Mobile - Chat - Edit message

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#543]
**Goal:**
Introduce updated designs for Edit message feature.

**Affected metric:**
- UI / UX enhancements
- Ease of data handling

**Description:**
Implement an updated design for "Edit message" pop-up. Attaching the old designs below:

![image](https://github.com/dappros/ethora/assets/99117374/6cf5a5fa-e4ce-498a-9283-ad0ef51c8b10)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/782ad49e-870f-4b08-b22c-4c40e699f96a)
The final version @dzinzyura @phwizard

**Comment by dzinzyura** [comment]
thanks @polipivnenko! we can start with the implementation @RomanLeshc
