### ISSUE TITLE
Design - Chat Details screen

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#544]
Please design the Chat Details screen (+ subscreens / modals where required).

This screen can be seen if you tap on the name or icon of the chat room when already inside the messaging interface of the room.

This screen allows to view additional room details, manage your settings / alerts for this room, also see members of the room and follow to their profiles. Owners, admins and moderators also can change room details or apply additional actions to room participants such as assign roles or kick/ban users from the room.

TASK

<img width="1263" alt="Screenshot 2024-01-08 at 14 40 43" src="https://github.com/dappros/ethora/assets/328787/75b14e7d-0b6e-4899-8d97-2ee134a4ffcf">

OLD UI

<img width="1172" alt="Screenshot 2024-01-08 at 14 32 21" src="https://github.com/dappros/ethora/assets/328787/d34d7875-3b2f-4b0b-823c-0cdfc72210a7">

<img width="1228" alt="Screenshot 2024-01-08 at 14 32 36" src="https://github.com/dappros/ethora/assets/328787/8e494205-1c6b-492c-b26b-45e438cc6484">

CONCEPT 

<img width="1248" alt="Screenshot 2024-01-08 at 14 34 56" src="https://github.com/dappros/ethora/assets/328787/7442c9fc-aa5d-4042-abe5-593fe03d14cf">

NEW UI + OLD CHAT DETAILS UI

<img width="1170" alt="Screenshot 2024-01-08 at 14 34 27" src="https://github.com/dappros/ethora/assets/328787/73172cdd-f798-4d5d-8517-f505c029e948">

CHANGE WALLPAPER FEATURE

<img width="1267" alt="Screenshot 2024-01-08 at 14 35 49" src="https://github.com/dappros/ethora/assets/328787/8be03ab5-3bb2-474d-a351-3a6b09e48017">

<img width="1149" alt="Screenshot 2024-01-08 at 14 36 06" src="https://github.com/dappros/ethora/assets/328787/da83c5f7-c36a-4fce-88ad-3854cd96d093">

<img width="1219" alt="Screenshot 2024-01-08 at 14 36 26" src="https://github.com/dappros/ethora/assets/328787/70c42e35-4631-4328-8fdd-7f63b5aef29c">

UI ELEMENTS / CONTROLS THAT SHOULD BE INCLUDED

**Controls**

- “Star” button - allows to add/remove this chat from Favourites tab
- Mute/unmute button - allows to mute/unmute push notifications from this room. Here shown as a slider button, but typically this is a bell or crossed bell icon. 
- “Bin” button - delete Chat Room (only for owners and admins)
- (optional - maybe via menu or majordomo bot) Change wallpaper (background) for the Chat Room
- (optional - maybe via menu or majordomo bot) Change soundtrack for the Chat Room
- “Leave” button (unless we have it in the Chat screen itself) - allows to leave the room (user is removed from participants and subscribers)
- “QR” button - allows to share the QR code or link to this room, similarly how it’s done in the User Profile screen
- Change wallpaper (or menu for advanced actions*) (* we may have other features such as set background music, set up a default bot etc - may be useful to have a submenu to allow adding more features like this, but not sure what’s best at the moment)

**Central** 

- Chat (Room) Image (+ edit option for managers) 
- Chat (Room) Title
- Chat (Room) Description (+ edit option)
- List of members with roles (+ “kick” option) 

**List of members (+ counter)**

- List of members with roles (+ “kick” option for managers) 
- Role tags (owner, admin, moderator)
- When clicked on any member, opens their Profile page.
- Swipe left or Long Tap (or other UI option) for a member menu allowing to manage roles or kick user
- List of kicked members (+ “unkick” option for managers)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/31a79f45-2fb8-4330-a336-5a0ffefa9328)
![image](https://github.com/dappros/ethora/assets/149969403/ac5ccab8-c0ec-4dac-afab-9e47aa487778)
![image](https://github.com/dappros/ethora/assets/149969403/729859b9-c022-48f8-a8fc-ad660b981d96)
![image](https://github.com/dappros/ethora/assets/149969403/2217081b-7a35-42a2-a343-f11e4574dccf)
![image](https://github.com/dappros/ethora/assets/149969403/f15e9b64-0abb-4717-ad5f-4d90b790f200)
![image](https://github.com/dappros/ethora/assets/149969403/b4804fac-01fe-4b25-9778-a8f4ef9cbe5e)

Ready screens: Chat details screen for member, Chat details screen for admin, Chat details screen collapsed, Former members, Edit chat, Edit chat photo, Member details, Delete room modal, Change background wallpaper, photo and color, QR-code for chat.
@phwizard

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/f76e2279-5f7c-4b57-8f55-00c193a544b2)
![image](https://github.com/dappros/ethora/assets/149969403/5ba2292b-374d-4b8a-8821-e63c8d474a06)
Updated screens and modals
@phwizard

**Comment by phwizard** [comment]
thank you Polina, looks great! 

I think we can go ahead with implementing these screens

pasting below our Slack discussion on the previous update here so that we have it in the history of the issue:

TF:
sorry maybe I wasn't clear with the 'removed' users
the idea is that chat admins can ban users
the ban can be temporary or permanent
we don't need a separate section for removed users unless you think it looks better, otherwise we can just show them normally in the list
next to each banned user we can show "banned" and we may also want to show who banned them, when and when the ban expires but I'm not sure if we should fit all that. Maybe have a look how it works in other chat/social platforms
also I have a question it seems you have 2 QR buttons?

TF: 
there also could be a button to "unban" or "unkick" available for admins
for each user who is not banned, we can show "ban" button for admins, and for those who are banned we can show "unban" and show in small letters information regarding when the user was banned

PP:
I think we can manage without a separate screen for deleted participants. By long-pressing on a member in the chat details, we can add in a modal window info about who/when/how long the member was banned. I will also add a button for admins to lift the ban.
Regarding the QR-code, my mistake. I forgot to remove it from the menu buttons, sorry.
