### ISSUE TITLE
Web client - Main screens redesign

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#545]
**Goal:**
Introduce updated designs for the web-client main screens.

**Affected metric:**
- UI / UX enhancements
- Ease of data handling

**Description:**
Create new designs for Ethora web-client, namely for main screens: login page, app screen, new app creation and configuration screens. 

Use old designs as a reference:

**Login page**
![image](https://github.com/dappros/ethora/assets/99117374/e278197c-833f-4abe-b879-38ddd2b32384)

**Apps section**
![image](https://github.com/dappros/ethora/assets/99117374/2a799b44-c513-4659-b898-bc3aefb7d54d)

**Create new app modal**
![image](https://github.com/dappros/ethora/assets/99117374/3e31a85e-0bfb-41ac-9be7-f5cf07fa1457)

**App configuration / creation**
![image](https://github.com/dappros/ethora/assets/99117374/8b31b7f3-7c21-44f0-b749-cef08fe3cfb0)

![image](https://github.com/dappros/ethora/assets/99117374/b507137d-9ce8-4e0c-8ca9-59a8e2e3cd23)

![image](https://github.com/dappros/ethora/assets/99117374/08d6ba15-6c4b-4f3a-8507-2bd6007fe9b9)

**Comment by polipivnenko** [comment]
The first versions of the appearance settings, user defaults screens and apps table.
![image](https://github.com/dappros/ethora/assets/149969403/924c0866-3ccc-43d0-929c-903b9e64578e)
![image](https://github.com/dappros/ethora/assets/149969403/5b5a9e05-4978-4087-b0f8-cb71413bcb56)
![image](https://github.com/dappros/ethora/assets/149969403/4e0efb1c-c1fc-4dd2-a0c1-573a97bb3bb8)


@dzinzyura @phwizard

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/1cb2e57a-e564-4ff9-9187-85230fbc2a07)
![image](https://github.com/dappros/ethora/assets/149969403/058c5de0-2e11-467a-9cb2-dcaccf8ac9b8)
![image](https://github.com/dappros/ethora/assets/149969403/5e2cc3ac-8eae-4f51-a675-aa21eec7e9dc)

Login page, create new app modal, App configuration are ready
@dzinzyura @phwizard

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/63f94936-e4cc-406f-828e-7248563d77aa)

@dzinzyura @phwizard 
Updated Login screen
