### ISSUE TITLE
Design - Menu & screens enhancement

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#546]
**Goal:**
Introduce updated designs for the menu and its associated screens.

**Affected metric:**
- UI / UX enhancements

**Description:**
Redesign the existing menu and its screens. 
You don't have to redo everything totally, but let's make the screens look better.

Please, use old screen as a reference for updates:

**Menu itself**
![image](https://github.com/dappros/ethora/assets/99117374/e4bf5a21-fa2b-461d-8670-c2fe88af8640)

**Referrals screen**
![image](https://github.com/dappros/ethora/assets/99117374/d8b37e1a-63f1-4b8c-a9a3-f40506748826)
![image](https://github.com/dappros/ethora/assets/99117374/b9c64611-762b-48b1-98e7-188be78e78ae)

**Buy coins screen**
![image](https://github.com/dappros/ethora/assets/99117374/421b0c4d-6cb0-454d-9e8e-4ce4b973185c)

**Mint items screen**
![image](https://github.com/dappros/ethora/assets/99117374/bbdb3be9-42e1-44db-a8e6-0e0e5ab43cbe)

**Upload document screen**
![image](https://github.com/dappros/ethora/assets/99117374/d292c34c-3021-4b86-979e-ab4bf336fe53)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/666a2eec-4553-4671-9feb-14145f1eb425)![image](https://github.com/dappros/ethora/assets/149969403/90d9afc9-af4f-47b3-a132-faf6bd3306d2)![image](https://github.com/dappros/ethora/assets/149969403/f0baecb0-85cc-426e-b108-9f7c03a3ef61)![image](https://github.com/dappros/ethora/assets/149969403/271ae48c-b1c0-44a2-9712-7f09add9fad7)![image](https://github.com/dappros/ethora/assets/149969403/0e09a74a-d56f-4517-b293-d3f03ba2095e)

@dzinzyura @phwizard

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/26751291-9ab8-4e8a-988d-52a969d24aea)

![image](https://github.com/dappros/ethora/assets/149969403/aa60c453-417b-4831-a887-10f09ff4ae77)

Updated upload-element and QR-Scan screen

@dzinzyura @phwizard
