### ISSUE TITLE
Design - Web-client - User profile

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#547]
**Goal:**
Revamp the user profile screens on our web-client platform to enhance usability and user satisfaction.

**Affected metric:**
- UI / UX enhancements
- Usability enhancements

**Description:** 
Implement new designs for Ethora web-client user profile screens. 

**Current designs**

_Own profile (scrollable page):_
![telegram-cloud-photo-size-2-5341819653065921697-y](https://github.com/dappros/ethora/assets/99117374/496cd04b-d330-466c-ba6e-6028281814af)

_Share profile:_
![telegram-cloud-photo-size-2-5341819653065921699-y](https://github.com/dappros/ethora/assets/99117374/d81046cc-7e10-4ee5-a781-a2cb1a6ad58e)

_Edit profile:_
![telegram-cloud-photo-size-2-5341819653065921700-y](https://github.com/dappros/ethora/assets/99117374/3af8a4fd-9248-4905-94e9-5447f636be9e)
![telegram-cloud-photo-size-2-5341819653065921701-y](https://github.com/dappros/ethora/assets/99117374/bb590132-266a-4e6b-942d-daa147cb23f6)

_Items provenance:_
![telegram-cloud-photo-size-2-5341819653065921702-y](https://github.com/dappros/ethora/assets/99117374/209f441f-8a5c-4de2-80e4-08e1c876b20e)

_Transactions:_
![telegram-cloud-photo-size-2-5341819653065921703-y](https://github.com/dappros/ethora/assets/99117374/2ba40926-e693-4941-9516-f86a6ab99aab)

_Other user profile:_
![telegram-cloud-photo-size-2-5341819653065921748-y](https://github.com/dappros/ethora/assets/99117374/f9771dc4-3bcf-49ab-a5f0-54ac79bba7ae)

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/2477312b-cdd7-4378-a175-e7729900f4da)
![image](https://github.com/dappros/ethora/assets/149969403/ec6bc751-1976-4d0d-9ec4-ea1b81a362eb)
![image](https://github.com/dappros/ethora/assets/149969403/2612b8f8-29b1-4f1e-adaf-627598af8d11)
![image](https://github.com/dappros/ethora/assets/149969403/143b2650-3713-4213-a41d-3579a1ccf8a9)

A version of the personal and other user's profile screen. Personal profile edit screen (with locked document/transaction block) and QR code modal

@dzinzyura @phwizard

**Comment by polipivnenko** [comment]
@dzinzyura @phwizard 
Screens for another user's account page. I've placed all the tabs to scroll down, and also, when clicking on the "Transactions" button, it quickly scrolls down to the transactions tab at the bottom of the account page.

![image](https://github.com/dappros/ethora/assets/149969403/9c1b1091-d399-47d3-ac59-1086cad322d7)
![image](https://github.com/dappros/ethora/assets/149969403/4d8c9ef6-f5d0-4175-8b26-7efc7c48fe27)
![image](https://github.com/dappros/ethora/assets/149969403/e3e57d1f-ee22-410f-8415-ae21f06bffa4)
![image](https://github.com/dappros/ethora/assets/149969403/7d3b7712-7b35-491f-9130-64090e40c89e)
![image](https://github.com/dappros/ethora/assets/149969403/0e601909-5a84-4327-9ae8-7ddbcf7ba596)
![image](https://github.com/dappros/ethora/assets/149969403/ca8b7a1c-6e82-4d8e-8b92-e7b1640594c4)

Screens for own user's account page. The same system, except the "message" button is missing, and the account editing function has been added. Also, modal windows for making changes to profile pictures.
![image](https://github.com/dappros/ethora/assets/149969403/8b6c9a26-7369-41ce-848e-fb7fd8d57762)
![image](https://github.com/dappros/ethora/assets/149969403/8c55c7d9-1667-41eb-993c-04406f0dc272)
![image](https://github.com/dappros/ethora/assets/149969403/3ba8a077-2a90-4d25-83ce-96b35aae3a91)
