### ISSUE TITLE
Discuss synergies with Starknet

### ISSUE THREAD

**Issue by AbdelStark** [dappros/ethora#550]
Hey, would love to discuss potential synergies / collaborations between Starknet and Ethora.

**Comment by dzinzyura** [comment]
Hi @AbdelStark!

Thanks for reaching out! We're excited to learn more about your interest in Ethora.

To get started and explore the details further, please fill out our quick contact form on ethora.com.

Once you've submitted the form, we'll be in touch soon to discuss your specific needs and answer any questions you may have.

In the meantime, feel free to browse our website for more information. 

Thanks again for your interest!

Best regards,
Vladyslav 
The Ethora Team
