### ISSUE TITLE
WalletConnect integration

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#57]
Let's create an experimental build that will help us to move further with our L2 <-> Mainnet connectivity roadmap items. 

Flow:

* Check if loginWalletConnect (or loginMetaMask) option is enabled in the config. If yes, proceed. 
* Login screen - shows WalletConnect (or Metamask) button under social login buttons
* WalletConnect or Metamask button opens the external UI / app (if installed by the user) that allows user to authenticate their external (non-custodial) crypto wallet through that app outside of Ethora
* Once authorised, either:
* (A) Create a DP user and record their L1 wallet (external wallet) via API
* (B) sign in an existing DP user if record already exists with this external wallet 

====

Clarification notes:

* In current version, users are identified and addressed with Ethereum address internally for all purposes (user account, wallet, chat/messaging etc), but normally this address comes from an internal custodial L2 wallet.
* For Metamask integration we should treat it similarly as social sign-on with social/email services. This means a DP user is still created with an internal L2 wallet, however for such user their external Metamask L1 / Mainet cold wallet address is stored and becomes the main identifier.

**Comment by phwizard** [comment]
This is now fully supported in the backend (storing EOA address and storing "verified" status if verification message is signed).

**Comment by phwizard** [comment]
@4RGUS please try to help on this issue - using a different Mac set up.

**Comment by phwizard** [comment]
Clarification regarding users who use WalletConnect as their first / primary login hence they don't have their name etc imported automatically.

Such users should only be allowed to proceed after they complete a compulsory "introduction" form. Upon sign in via WalletConnect, show them a modal window with the following content: 

Please provide a first name and last name.

This will be displayed in your profile and chat messages.

First name:
Last name:

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/183055409-cbc666bb-d17c-4979-bafa-ebde981aa978.mov

**Comment by phwizard** [comment]
Great stuff @dendidibe!

Please move the Metamask login button to the bottom of the list and make sure it's included in the Login options in the Config so developed can switch it on/off for their projects.
