### ISSUE TITLE
Login options to Config

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#60]
Suggest to move social and other login options to a Config section so that developers / publishers can enable/disable options there as required.

======================
UPD (more details):

Our previous default option for users login was E-mail + Password via Dappros Users API.

Current default option is SSO (social sign-on) where we have Facebook, Gmail and Apple options.

Different projects need different configurations. Some want all options, some don't want social sign in at all etc.

Let's make this manageable from the Config so that developers can enable/disable each option separately:

something like this for current default option:

loginFacebook = true;
loginGmail = true;
loginApple = true; 
loginCustomEmail = false;

======================

**Comment by phwizard** [comment]
clarification - we need the following options:

- SSO - Facebook
- SSO - Gmail
- SSO - Apple
- Custom - E-mail + password
- Custom - Login + password

the latter option is needed for projects who don't want to use E-mail as Login, and prefer to use a conventional "login name" instead. In this case e-mail should be collected and validated separately to be used for password reset and other purposes.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/185382869-967889c7-0b82-4e13-8543-4127329a9a5a.mov

**Comment by dzinzyura** [comment]
Looks great, thanks, Mike! 
Also, please, add the possibility to create/login with the e-mail credentials

**Comment by dzinzyura** [comment]
Done. Works and looks great! Thank you, Misha!

https://user-images.githubusercontent.com/99117374/187876592-b375084c-e556-403c-8d71-29f30eb59b1a.mp4
