### ISSUE TITLE
Invite friends - mechanics research & story

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#66]
We want to allow users to invite their friends and earn 100 Coins each (both the user and their friend/contact who has joined).

This way the Ethora powered communities can grow faster and have a better chance to gain the necessary critical mass in their groups to be self-supporting. 

The server-side / blockchain part is straightforward. We need to figure out the optimal frontend / UI / UX for the end users.

Tasks and questions:

1. Shall we use address book / contacts or simply share the link/code via standard social channels or direct message? I believe the latter is the simpler option.

This example shows using e-mail and SMS composer to send invites to your address book: https://blog.expo.dev/help-your-users-share-their-love-for-your-app-with-react-native-7549b1b0b3af

This is tempting as it's more personalized and viral using SMS and e-mail channels, but it also requires more movements from the user. Also, people aren't likely to use SMS for this. 

2. Shall we leverage any existing trusted SDKs or APIs? Example:
https://stackoverflow.com/questions/52271284/react-native-implementing-reward-referral-invite-and-earn
https://firebase.google.com/docs/dynamic-links/use-cases/user-to-user
https://www.npmjs.com/package/react-native-invitereferrals

3. Deep linking  / eto.li shortener should be used so that we can (1) bring user into reward claiming interface if user already has the app installed or (2) redirect to appstore if user doesn't have the app installed. 

Example of deep linking: https://www.educative.io/edpresso/react-native-reward-referrals

===========
**STORY**
===========

Alice opens her Ethora-based app.
 
Menu → Referrals & Bonuses → Refer & Earn

(there are 2 tabs there:

“Refer & Earn” - the default tab where user can obtain their code and share it with others.

“Enter code” - the 2nd tab where user can enter their referral or bonus code.

 
Example:

======

Refer & Get 100 Coins
Both you and your referred person receive 100 Coins.

Your Referral Code: e4cx97srp9

[ Agree and Share Now ]

======

Alice taps [Agree and Share Now]

App offers standard/system sharing options.

Alice proceeds with one of the options and sends the code to her friend Bob.

======

Bob receives the code via a social channel or e-mail.

Bob opens his Ethora-based app → Menu → Referrals & Bonuses → Enter Code

Bob enters Reward Code

System sends 100 Coins (the default app coins, ERC-20 token) to both Alice and Bob. 

 
The above transaction is visible on each of their profiles in the transactions history.

(Specify “Referral bonus” in the transaction description if possible.)

 
======

The referral code is the same and unique for each user.

So for example Alice has the same code “e4cx97srp9” and it will remain the same for all of her friends that want to join the app using her referral. 
 
We could probably use the public key and/or QR code for this referral, same as the QR code when user’s profile is shared, however that code is too long if used in text format. Probably need to create some shorter hash based on user’s public key?

======

There should be a limit of only 1 time that Bob can enter a sign-up referral reward code from any other user.
( suggestion:
include a flag signUpCodeUsed for each user in the Users profile?
This way if user has used it already, this value will be non-empty.
We can also track whose codes have been used most often if needed.
)

However it’s not critical for us to enforce this limit in 1st implementation. 

In future we might use the same interface for “Enter code” for other bonuses/reward purposes, not just for sign-up referrals.

======

P.S. I would also love to see this mechanism work via a smart contract, but perhaps easier to make it a backend/API based at this point. 
 
======

**Comment by phwizard** [comment]
Completed, but we need to review the mechanics. Moving this to milestone 22.08.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/187177284-1b619e5f-1bb5-4641-b76c-d9fe30233314.mov

**Comment by dzinzyura** [comment]
Done.
Looks great, thank you!
