### ISSUE TITLE
Image thumbnails for chats

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#75]
Option for room Owners and Admins to upload images for the room/space via chat edit menu.

Use same mechanism (IPFS) as for attachments etc.

If image is uploaded, the chat room thumbnail will change from the default "initial" letters mode to the uploaded picture thumbnail.

====
**Clarified**:

To describe how to associate chat rooms (JID) with IPFS link (file attachment). 

A) Using DP User for each Room/Space (as planned previously)
**B) Using a name convention (so for example using room JID as a file name in our Files API / DB)** 

1. Chat Owner / Admin uploads an image via Ethora UI (manage chats UI).
2. Application uploads it via Files API and uses room JID as filename. 
3. When other users look into chats list (Lobby screen) the Application looks for files with JID == chats in the list and shows the thumbnails of the rooms if they exist. If not, fall back to default option showing room initials.

====

**Comment by phwizard** [comment]
To describe how to associate chat rooms (JID) with IPFS link (file attachment). 

A) Using DP User for each Room/Space (as planned previously)
**B) Using a name convention (so for example using room JID as a file name in our Files API / DB)** 

1. Chat Owner / Admin uploads an image via Ethora UI (manage chats UI).
2. Application uploads it via Files API and uses room JID as filename. 
3. When other users look into chats list (Lobby screen) the Application looks for files with JID == chats in the list and shows the thumbnails of the rooms if they exist. If not, fall back to default option showing room initials.

**Comment by phwizard** [comment]
better to do this via XMPP

**Comment by phwizard** [comment]
@Akick can you please add into the plugin for the rooms list so that it also returns a field with roomIcon, roomBackground.

**Comment by phwizard** [comment]
So either here or vcard or plugin, we should also add fields for 

roomThumnbail
roomBackground

which will be links to images files.

**Comment by Akick** [comment]
@phwizard I made changes in the mod_get_user_rooms plugin

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/193551915-6f7db78e-41cc-449f-8233-41886ff5a157.mov

**Comment by phwizard** [comment]
Done, thank you.
