### ISSUE TITLE
Debug (Jester) bot

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#79]
We might need a chat bot that sends a message into the room every 5 minutes, so that we can test push notifications and other features. 

The bot can use one-line jokes from a text file posting one randomly every 5 minutes.

Source example:
https://github.com/yesinteractive/dadjokes/blob/master/controllers/jokes.txt

To start the bot, say "start jokes", "jokes start", "start jester" or "jester start".

To stop the bot, same as above but using "stop" instead of "start".

**Comment by Egatlov** [comment]
Current update:

1) Bot can join chat
2) Bot listens to the message from the user that says "jester start" or "start jester" or "jokes start" or "start jokes"
3) Bot starts sending messages at the interval of 1 min (will be changed to 5 mins)

Remaining:

1) Convert provided jokes.txt to JSON and send a random joke every 1 min
2) Stop the look when a user enters "jester stop" or "stop jester"
