### ISSUE TITLE
Raffle Bot

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#85]
This tasks is to implement a Raffle Bot to improve gamification within our platform and support scenarios where artists, famous people, event hosts and usual users want to give away some NFT Item randomly in a room. 

=====

Alice: Raffle bot

Raffle Bot:
Do you want to raffle? This works simple: send me an Item and specify the duration.
All users who write something into chat before the timer runs out will participate in the raffle. 
I will randomly pick the winner and send the Item to them!

Raffle Bot: 
One more thing - please transfer 7 Coins towards my costs and we will proceed.

Alice:
// transfers 7 Coins to Raffle Bot

Raffle Bot:
Thank you! Now, what should be the duration? 
[ 3 minutes ]
[ 5 minutes ]
[ 10 minutes ]
[ 30 minutes ]
[ 1 hour ]
[ 1 day ]
[ Cancel ]

Alice:
[ 10 minutes ]

Raffle Bot:
Perfect, just send me the prize item now and we are good to go!

Alice: 
// sends some Item to Raffle Bot

Raffle Bot:
Thank you. I’m pleased to announce that the raffle registration is now on!
The time now is 20:15:21 GMT, all users who write a message during next 10 minutes will all be counted as participants!

Bob: 
hello

Raffle Bot:
Bob, you’re in! 

Charlie:
count me in

Raffle Bot:
Charlie, you’re in!

Alice: 
hey guys

Raffle Bot:
Alice, you’re in!

// 1/3rd of the time period passes

Raffle Bot:
To remind everyone, the raffle is on the and the prize is [<Item name>].
The raffle will end in [<X>] minutes. 
Just write a message to be counted in!

// 2/3rd of the time period passes

Raffle Bot:
To remind everyone, the raffle is on the and the prize is [<Item name>].
The raffle will end in [<X>] minutes. 
Just write a message to be counted in!

// 1 minute remaining 

Raffle Bot:
There is just 1 minute left until the winner of the raffle is announced! You can still participate by writing any message here. Quick!

// duration has expired

Raffle Bot:
TA-DA!!! The raffle is now officially complete! Announcing the winners in 1..

// 1 second delay

Raffle Bot: 2..

// 1 second delay 

Raffle Bot: 3..

// 1 second delay 

Raffle Bot: And the winner is.. 

// 1 second delay 
// Raffle Bot randomly chooses a winner across all participating users excluding itself.

Raffle Bot: <winner name>!!!

// 1 second delay 

Raffle Bot: Congratulations, <winner name>, here is your prize!

// Raffle Bot transfers the Item to the winning user.

**Comment by phwizard** [comment]
@dzinzyura 
we can return to this and implement this, please assign either Nikhil or Anton

**Comment by dzinzyura** [comment]
The main functionality is done. Great stuff, guys, thank you!

[Video](https://dappros.slack.com/files/U02TQ529R1U/F04FATH8H45/screen_recording_20221215_160350_ethora.mp4)
