### ISSUE TITLE
Backend: e-mail validation

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#92]
Proper / improved e-mail validation mechanism for end users when using e-mail + password login option.

1. Allow user to sign up with e-mail.
2. Send validation e-mail with a unique link to user's e-mail upon registration.
3. Don't allow user to sign in until user has clicked the unique link in the e-mail.

**Comment by dzinzyura** [comment]
Done. Thank you, @transkarpation!

https://user-images.githubusercontent.com/99117374/187877380-c0b1cdd8-5058-4e75-b0ad-a47597eb7b9f.MOV
