### ISSUE TITLE
Backend: password reset

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#93]
We have a password reset mechanism for Owner / DP users, but need to implement a more user-friendly password reset / password update mechanism for the end Users in Ethora engine.

Users should be able to specify their own password.

**Comment by dzinzyura** [comment]
**Client side (UI)**

For the E-mail + password credentials, please, add the "Forgot password" button, which will lead to the reset password route

For the Username + password we can add the same button, but this button will open the page or modal with such text:

"For some privacy reasons, Ethora does not store any user credential information. 
Please, create a new account if you forget your password."

@dendidibe

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/188836815-d843529a-b814-4cc7-bc3a-5f633a0b237b.mp4

**Comment by dzinzyura** [comment]
Looks great, thank you, @dendidibe!

I'll also think about the UI for the modal with warning

**Comment by phwizard** [comment]
Done.
