### ISSUE TITLE
Profile sharing update 

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#95]
The profile sharing screen is to be updated as follows:

1. Change first button text from "Share" to "share QR (visual)" 
2. Rename 2nd button as "copy link (text)" 

![Screenshot_2022-07-04-12-32-08-409_com.ethora.jpg](https://user-images.githubusercontent.com/328787/177146420-5558bb1e-1238-4da3-9c42-d4c2d302b813.jpg)

**Comment by phwizard** [comment]
I have removed this

====
3. Add 3rd button underneath "copy wallet address" 
"copy 🔗 address"  should copy the Ethereum address of the user into the buffer.
====

from the task, it's going to be a bit confusing, we will add it in some better way later

**Comment by phwizard** [comment]
@Egatlov let's visualize this

**Comment by Egatlov** [comment]
![shareProfile](https://user-images.githubusercontent.com/10884207/179691160-42a7f1ff-b9bd-4873-81a7-dd67c47ad441.png)
@phwizard Let me know if this looks good or we need any more modifications.

**Comment by phwizard** [comment]
@Egatlov thank you, this is good, only feedback:

1) remove "(visual)" as it's quite clear now
2) remove "text", so just "Or copy.link"

@4RGUS can you please.go ahead and implement this update

**Comment by Egatlov** [comment]
![Share profile-2](https://user-images.githubusercontent.com/10884207/182541387-d582260f-b1f7-4541-9547-d1043c26a6b0.png)
updated preview
