### ISSUE TITLE
Item in-room display

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#97]
**Display an Item in a chat**

We need to have a functionality allowing users to demonstrate their NFT Items and collections in the room/chat so that other users can interact with such items or be aware of their existence. 

This is similar to sending a file attachment into a room, however user is sort of "picking from a gallery" instead of uploading a new file. 

**What should be implemented**:

Tapping on "file attachment" icon shows following options:
* Upload File
* Display an Item [ show only if User has any Items in the wallet/profile ]
* Cancel

In case "Display an Item" is tapped, this shows UI picker allowing the User to pick one of the items held in User's own wallet / profile. 

As soon as the Item is selected, this sends a special message stanza into the room that is similar to a file attachment, however instead of uploading a new file it will display an existing file.

**Comment by dendidibe** [comment]
https://user-images.githubusercontent.com/54039544/179212224-95271bb5-883f-4c37-81cd-f643fd522037.mov

example of work

**Comment by phwizard** [comment]
Done.
