### ISSUE TITLE
Bot: Merchant Bot

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#99]
Use scenario:

Alice: Bot Merchant
(or "merchant bot”, or "get NFT", or "buy NFT")

Merchant Bot: Hi, I’m the Merchant and will help you to get some unique Items in no time!

Merchant Bot: Best prices this part of the galaxy!

Merchant Bot: Now, do you happen to know a name or an address of the Items Collection that you like to mint or purchase from? 

Merchant Bot: Alternatively, we can browse some recent Collections with you.

[ Browse recent Collections ]

[ Leave ]

Alice: 0x242394239474311 
(Collection address)

Merchant Bot: one moment..

Merchant Bot: found it!

Merchant Bot: Let me get some details for you.

Merchant Bot: Now, the Collection is called CryptoBikes and these are the details:

Merchant Bot: 12 “Bronze” left out of 245 total: Free

Merchant Bot: 8 “Steel”: left out of 100 total: 100 Coins

Merchant Bot: 25 “Silver”: left out of 50 total: 200 Coins

Merchant Bot: 5 “Gold”: left out of 25 total: 500 Coins

Merchant Bot: 3 “Diamond”: left out of 5 total: 1,000 Coins

Merchant Bot: Now, which Item would you like to get?

[ 1 x “Bronze” for Free ]
[ 1 x “Steel” for 100 Coins ]
[ 1 x “Silver” for 200 Coins ]
[ 1 x “Gold” for 500 Coins ]
[ 1 x “Diamond” for 1,000 Coins ]
[ Browse recent Collections ]
[ Leave ]

Alice: 

[ 1 x “Steel” for 100 Coins ]

Merchant Bot: Great. That would be 100 Coins, please.

Alice: (transfers 100 Coins to Merchant Bot)

**TO DO: CLARIFY WHETHER SENDING TO BOT OR COLLECTION CONTRACT**
**A) BOT DOES MINTING ON BEHALF OF THE USER
B) SHOW "AS IF" BOT DOES IT, BUT IN FACT USER INTERACTS WITH SMART CONTRACT DIRECTLY**

BACKEND QUESTION:
A) BOT WORKS WITH B/C DIRECTLY VIA WEB3 LIBRARY
B) BOT WORKS VIA OUR API 

Merchant Bot: Know that you have made an excellent choice. Enjoy!

(mints and transfers the “Steel” item to Alice).

**Comment by dzinzyura** [comment]
Bot works great. Thank you, guys!

![Screenshot_38](https://user-images.githubusercontent.com/99117374/187864409-a2b4136a-a1cc-4268-9ec9-c64d83f4c3cc.png)
![Screenshot_20220901_110251_com ethora](https://user-images.githubusercontent.com/99117374/187864435-6a314807-ab40-420c-a4a8-5ad215f90717.jpg)
